### ISSUE TITLE
[Translate] Italian translation

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#1]
# Language you want to translate to
Italian
# Description
@dzpex I've seen that you forked the jamulushome repo: https://github.com/dzpex/jamulushome

We have just moved the repo here. Could you please use this repo instead?

**Comment by dzpex** [comment]
I make a pull request on the older repo....but i replicate on the correct now....

**Comment by ann0see** [comment]
Thanks! See the your pr for more information.

**Comment by dzpex** [comment]
I hope it's all correct....

**Comment by ann0see** [comment]
It looks ok now. Could you please check the site?
