### ISSUE TITLE
Update screenshots for "Delete Server" button

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#1002]
Documentation updates are required for
* https://github.com/jamulussoftware/jamulus/pull/3159
* https://github.com/jamulussoftware/jamulus/pull/3260
* https://github.com/jamulussoftware/jamulus/pull/3305

which relate to the addition of a "delete current entry" button to the Client dialogs Connect and Advanced Settings.

The amended English (primary) documentation should have replaced screenshots and any accompanying text changes that are required.

Weblate authors should, once these changes are available, make the required changes to the translations as usual (outside this issue).

**Comment by ann0see** [comment]
![connection setup window](https://github.com/user-attachments/assets/950c8dc1-b766-49b6-b88e-4bf9c38e6c2d)
Screenshot of connection setup window


![Advanced setup screenshot](https://github.com/user-attachments/assets/2869f401-347b-4b3e-b280-36a7b45d7ee6)
Screenshot of advanced setup

I hope these are the only screenshots which need to be changed

**Comment by ann0see** [comment]
Screenshots added for this. 
Doc changes may still be outstanding.

**Comment by ignotus666** [comment]
Adding screenshots in ES here to create links:
![con_setup](https://github.com/user-attachments/assets/e26d6131-de30-46a5-9145-7c539cb67c87)
![adv_setup](https://github.com/user-attachments/assets/85e6859b-c88a-4ace-ad4e-86993241c873)

**Comment by pljones** [comment]
![image](https://github.com/user-attachments/assets/e8b673e0-25a2-4861-883f-bb374c6df92b)

I'm going to take the opportunity to reword the text a bit.  Currently, how to actually connect has got a bit hidden in the depths.

#1007 opened -- I'm waiting for GitHub to do the build as I couldn't get it working on my fork.

**Comment by ann0see** [comment]
@pljones I think this is done

**Comment by henkdegroot** [comment]
Adding nl images here as well

![Connect-dialog_nl](https://github.com/user-attachments/assets/a8871f37-cd91-4c34-890a-0214470a91cd)

![Advanced-settings_nl](https://github.com/user-attachments/assets/158052b7-e2e3-413d-a48a-ed4a9ed6fe98)
