### ISSUE TITLE
"Software Manual" wiki page

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#1030]
_Originally posted by @pljones in https://github.com/jamulussoftware/jamuluswebsite/pull/1019#discussion_r1739858201_

The page title on the "Software Manual" wiki page is "Jamulus User Manual" - reflecting that it's _not_ the "Server Manual".

- "Jamulus" in the title is redundant
- references to the page use "Software Manual" which is confusing, as you land on a page called "User Manual"

It would be better if the page were titled "User Manual" and referenced as such throughout the wiki.

**Comment by gilgongo** [comment]
Fixed with https://github.com/jamulussoftware/jamuluswebsite/pull/1050
