### ISSUE TITLE
Identify canonical and alternate URLs

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#1033]
_Originally posted by @pljones in https://github.com/jamulussoftware/jamuluswebsite/issues/1026#issuecomment-2328492215_

I don't think it's right...

https://github.com/jamulussoftware/jamuluswebsite/actions/runs/10696055730
http://jamuluswebsite.drealm.info/wiki/Installation-for-Linux
```
<!DOCTYPE html>
<!--[if IE 9]>
<html class="ie9">
<![endif]-->
<html lang="en">
<head>
<title>Installation for Linux – Jamulus Website</title>
<meta charset="utf-8">
<link rel="canonical" hreflang="en" href="/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="/sv-SE/wiki/Installation-for-Linux">
...
```
http://jamuluswebsite.drealm.info/sv-SE/wiki/Installation-for-Linux
```
<!DOCTYPE html>
<!--[if IE 9]>
<html class="ie9">
<![endif]-->
<html lang="sv-SE">
<head>
<title>Installation för Linux – Jamulus websida</title>
<meta charset="utf-8">
<link rel="canonical" hreflang="en" href="/sv-SE/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="/sv-SE/wiki/Installation-for-Linux">
...
```

1. If `ie9`, we get _two_ `html` tags, which cannot be right.  Does IE 9 still exist?  Is the XML comment actually parsed?
2. The http://jamuluswebsite.drealm.info/sv-SE/wiki/Installation-for-Linux page says `canonical` is `en`, okay but gives the wrong `href` to get there.

I should have spotted that earlier, sorry!

**Comment by pljones** [comment]
```Jinja
<!-- Canonical and Alternate Links -->
{% comment %}
English URLs don't have a lang subdirectory since it's the default language.
See https://github.com/untra/polyglot
{% endcomment %}
        <link rel="canonical" hreflang="en"        href="{{ site.url }}{{ site.baseurl }}{{ page.url }}">
{% for lng in site.languages | sort %}
  {% if lng != "en" %}
        <link rel="alternate" hreflang="{{ lng }}" href="{{ site.url }}{{ site.baseurl }}/{{ lng }}{{ page.url }}">
  {% endif %}
{% endfor %}
```



| | `canonical` href | `alternate` href |
| -: | - | - |
| source| `"{{ site.url }}{{ site.baseurl }}{{ page.url }}"` | `"{{ site.url }}{{ site.baseurl }}/{{ lng }}{{ page.url }}"` |
| English | `"/wiki/Installation-for-Linux"` | `"/sv-SE/wiki/Installation-for-Linux"` |
| Swedish | `"/sv-SE/wiki/Installation-for-Linux"` | `"/sv-SE/wiki/Installation-for-Linux"` |

From the rendered output, it looks like `{{ site.url }}{{ site.baseurl }}` is empty, `{{ page.url }}` is the _language-specific_ page URL (i.e. `/wiki/Installation-for-Linux` or `/sv-SE/wiki/Installation-for-Linux`) and the additional `/` followed by `{{ lng }}` prefix is getting removed during creation of the HTML ("helpfully").

**Comment by gilgongo** [comment]
> 2. The http://jamuluswebsite.drealm.info/sv-SE/wiki/Installation-for-Linux page says `canonical` is `en`, okay but gives the wrong `href` to get there.
> 

I'm not seeing that when I run the site locally. I get this, which I think is correct? 

```
<link rel="canonical" hreflang="en" href="http://0.0.0.0:4000/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="http://0.0.0.0:4000/sv-SE/wiki/Installation-for-Linux">

```
 
Not sure I follow what you mean with the comment about IE9.

Do you mean this is some issue with GH Pages rendering vs doing it locally?

**Comment by pljones** [comment]
> I'm not seeing that when I run the site locally. I get this, which I think is correct?

Which language was your current language?

**Comment by gilgongo** [comment]
> > I'm not seeing that when I run the site locally. I get this, which I think is correct?
> 
> Which language was your current language?

`sv-SE` - also works OK if I switch back and forth between languages (did a git pull and switched to next-release before looking BTW)

**Comment by pljones** [comment]
I'm using the Website.zip file unpacked.
https://github.com/jamulussoftware/jamuluswebsite/actions/runs/10696055730
if I got the right file...
```
-rwxrwxr--+ 1 peter www-data 9117903 Sep  4 16:11 Website.zip
```

**Comment by gilgongo** [comment]
That's strange - wonder why they're different? I suppose it makes sense that it doesn't use FQ URLs, but that doesn't account for the the canonical being the wrong one.

**Comment by pljones** [comment]
Yep, just downloaded it again and looked directly in the file `_site/sv-SE/wiki/Installation-for-Linux.html` (with line breaks added)
```
<!DOCTYPE html>
<!--[if IE 9]>
<html class="ie9">
<![endif]-->
<html lang="sv-SE">
<head>
<title>Installation för Linux – Jamulus websida</title>
<meta charset="utf-8">
<link rel="canonical" hreflang="en" href="/sv-SE/wiki/Installation-for-Linux">
<link rel="alternate" hreflang="sv-SE" href="/sv-SE/wiki/Installation-for-Linux">
...
```

**Comment by pljones** [comment]
> That's strange - wonder why they're different? I suppose it makes sense that it doesn't use FQ URLs, but that doesn't account for the the canonical being the wrong one.

How are you running the site?  Are you generating it and then handing the output to Apache or are you running it with `po4a` or something and looking at the generated page source?

I'm wondering if Github is using a subtly different way of generating the output...

**Comment by gilgongo** [comment]
> > That's strange - wonder why they're different? I suppose it makes sense that it doesn't use FQ URLs, but that doesn't account for the the canonical being the wrong one.
> 
> How are you running the site? 

On an Ubuntu VM, I've got ruby with various gems to run Jekyll, and with all the po4a stuff. I git clone/pull, switch to next-release, run the po4a script (which BTW I see throws a warning about an unexpected closing div), then run `jekyll serve --host=0.0.0.0`. Jekyll has a built-in web server I guess. Basically [according to this](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/README.md#viewing-the-website-offline).

It's so I can test changes without having to make PR first.

**Comment by ignotus666** [comment]
> which BTW I see throws a warning about an unexpected closing div

That will go away when #1025 gets merged. It's because po4a is a little too strict about tags.

**Comment by gilgongo** [comment]
Closing with https://github.com/jamulussoftware/jamuluswebsite/pull/1039
