### ISSUE TITLE
[Bug] Unparsable json in headers

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#1049]
Probably a minor issue, but Google is complaining that [https://jamulus.io/kb/2020/03/28/Server-Rpi.html ](https://jamulus.io/kb/2020/03/28/Server-Rpi.html) and [https://jamulus.io/it/kb/2022/08/04/Translating-po-files.html](https://jamulus.io/it/kb/2022/08/04/Translating-po-files.html) have  "Error parsing an array value: missing a comma or closing bracket in an array declaration."

```
  {
    "@context":"https://schema.org",
    "@type":"BlogPosting",
    "headline": "Install Jamulus Server on a Raspberry Pi",
    
    
    "publisher": {
      "@type": "Person",
      "name": "fredsiva",
      
    }, <--- highlights this as the error location
    "author": {
      "@type": "Person",
      "name": "fredsiva",
      
    },
```

Looking at `_layouts/post.html` I'm not sure how to fix it though - does it need re-generating in some way?

**Comment by pljones** [comment]
```json
"name": {
  "key": "value",
}
```
has a trailing comma after `"value"`, which will confuse most parsers.  The template should be written to only add a comma _before_ the second and subsequent entry, rather than _after_ every entry.  (Some templating schemas have explicit support for this need.)

**Comment by pljones** [comment]
Or for this kind of `if` block:
```json
    "publisher": {
      "@type": "Person",
      "name": "{% if site.data.authors[page.author].name %}{{ site.data.authors[page.author].name }}{% else %}{{ page.author }}{% endif %}",
      {% if site.data.authors[page.author].url %}"url": "{{ site.data.authors[page.author].url }}"{% endif %}
    },
```
do this:
```json
    "publisher": {
      "@type": "Person",
      "name": "{% if site.data.authors[page.author].name %}{{ site.data.authors[page.author].name }}{% else %}{{ page.author }}{% endif %}"{% if site.data.authors[page.author].url %},
      "url": "{{ site.data.authors[page.author].url }}"{% endif %}
    },
```
so that the `{% if` starts _before_ the `,` that separates the conditional element from the previous content.

**Comment by pljones** [comment]
https://github.com/jamulussoftware/jamuluswebsite/pull/1051 just might work.

**Comment by pljones** [comment]
I get this:
```json
  {
    "@context":"https://schema.org",
    "@type":"BlogPosting",
    "headline": "Install Jamulus Server on a Raspberry Pi",
    "publisher": {
      "@type": "Person",
      "name": "fredsiva"
    },
    "author": {
      "@type": "Person",
      "name": "fredsiva"
    },
    "datePublished": "2020-03-28T00:00:00-05:00"
  }
```
http://jamuluswebsite.drealm.info/kb/2020/03/28/Server-Rpi.html

(I might contend - and I might have said before - that "publisher" should be "Jamulus Development Team", or some other representation of the jamulus.io site owners.)
