### ISSUE TITLE
Add <ไทย> [th]

### ISSUE THREAD

**Issue by dtinth** [jamulussoftware/jamulussoftware.github.io#1054]
# Language you want to translate to

Thai

# Description

Thailand is in the top 5 list of countries that used Jamulus the most, so might be fitting to have Thai translation. This issue is opened following instructions from https://github.com/jamulussoftware/jamuluswebsite/tree/release/_translator-files#adding-a-new-language

**Comment by ignotus666** [comment]
Hi @dtinth, that would be great! Could you please edit the issue title so `<Thai>` is _in_ Thai? (ภาษาไทย?). That way it will be displayed in the website's language selection menu in that language (if that makes sense).

**Comment by dtinth** [comment]
thanks for the suggestion, done.
