### ISSUE TITLE
Is it me, or is editing the site content now too difficult?

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#139]
I've just tried reviewing https://github.com/jamulussoftware/jamuluswebsite/pull/108 and realised I was getting pretty confused.

I find it very hard to work out whether proposed changes are going to work. I can review the raw content, but without the relevant UI context, it's like trying to watching a movie where only parts of the screen are visible to you at any one time (and what is visible looks nothing like the director intended). 

At the risk of further complicating things - what would happen if we had (yet another) branch for "refactoring" the docs (if that's what we're doing with adding whole new sections and stuff) which we could compile locally to looks at. A fork perhaps? Just some way in which we can see how the site would look and feel with certain changes so we can judge the changes properly. This is going to be even more important if we start incorporating images too.

I think this implies we'd treat that branch like a wiki and just commit directly to it without going though reviews in Github.

Translation doesn't (I assume) suffer from this though, so that can stay the same.

**Comment by ann0see** [comment]
Yes. It is a bit more difficult if you don't see the real UI. I don't think we can even add an open branch without granting public access to all branches (I don't think that's even possible). I suggest to try everything locally (you can just checkout the "simplify" branch for example). 
You can have a look at the raw files (and the preview tab) if you start a new review. Maybe this helps?

**Comment by gilgongo** [comment]
You can't see the proposed changes locally until they have been merged to a branch though. Can only repo admins merge then? I guess so.

Hm. So one thing about Github Pages is that they're not designed for collaborative editing. It's hard enough doing that with a simple site like ours, so it must be pretty much impossible making large changes to a complex site. 

Oh well. I'll close this as there doesn't seem to be anything we can do about it really.

**Comment by ann0see** [comment]
> You can't see the proposed changes locally until they have been merged to a branch though. Can only repo admins merge then? I guess so.

You can see proposed changes locally: clone the repository and run jekyll serve.

As far as I know, only repo admins can merge to main. But you can select the permissions per branch for groups in the repo's settings.

The GitHub Action might support building from two branches. I don't know. Maybe we could use it to generate a folder on jamulus.io which publishes the changes (jamulus.io/changes/)
