### ISSUE TITLE
[KB] Add page for setup with video conferencing tool

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#149]
I think somebody (not me since I have no real experience) should write an article for the upcoming knowledge base about

1. How to use Zoom or any video conferencing tool with Jamulus
2. How to setup a virtual audience like WorldJam (chrisrimple?)

> Also, is there experience using Jitsi or another open source video conferencing tool (instead of Zoom).

See: 
https://github.com/jamulussoftware/jamuluswebsite/pull/101#issuecomment-738336014

**Comment by gegeweb** [comment]
It talks about this subject on the francophone FB group (Jamulus + Jitsi Meet). I relayed this issue there.
Perhaps there will be a feed back!

**Comment by ann0see** [comment]
Would be great!

**Comment by ann0see** [comment]
@chrisrimple as far as I know, you're involved in the WorldJam. Maybe this ticket is something for you?

**Comment by chrisrimple** [comment]
@ann0see Thanks for the heads-up, I missed this one.  Yes, I would be happy to add content for this - I've been quite busy and have a lot of new/updated content to add.  Since the move of the Wiki, I haven't figured out how to edit it now - do I have to check in/out via github?

**Comment by ann0see** [comment]
No problem ;-). 

> Since the move of the Wiki, I haven't figured out how to edit it now - do I have to check in/out via github?

Yes. That's basically it. 

The next release of the documentation will have a new section called "community knowledge base". If you look at the _posts folder you'll see some example blog posts (they are mainly for stuff related to Jamulus but not necessarily part of the core functionality like the files in the wiki folder --> no translation and separate design so that users know it's additional information). 

If you don't have time, no need to rush ;-)

**Comment by gilgongo** [comment]
But see also... #317 ??

**Comment by ann0see** [comment]
@chrisrimple Just added a basic page (#432) based on https://github.com/jamulussoftware/jamulus/discussions/1456#discussioncomment-625852 and a few experiences I had. Feel free to edit the page as you want.
