### ISSUE TITLE
[Feature] More Vocal options for Choir down the intstrument profile in My profile

### ISSUE THREAD

**Issue by Sollenberg72** [jamulussoftware/jamulussoftware.github.io#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In a choir you have more different vocal options than in traditional barbershops (Soprano, Alto, Tenor and Bass). We have two options for Alto and Soprano = Alto 1 and Alto 2 and Soprano 1 and Soprano 2. This helps us to create groups in Jamulus and use the panorama button so that we can create the same feeling as in the room You stand in reality.

**Describe alternatives you've considered**
We want more choices under the menu for instruments for us who use Jamulus for our choir rehearsals. Today there is singing in the form of Soprano, Alto, Tenor and Bass. We need to divide Alto and Soprano respectively into Sopranos 1 and 2 and Alto 1 and 2, as there are divided parts in a choir.

**Additional context**
Vocal (soprano)
Vocal (soprano 1)
Vocal (soprano 2)
Vocal (alto)
Vocal (alto 1)
Vocal (alto 2)

I think soprano and alto without division need to remain for those who do not divide soprano and alto parts into 1 and 2 respectively

**Comment by gene96817** [comment]
For complete support of a classical chorus, this should be extended for Tenor1, Tenor2, Bass1, and Bass2.

**Comment by ann0see** [comment]
I‘m afraid this is the wrong place to request this. Please do so on https://github.com/corrados/jamulus/issues

How did you find this repo?

**Comment by ann0see** [comment]
Since volker will probably not look here, I've moved it to the main repo: https://github.com/corrados/jamulus/issues/772
