### ISSUE TITLE
[Bug] IP Rockers Link has changed

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulussoftware.github.io#156]
https://www.facebook.com/groups/619274602254947/permalink/811687086347030

_Message for Volker Fischer. The link to the IP Rockers on your wiki page https://jamulus.io/wiki/Demos needds to be updated. IP Rockers link is: https://soundcloud.com/.../the-ip-rockers-live-on-jamulus   I was not sure how to get a hold of you so I am posting here.  Thanks. Scott IP Rockers_

**Comment by ann0see** [comment]
@gilgongo should have a look at this before we start the translation phase.
By the way, @corrados you should be able to edit the file yourself.

**Comment by gilgongo** [comment]
Isn't it just a link change?

**Comment by ann0see** [comment]
I think so?

**Comment by ann0see** [comment]
We will have to re-add it from the current release branch since I removed it on changes

**Comment by ann0see** [comment]
By the way: the link @corrados mentioned is broken too (and I don't have access to the facebook group)

**Comment by gilgongo** [comment]
Doh - yes. Ok I'll fix it and commit to changes.
