### ISSUE TITLE
[en] consistency: "FOSS", "open source",...

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#163]
There are several places where it says "open source". It is ambiguous as "open source" doesn't necessarily mean it's free (as "free as a free speech").

Because Jamulus is distributed under a GNU GPL licence, it would then make sense that it should be at least "FOSS" (Free Open Source Software).

If we want to emphasise and disambiguate even further, we can use "FLOSS" or even "libre software" as [written and suggested by Stallman on the FSF website](https://www.gnu.org/philosophy/floss-and-foss.en.html).

@corrados : it would make sense for you to share your opinion here.

**Comment by gilgongo** [comment]
We discussed this in the context of the wording on the home page 

https://github.com/jamulussoftware/jamuluswebsite/blob/e5e8587410387496d47503770ae6108192d137d5/1-index.html#L49

"Jamulus is free and open source software licensed under the GPL"

**Comment by trebmuh** [comment]
@gilgongo that is correct that we've discussed about **one** occurrence of "free and open source" in #46.

The reason of this very thread I've opened is to check if that's OK for everyone to apply the same to every occurrences we can found in all the English pages.

There are several occurrences of "open source" and others of "free and open source" in the pages. I'd like to make sure here that both are written with the idea of "free and open source", then we could rewrite them all like that for more consistency.

**Comment by ann0see** [comment]
I'd be ok with open source, free software, FOSS or FLOSS although they're slightly different. I think it's up to @corrados

**Comment by corrados** [comment]
> It is ambiguous as "open source" doesn't necessarily mean it's free

Valid point. I think there are hundreds if not thousends of discussions about this "free" topic of open source software...

> @corrados : it would make sense for you to share your opinion here.

The only thing I can say about it is that the Jamulus licence is GPLv2. As long as the users comply with that licence, they can use the source code. If that means that the software is free ... Maybe? :-)

**Comment by gilgongo** [comment]
The term "open source" is, for better or worse, the most widely used term to describe something under the GPL. I'd stick with that myself.

**Comment by trebmuh** [comment]
> The term "open source" is, for better or worse, the most widely used term to describe something under the GPL

I totally disagree.

**Comment by ann0see** [comment]
Open Source is probably more common while Free Software is the GNU term (where the GPL came from). At least in german more people know what "Open Source" FOSS/FLOSS/Free Software is quite uncommon.

**Comment by pljones** [comment]
Most people don't _care_ about the ambiguities.  But they want a familiar term not some geekspeak technojargon that will send them running.

The people who do care look at the licence.

**Comment by trebmuh** [comment]
> Most people don't care about the ambiguities. But they want a familiar term not some geekspeak technojargon that will send them running.

I couldn't disagree more.

I think it's never a good idea to assume that "most people don't care". Nobody can't speak on behalf of "most people".

Re: "technojargon", I don't believe at all that talking about freedom to users it talking about "technojargon". It's talking about freedom. I have been amazed numerous times how people can be interested in freedoms when you talk to them as equals and you don't make pre-established choices for them.

Let's call a cat a cat. Jamulus is a Free and Open Source Software = FOSS.

**Comment by gilgongo** [comment]
As far I as can tell, we only actually mention the Jamulus licence directly [twice](https://github.com/search?p=1&q=org%3Ajamulussoftware+open+source&type=Code): once on the website (on the home page) where we say "Jamulus is free and open source software licensed under the GPL" and once in the README.md where we just say "Jamulus is Open Source software". So we just need to change the README.md to be consistent with the home page, no? 

Or do you mean you want us to say "Jamulus is free and open source software (FOSS) licensed under the GPL" on both cases? 

In which case I've got no problem with that :-)

**Comment by gilgongo** [comment]
OK, all references to open source now say "free and open source software (FOSS) licensed under the GPL"
