### ISSUE TITLE
[en] Client-Troubleshooting.md page 

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#167]
While reviewing the French translation of this page, I stumbled across this link: `[software manual](https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md)` in this page.

Shouldn't that be updated to `[software manual](Software-Manual)` and the https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md page removed?

**Comment by ann0see** [comment]
I think so, we were a bit struggling what to do with this. Corrados was ok with removing it. But it would break a few links and Jamulus versions. I think you can at least modify it on changes @gilgongo ?

**Comment by trebmuh** [comment]
> [...] it would break a few links and Jamulus versions [...]

OK, I see. So instead of removing it, we should probably delete its content and replace it with a link to https://jamulus.io/wiki/Software-Manual . Thoughts?

**Comment by ann0see** [comment]
Yes. This would be probably the best option.

**Comment by gilgongo** [comment]
We need to at some point delete the original software manual page as it doesn't make sense to maintain a duplicate.

**Comment by ann0see** [comment]
Yes. But we should set a link since old versions of Jamulus and some websites still link there.

**Comment by trebmuh** [comment]
I was on my way to make the change in the Client-Troubleshooting.md page , and I saw that @gilgongo already did so in the https://github.com/jamulussoftware/jamuluswebsite/commit/a752c78cbb6d33429bb2152fdbd191ea5b92e34e commit. Hence I'm closing this thread.

(_see https://github.com/corrados/jamulus/issues/776 for the deletion of the **old** wiki_)
