### ISSUE TITLE
[en] consistency QT/Qt

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#194]
Qt should be written like that: **Qt** (not **QT**). See https://www.qt.io/product/framework .
I've seen a typo in wiki/en/en-Compiling.md and in its translations:

- wiki/es/es-Compiling.md
- wiki/de/de-Compiling.md
- wiki/fr/fr-Compiling.md

I've made the changes in those files on the "changes" branch but now, I wonder if that wouldn't have been better against "release".

**Comment by ann0see** [comment]
> I've made the changes in those files on the "changes" branch 

Depends. The initial reason for the changes branch (initially) was that translators have a clean diff once the translation period starts again. 

In my opinion, you should have only changed it in the english version and then change it in the other translations during translation period.

But I don't really think it's a problem.

**Comment by trebmuh** [comment]
OK, sorry about that then. I'll try to remember it for a next time and I hope it won't be a problem for the translators.

@ann0see : is that OK for you to close this issue?

**Comment by ann0see** [comment]
I don't think this is a problem. I can close it now.
