### ISSUE TITLE
New Installer: Explain what ASIO is

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#237]
The new installer is almost ready and linking to https://jamulus.io/wiki/Installation-for-Windows#setting-up-asio4all if no ASIO driver was found. We should explain ASIO on Windows for newbies. (Why they need it [only one sentence], and that ASIO4ALL is not recommended but probably needed. etc.)

Any proposals?
What I'd suggest:

1. Explain that you need an ASIO driver since the inbuilt drivers don't allow low latency audio
2. Tell the user that usually ASIO drivers are only provided for external sound cards (which we also recommend to use with Jamulus)
3. Tell the user that he can use ASIO4ALL which is a generic ASIO driver and the setup is described here (save for later); it should also be possible to download the .md file since sometimes the web browser also conflicts with ASIO4ALL

**Comment by gene96817** [comment]
My experience from helping new users is that explaining what is ASIO and ASIO4ALL doesn't help the non-technical user. They need to be told what needs to be done with all the user input that ASIO requires to operate properly.

**Comment by ann0see** [comment]
Have a look at #242. I think the page must at least briefly explain that you need something audio related (called ASIO) which isn't something you usually have on your PC.

**Comment by gene96817** [comment]
Sadly, it is not enough. It needs to be, "there are three places you need to review to configure your ASIO interface. First, go to X and ..., then go to Y and ...., finally at Z and..... Note that X and Y are related as they set up the left and right channels of your output.... ".    Something like that. I find the users need help understanding the meaning of the words in there options. 

We easily forget that our backgrounds help us interpret the meaning of those strings describing the options.

**Comment by ann0see** [comment]
Yes. That's right. Can you look at the PR I mentioned and make a proposal?
This issue is difficult.

**Comment by gene96817** [comment]
I don't have a windows machine. I do have more newbies to help. I'll take notes and bring it back. Give me a few days.

**Comment by ann0see** [comment]
Great! This might also be something you could tell @jamulussoftware/designers They might be interested in UX.

**Comment by mulyaj** [comment]
I would be interested in your notes @gene96817 - I agree that new users don't really understand ASIO. I think the most crucial part for newbies is to explain exactly how to set ASIO and not necessarily place too much emphasis on the technical side.

**Comment by Hk1020** [comment]
Just an unqualified comment of a Jamulus fan here. Asio4all is the greatest stumbling block on Windows. It has a really weird user interface, it reacts strangely if there are not working devices present and it doesn’t select the correct device quite frequently. The worst part is that it looks different everywhere because of different hardware. You can’t just tell people where to click you first have to inspect their hardware. I regularly end up with TeamViewer on people’s computers to get this fixed. And once you have to dive in to set 48khz people are completely lost. Not to mention that there is hardware which works fine with Windows or Zoom but doesn’t with asio4all. 

I‘d be thrilled if we could get rid of asio4all. I read on some of the Jamulus boards that with modern Windows this should be possible. It now comes with really low latency drivers but I forgot the details.

**Comment by pljones** [comment]
ASIO4ALL sits on top of standard Windows WDM low latency audio any way.  All it does is provide an ASIO API that translates to the WDM API.

Work is going on to add PortAudio support to Jamulus.  This will let Jamulus take advantage of any PortAudio-provided support for newer Windows low latency audio without ASIO4ALL being required.

It should provide a _better_ user experience but won't eliminate the issue with each user potentially having a different set up, of course.  I've yet to see how Jamulus+PortAudio presents the audio devices.

Also, hardware with a dedicated ASIO driver will still be best used with that driver, even with PortAudio -- PortAudio provides support for ASIO, along with other APIs.

**Comment by ann0see** [comment]
#309 is related.

**Comment by gilgongo** [comment]
Done with https://github.com/jamulussoftware/jamuluswebsite/pull/242
