### ISSUE TITLE
[Bug] footer outdated

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#255]
In the footer, we have "`Summer 2020! Tell us about Jamulus - take our anonymous survey!`".
It starts to be outdated (we're not in summer 2020 any more)  and we might want to change that to something more up-to-date.

**Comment by ann0see** [comment]
Yes. A few weeks ago we talked about this in the UI discussion. I suggested to add it to the onbording page. 
@mulyaj Can you still remember what exactly was the outcome of the discussion? I think @gilgongo wanted to redraft it?

**Comment by mulyaj** [comment]
I'm afraid I don't remember. As of now could it be moved to a more visible location?

**Comment by ann0see** [comment]
Yes. Maybe the onboarding page?

**Comment by trebmuh** [comment]
Questions:
- are people still able to answer the survey? in such a case, we could just rephrase the sentence
- what is the outcome of this survey? has any blog post or any kind of official summary/overview been written yet? is such a case, we could link to that (keeping a bit of a momentum there)

**Comment by ann0see** [comment]
> are people still able to answer the survey? in such a case, we could just rephrase the sentence


Yes, I think so. 

> what is the outcome of this survey?

Gilgongo knows about it. He hasn't been active in the last few weeks and I'm a bit worried about him. Hopefully he just has too much to do at the moment.

**Comment by trebmuh** [comment]
@gilgongo can you please update us on that?

If people are still able to answer the survey, and if that's still useful for Jamulus, I'd recommand to leave the link to the survey in the footer and only rephrase the sentence a bit. Reading "`Summer 2020! Tell us about Jamulus - take our anonymous survey!`" makes it feel like "`oh, that's outdated, no needs for me to answer`". If we just put "`Tell us about Jamulus - take our anonymous survey!`" it's good enough to keep attracting people I'd say.

**Comment by gilgongo** [comment]
Hi - sorry for being absent recently but I've been busy with a big bunch of work in the new year. 

I've been meaning to replace the survey with a new one. The first 100 responses to the current one are [summarised here](https://docs.google.com/document/d/11fSDoSfp5w40VixXabujyzarV-wDYIapftyF-Dhc6I8/edit) as of a few months ago, but I'll see if I can update that as we've now had 264.

The results are reasonably interesting, but I think we could probably ask some more useful questions now (particularly as we have the new website and better docs). Once I've done the update we can perhaps discuss.

**Comment by ann0see** [comment]
Thanks for commenting it's good to know you're allright. 

If you have too much to do at the moment, I think the @jamulussoftware/designers team could look at the questions and results and discuss them here. 

Tagging @corrados too since he might also want to add some questions to the survey.

**Comment by gilgongo** [comment]
Thanks - I'll snapshot that doc and update it with the latest figures but they're not that different it seems.

**Comment by corrados** [comment]
I leave it up to you.

**Comment by trebmuh** [comment]
Let's update the sentence to "`Tell us about Jamulus - take our anonymous survey!`" for the time being.
That fixes the "_we're not in summer 2020 any more_" issue and we'll be able to discuss about other things later.

@ann0see: please merge #260

**Comment by trebmuh** [comment]
done

**Comment by gilgongo** [comment]
I've [updated the summary](https://docs.google.com/document/d/11fSDoSfp5w40VixXabujyzarV-wDYIapftyF-Dhc6I8). 

A few possibly interesting comparisons between the first 100 respondents (when the first version was compiled) and the next 165 but nothing major.

I'll see if I can start a discussion about questions for another survey on the  jamulussoftware/designers team.

BTW not that it's relevant to this ticket, but in re-compiling the summary, I noticed we are starting to see **very small glimmers** of people finding us on Google searches for “jam online” since November (44 clicks, 1,503 impressions, av. position 9.79), “music jam online” (15, 157, 6.31) with a CTR for these of about 3-10%. Some other phrases too (although ranking for those is as yet tiny). So we're doing something right, and the SF download chart _may_ be reflecting that but it's hard to say.
