### ISSUE TITLE
[Bug] Running-Jamulus-with-Multiple-Audio-Interfaces page

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#256]
https://jamulus.io/wiki/Running-Jamulus-with-Multiple-Audio-Interfaces#linux

The link "`Follow `**this tutorial**` to route the desired interface into Jack by using alsa_in.`" isn't linking to a relevant page any more. We can replace it with a link from archive.org : https://web.archive.org/web/20201112033306/https://www.penguinproducer.com/Blog/2011/11/using-multiple-devices-with-jack/ or we can find another tutorial.

I'd go with the archive.org link.
Thoughts?

**Comment by ann0see** [comment]
I think, this page will be in the community section. You should add it there.

**Comment by trebmuh** [comment]
@ann0see (just checking) you mean [this one here](https://github.com/jamulussoftware/jamuluswebsite/blob/changes/_posts/2020-11-24-Multiple-Audio-Interfaces.md) ?

**Comment by ann0see** [comment]
Yes. This should be it. You can just edit it there.

**Comment by trebmuh** [comment]
Thank you. Done: https://github.com/jamulussoftware/jamuluswebsite/commit/1b9f8db5597097726991d9ecafb35dc6fc3f5fc5

(_closing here now_)
