### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by AndyMcProducer** [jamulussoftware/jamulussoftware.github.io#262]
What should the overall ms be local?

Someone said to me they had 8ms a while ago but even at 32buffers I still have 16ms.

**Comment by ann0see** [comment]
I think 16ms locally isn't that bad. If the overall delay keeps green almost all the time, you should be ok.

**Comment by AndyMcProducer** [comment]
Someone else told me they get 8ms and that difference would make a big difference on the servers I connect to.

**Comment by ann0see** [comment]
Of course, latency should be as low as possible. 

My Ping-Time is 12ms (so not connected to localhost) and overall delay 33ms with small network buffers and 2.67ms buffer size, network buffers set to auto. 
I use a Behringer UPhoria UMC 202HD interface and these numbers come from Windows 10 + native Behringer driver.

If I'm on Debian 10, the latency on my end with these settings is really good. (That's just my subjective feeling)

What are your OS settings? Do you use ethernet?

At least from my reading Linux provides better latency than Windows. 

Ok. Just connected to my local Jamulus server on Windows I could push it to 17ms...

**Comment by ann0see** [comment]
Can we close this issue since it seems to me that the discussion is taking place here: https://github.com/corrados/jamulus/issues/877
