### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by AndyMcProducer** [jamulussoftware/jamulussoftware.github.io#263]
To show pings of users in connect window.

Is this possible with out too much overhead?

**Comment by ann0see** [comment]
Sorry to be the guy, but I think you opened this issue on a wrong repo (this is just about the documentation, not the Jamulus program). You should open an issue here: https://github.com/corrados/jamulus/issues which will get much more attention.

**Comment by AndyMcProducer** [comment]
Thanks I put it on the link you said.

**Comment by ann0see** [comment]
Great!

**Comment by ann0see** [comment]
Can you also post this issue there? I think you only posted #262
