### ISSUE TITLE
[Bug] Compiling instruction not online

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulussoftware.github.io#267]
**URL**
https://jamulus.io/wiki/Compiling

**Describe the bug**
The webiste says: get and copy the ASIOSDK development files in [\path\to\jamulus\source]\windows directory so that, e.g., the directory [\path\to\jamulus\source]\ASIOSDK2\common exists

the code says: "and copy the contents into `[\path\to\jamulus\source]\windows\ASIOSDK2` so that, e.g., the folder `[\path\to\jamulus\source]\windows\ASIOSDK2\common` exists"

Note the missing "windows":
 [\path\to\jamulus\source]\ASIOSDK2\common
`[\path\to\jamulus\source]\windows\ASIOSDK2\common

When will this fix go live?

**Comment by ann0see** [comment]
> When will this fix go live?

Once we start the translation process which starts roughly one week before the next version of Jamulus is getting released.

**Comment by nefarius2001** [comment]
Hm.
Pity that there is no faster lane for fixing mistakes, but that’s how it is, then.
Not too critical anyway
