### ISSUE TITLE
Link to be changed in Installation-for-Linux

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#271]
In https://jamulus.io/wiki/Installation-for-Linux , we've got a link to https://github.com/corrados/jamulus/issues/223 but that issue has been converted to [a discussion ](https://github.com/corrados/jamulus/discussions/914#discussioncomment-318905). I'm not changing it right with a PR since the repo will likely move from https://github.com/corrados/jamulus to https://github.com/jamulussoftware/jamulus soonish. Hence, this issue is reminder for later.

**Comment by ann0see** [comment]
Yes. You're right. It should be changed. Furthermore, I think we should start a release process of the documentation soon with all the link changes/... @gilgongo what do you think?

**Comment by gilgongo** [comment]
Yes I was wondering about that.

**Comment by pljones** [comment]
See also https://github.com/jamulussoftware/jamulus/issues/908#issuecomment-770063290

**Comment by ann0see** [comment]
I've just pushed a big commit: https://github.com/jamulussoftware/jamuluswebsite/commit/e722462504c55d1c08a7211d549081ee3cd7aa0d

I hope, I found all the links here. Android is not changed because of #308

**Comment by gilgongo** [comment]
@ann0see Is this done? Close?

**Comment by ann0see** [comment]
I think so.
