### ISSUE TITLE
Change body text colour - black to dark grey (Light Mode)

### ISSUE THREAD

**Issue by mulyaj** [jamulussoftware/jamulussoftware.github.io#284]
Black text against a white background can cause eye strain for readers. It is also particularly difficult for readers with dyslexia and contrast sensitivity (text will look like it's moving).

A colour I propose is Hex 333 or Hex 222.

**Comment by trebmuh** [comment]
The website isn't "`Black text against a white background`" here:

![jamulus](https://user-images.githubusercontent.com/8705846/107128158-afa60c00-68bb-11eb-88d8-58699dc794c5.png)

Do you have something different?

**Comment by mulyaj** [comment]
That's the dark mode version. Here it is on light mode.

![image](https://user-images.githubusercontent.com/63881221/107128750-52479600-688e-11eb-8487-bb688c42a2cd.png)

**Comment by trebmuh** [comment]
Strange, I can't remember to have selected the dark mode.

**Comment by mulyaj** [comment]
That might be your default if you have dark mode enabled on your desktop settings

**Comment by trebmuh** [comment]
Can't remember to have selected a desktop dark mode either.

**Comment by mulyaj** [comment]
@ann0see @gilgongo Are there any objections to this?

**Comment by gilgongo** [comment]
Go for it, I say :-)

**Comment by ann0see** [comment]
Yeah, just open a PR

**Comment by mulyaj** [comment]
I made a commit on changes: f86f6190bf627126cd64b6ca8e26bc403ce77071

Should I open a PR first next time?

**Comment by ann0see** [comment]
That's no problem ;-). I'll close this then.
