### ISSUE TITLE
[Feature] Flatpak installation guide

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#287]
**Is your feature request related to a problem? Please describe.**
Installation on Linux involves/involved compilation which might not be easy. Now there are multiple ways to install Jamulus on Linux, one if via Flathub: https://github.com/jamulussoftware/jamulus/issues/803 
**Describe the solution you'd like**

Maybe: an installation guide for Jamulus via Flatpak from Flathub?

**Comment by ann0see** [comment]
Link: https://github.com/flathub/io.jamulus.Jamulus

@joao-p-marques do you want to link the repo or the installation guide of the flatpak in the Jamulus documentation?

The best thing would surely be an installation guide in the upcoming community section.

**Comment by joao-p-marques** [comment]
@ann0see yes, it would be nice, I've added some quick documentation in the README of the flathub repo, so it could be a good resource to link in the Jamulus documentation. However, it could use some polishing and improvement. 
The main point of difficulty would be setting up pipewire, so it would be nice if someone could test in on other distros and provide feedback and possible improvements to the docs.

**Comment by ann0see** [comment]
I only have a Debian PC and am happy to test a guide.

**Comment by joao-p-marques** [comment]
That would be nice @ann0see Thanks!
As I said, the main "friction" point should be setting up pipewire, and I don't know what would be the correct process for your OS. If you could test it and provide some feedback it would be great!

**Comment by ann0see** [comment]
I installed the flatpak but I‘m still struggling with pipewire (as you told me). I hope I get this sorted out.

**Comment by joao-p-marques** [comment]
https://bryanquigley.com/posts/mindshare/pipewire-it-plays.html seems to be a good guide for installing `pipewire` on Debian. Jus remember that the one needed to work with Jamulus is the `pipewire-libjack` package, not the `pipewire-pulseaudio` (currently they are separated and conflicting for some reason). Also, it is possible that you need to uninstall JACK and a few dependencies of the machine before being able to install `pipewire` (also due to conflicting dependencies)

**Comment by gilgongo** [comment]
This wold be better as a Knowledge Base page. Feel free to open a PR on that.
