### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DominikSchaller** [jamulussoftware/jamulussoftware.github.io#293]
**Describe the bug**
The link to Simon's guide on this page is broken: https://jamulus.io/wiki/Running-a-Server

**Comment by ann0see** [comment]
Do you know if there's a new link?

**Comment by DominikSchaller** [comment]
https://m.facebook.com/notes/jamulus-worldjam/howto-idiots-guide-to-installing-or-upgrading-a-jamulus-server-on-amazon-aws-lig/818091045662521/

**Comment by DominikSchaller** [comment]
This is the link from my mobile, best use the one from a desktop PC (without the leading m.)

**Comment by ann0see** [comment]
So you mean https://www.facebook.com/notes/jamulus-worldjam/howto-idiots-guide-to-installing-or-upgrading-a-jamulus-server-on-amazon-aws-lig/818091045662521/ ?

**Comment by DominikSchaller** [comment]
Yes, that link works for me. I also tried it in anonymous browser mode (to
make sure it works when I'm not logged into facebook).

**Comment by ann0see** [comment]
Great. Solved via 7ad86608db7259fd24e4a057c5de5991d9c038de

The fix will be up once the translation process starts.
