### ISSUE TITLE
ASIO4ALL helping hand / tip

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#309]
We suggest people install ASIO4ALL if they do not have a dedicated ASIO driver for their hardware.  The people in this position are more likely to need assistance setting up so it might be a good point to also say something like "If you're installing ASIO4ALL and haven't used it before - go read ***this***" and link to something that will explain what's going on.

**Comment by gene96817** [comment]
> install ASIO4ALL if they do not have a dedicated ASIO driver for their hardware

I have not heard anyone say "if they do not have a dedicated ASIO driver for their hardware". this bit has been lost to many (almost all) users. Do we believe Jamulus almost always works with the dedicated ASIO driver from the PC manufacturers?  It does change things if I told new users, "if your computer already has an ASIO driver, just install Jamulus."

**Comment by pljones** [comment]
"Professional audio" hardware will have a suitable ASIO driver for Windows.  Realtek provide an ASIO driver but I've heard bad things about it - the ASIO4ALL site terms such things "consumer grade drivers".  So it's not just whether it's a "dedicated driver", it's whether it's "dedicated" hardware, rather than consumer grade.  "Hi-fi" is not professional audio - it's still consumer grade, just expensive.

I've needed ASIO4ALL myself - my audio hardware is now so old the ASIO driver isn't as Windows 10 compliant (it's "no longer supported" as of Win 8.1) as one of my audio applications would like - ASIO4ALL over the WDM driver lets me run it (but it's not really usable in realtime).

**Comment by gene96817** [comment]
Watching PCs and drivers over 40 years, here is my working stereotype:
1- built-in drivers can be pretty bad. If the chipset vendor has a driver, it is usually helpful to install the chip vendor's driver. The PC manufacturer often breaks the chipset vendor's driver when they customize the driver.
2- the chip vendors do fix driver problems with new releases but the PC manufacturer does not have a process to update defective drivers (it adds cost to their operations). If you are working with their support, you might find out there is a new driver that fixes a problem. For the most part, the PC manufacturer relies on their Windows certification as proof of quality.
3- external add-on specialty devices typically come with useful drivers (your premium professional audio hardware fits here)
4- commodity add-on devices often have pretty bad drivers (frivolous toy Bluetooth widgets fit here)

**Comment by gilgongo** [comment]
This seems to be a dupe now of #237. Closing.
