### ISSUE TITLE
Document the list of maintainers

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#318]
I think it would be nice to see who is in charge for the Jamulus project (i.e. who can merge PRs, etc.).

Places where I would look for such a list:

- A `MAINTAINERS.md` file in the main repository
- https://github.com/orgs/jamulussoftware/people (which looks empty to me: *This organization has no public members.*)

**Comment by hoffie** [comment]
I can move this forward if we have consensus if/what should be done.

I have looked at the Github jamulussoftware's People tab. If we wanted to have that list populated, it seems like every organization member would have to mark their membership as public when going to https://github.com/orgs/jamulussoftware/people, clicking on their own name and choosing Membership: Public. I would be in favor of doing this, but this only makes sense if everyone agrees.

I'm would only add a `MAINTAINERS.md` file if we are to add additional information there (i.e. full names if wanted, focus area, etc.). If we don't need this right now, it would just be a maintainance burden, so I'd skip this for now.

@ann0see @pljones @softins @gilgongo So, would you agree with
- Setting your own membership to Public and
- Not adding a `MAINTAINERS.md` file right now?

**Comment by ann0see** [comment]
Yes. That would be ok.

**Comment by gilgongo** [comment]
@hoffie Is this a duplicate? https://github.com/jamulussoftware/jamuluswebsite/issues/355

**Comment by hoffie** [comment]
> @hoffie Is this a duplicate? #355

More or less. The decision we reached here was about publishing organization membership. Some have done that, I think @softins hasn't yet. I'd say we can close this ticket as it is superseded by #355 which is more generic and structured, yet more actionable. Feel free to close if you agree.

**Comment by softins** [comment]
Sorry, I missed that. I'll do it now.

**Comment by gilgongo** [comment]
OK cool - lets look at #355 instead.
