### ISSUE TITLE
Process for reporting security issues

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#319]
Many open source projects want security researchers to report potential vulnerabilities responsibly in private instead of creating public issues on Github. This allows for some time to develop a fix before making all details public. Has this topic come up with Jamulus so far? The closest I have seen is jamulussoftware/jamulus#314.

If some decision is made how to handle this, it would be cool to have this documented in a [`SECURITY.md`](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) file.

Are there any plans for Jamulus in this regard?

I'm asking because I was about to open an issue which one could classify as a (low-severity) security-related issue. Should I just open it? Should I sent it to you, @corrados, in some other way (my mail address is in my Github profile, if you want)?

I also have some further thoughts regarding jamulussoftware/jamulus#314 / protocol-level stuff and I'm unsure whether I should add them to the public ticket already.

---

1. **Set up a security@jamulus.io address which forwards to the main developers' private addresses.** Additionally generate a GPG key with access to the private key for all main developers.
    - I think this is a common way to implement this.
    - As far as I can see, no mail infrastructure is currently in place for jamulus.io, so this would have to be added. @gilgongo You currently run all DNS-related things for jamulus.io, as far as I understood. Would it possible for you to handle mail as well? If not, I'd also volunteer to have MX records point to a server of mine which could implement this redirect. If possible, I think I would prefer to have all the infrastructure stuff handled in a single place on @gilgongo's infrastructure.

2. **Use Github issues and request such reports to be posted in GPG-encrypted form.**
    - We would need a shared GPG key for the main developers as well. 
    - I don't think I've ever seen that in the wild, so that may be uncommon.
    - It would have the benefit of making the process transparent and we could easily publish the unencrypted issue content when we feel ready.
    - It would also avoid the mail setup requirement.
    - We could optionally make this n security-specific issue template which points to SECURITY.md for details.

**Comment by hoffie** [comment]
So, I'd like to move this forward. I understand that there is consesus that we do want to provide a way for responsibly disclosing security issues. I can come up with the following options:

1. **Set up a security@jamulus.io address which forwards to the main developers' private addresses.** Additionally generate a GPG key with access to the private key for all main developers.
    - I think this is a common way to implement this.
    - As far as I can see, no mail infrastructure is currently in place for jamulus.io, so this would have to be added. @gilgongo You currently run all DNS-related things for jamulus.io, as far as I understood. Would it possible for you to handle mail as well? If not, I'd also volunteer to have MX records point to a server of mine which could implement this redirect. If possible, I think I would prefer to have all the infrastructure stuff handled in a single place on @gilgongo's infrastructure.

2. **Use Github issues and request such reports to be posted in GPG-encrypted form.**
    - We would need a shared GPG key for the main developers as well. 
    - I don't think I've ever seen that in the wild, so that may be uncommon.
    - It would have the benefit of making the process transparent and we could easily publish the unencrypted issue content when we feel ready.
    - It would also avoid the mail setup requirement.
    - We could optionally make this n security-specific issue template which points to SECURITY.md for details.

@jamulussoftware/maindevelopers What do you think?

**Comment by ann0see** [comment]
I'd go for the rather unusual way with issues. But this would mean we'd need to share a private key probably?

**Comment by hoffie** [comment]
> But this would mean we'd need to share a private key probably?

Yes. I have clarified that in my comment above. I also added that we could add a new issue template for that to make this more accessible.

**Comment by gilgongo** [comment]
I can set up email forwarding if needed. Even if we don't use if for this it might be useful for other things in the future perhaps.

**Comment by ann0see** [comment]
I think we should close this. There's already a discussion on the main repo with roughly the same topic: https://github.com/jamulussoftware/jamulus/discussions/916 and we could continue discussion there.

**Comment by gilgongo** [comment]
@hoffie  This is a bit meta, but can we test the idea here of you taking what you wrote https://github.com/jamulussoftware/jamuluswebsite/issues/319#issuecomment-782936296 and replacing the main "ticket" (that is https://github.com/jamulussoftware/jamuluswebsite/issues/319#issue-811891513) with that text? 

This so that we have an Issue that has been resolved with an action without people (er, like me) having to read the entire thread to work out what's going on?

Personally, I think we should do this for tickets that we haven't ourselves opened, but I know that's controversial... 

BTW if you think people haven't fed back enough yet, then that's OK but ping them on DC if necessary and give them a time limit by which to respond. What you propose seems good to me.

**Comment by hoffie** [comment]
> This is a bit meta, but can we test the idea here of you taking what you wrote #319 (comment) and replacing the main "ticket" (that is #319 (comment)) with that text?

Yes, I added the text to the issue description. I do not feel good with replacing the initial text as it would make the first replies look odd.

Now that mail infrastructure seems to be in the process of being set up, I think we should go with the more common option (email) and will move on with that.

**Comment by gene96817** [comment]
> Use Github issues and request such reports to be posted in GPG-encrypted form.
We would need a shared GPG key for the main developers as well.

I don't know if I interpreted this correctly. It would be a bad idea for more than one user to have the secret part of a GPG key. If one user is compromised, then the whole system is compromised. I think the repository should have a GPG key. All messages would go from repository to developer. If there are N developers, that means there are N versions of the message all sent with each developer's GPG public key.  This shouldn't be a big issue. If one developer is compromised, that developer's key would be revoked and it doesn't affect anyone else.

**Comment by gilgongo** [comment]
@gene96817 I assume we're saying `gpg --encrypt --recipient alice@example.com --recipient bob@example.com doc.txt` 

Although that does assume the sender knows the list of which keys to use. Maybe there is such a thing as a "wrapper" key? Dunno.

**Comment by gene96817** [comment]
I have used GPG for years. Each user has a key pair registered to their email address. The (my) mail client knows to apply the recipient's public key to encrypt the mail. If I send mail to a list, each recipient receives mail encrypted with their public key. It is really no additional work on my part. In this scheme, if you reply to my email, I will receive your reply encrypted with my public key. My mail reader applies my private key to read the email.

20+ years ago, encrypted email was very inconvenient. Now Outlook and Apple Mail makes it very easy. When I send email, if my correspondent has a key, the mail is encrypted. If the correspondent doesn't have a key, then the mail is sent in plaintext with a signature.  The signature is proof I am the sender (without encryption).

**Comment by hoffie** [comment]
> I think the repository should have a GPG key. All messages would go from repository to developer.

I'm not sure if I understand. What do you mean by "the repository should have a GPG key"?
If I interpret this as: For the [option 1](https://github.com/jamulussoftware/jamuluswebsite/issues/319#issuecomment-782936296), which I plan to move forward with, this would mean having some infrastructure which takes messages encrypted for the published public key, decrypt them (thus needs the private key), and re-encrypt them to the team members. I'm not seeing a benefit here, as this requires infrastructure to be managed and the key would still have to be rotated if a team member leaves, for example.

If you mean that we should not publish a single mail address, but rather a list of developers plus their GPG keys, then I see that this could work. [Apache](http://www.apache.org/security/) does it like that. Personally, I'd prefer to have a single address and don't have a problem with a shared private key. We would need to rotate that when someone leaves (and publish the new key). [Apple](https://support.apple.com/en-us/HT201214) chooses the single-key approach I've outlined above. [Linux kernel](https://www.kernel.org/doc/html/v4.11/admin-guide/security-bugs.html) does not mention GPG at all.

**Comment by gene96817** [comment]
@hoffie   I apologize for my loose language. 
1- sharing a private key should not be used. Every developer should have their own public/private key pair.
2- publishing a single mail address is helpful. That mail address should have its own public/private key pair.
     this implies mail sent to this address will be redistributed to developers using each developer's key.
3- If a developer leaves, there is no impact to the key list. the developer is simply deleted from the distribution l
4- #2 above implies part of the discussion about "option 1". The point is that each entity/person has its own private key. In this way, you maintain the benefits of privacy and non-repudiation.

**Comment by gene96817** [comment]
@hoffie  I have reread your message.

I agree with your first paragraph, except that, no keys needed to be changed if a team member leaves.

Publishing a list of developers (e.g. Apache) has the disadvantage that there is no single log of all mail sent about a topic. 

> Personally, I'd prefer to have a single address and don't have a problem with a shared private key.

I agree.

> We would need to rotate that when someone leaves (and publish the new key).

Technically you don't need to do this when a developer leaves. BUT, you do need to do this if a person who manages the "single" address with access to the secret key leaves. 

With the exception of some imprecise language, I believe we are in agreement.
