### ISSUE TITLE
Describe usage for --streamto

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#323]
Need to add this to Configuration page. Allows streaming of audio output to a service like icecast or other output supported by ffmpeg.

`--streamto "[outfile options] outfile"`

Also, I propose we write up something in Tips & Tricks with more info on it as per https://github.com/jamulussoftware/jamulus/pull/967#issuecomment-782191210

**Comment by hoffie** [comment]
I think this was created related to the Streamer2 PR which [has been closed](https://github.com/jamulussoftware/jamulus/pull/967#issuecomment-1003752345). Therefore closing this as well.
