### ISSUE TITLE
Change references to "Central Server"

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#330]
The term "central server" isn't really descriptive of what it is any more, and has always been a bit confusing in discussions of servers. There is persistent (if vague and unsubstantiated) evidence that newcomers to Jamulus assume that running a server in some form is required for any use. Distancing the terminology ("directory" vs "central server") may help with that, and helps to make the word "server" mean what is currently sometimes called a "normal server" in conversations about the two types (particularly when this involves non-technical people being instructed to connect to a "custom central server").

So we'll replace it with the term "Directory Server" (as the formal name), and in most cases just "Directory" so as to disambiguate between "normal" servers. Eg:

"Configuring your server as a Central Server ..." should be "Configuring your server as a Directory" 

"You need to enter a custom central server address" should be "You need to enter a custom directory address" 

Also need to change this in the diagram (and update the logo there)

**Comment by dcorson-ticino-com** [comment]
Excellent move !

**Comment by pljones** [comment]
Ah good, I thought we had this.  I wanted to mention some thoughts...

Tagging @gegeweb as an interested party.

### Definition of terms

#### Directory server
A _role_ performed by some servers.  Directory servers do not _register_ with another server but support clients connecting for jams.  However, their distinguishing feature is that other servers may _register_ with them and clients may retrieve a _directory list_ of servers from them.

#### Public Directory server
One of the "built in" _directory servers_ in the Jamulus client and server.

#### Custom Directory server
A _directory server_ added by the Jamulus client or server user.

++ note: "Private Directory server" would then be the proposed server only list of built in "private" directory servers.

++ note: "Public" and "Private" may not be the finalised choices...  Same applies below.

++ note: I'd also like "Edit custom servers..." at the bottom of the "List" drop down when selecting a directory server and for all the known custom servers to be listed (below a line - so: top part "official", second part "custom", third part "edit")

#### Register, registered server
A registered server is one that has registered with a directory server.  Essentially, the "register" is a list of servers maintained by a _directory server_.

#### Public server
A public server is a _registered server_ that has _registered_ with one of the _Public Directory servers_.  To remove any possibly confusion: these are _all_ intended for use by _any_ Jamulus client user.

#### Private server
A server that is not intended for use by every Jamulus client user.  These may be _registered_ or not (but should not be registered to the _Public Directory servers_).

#### Server list
When a client wishes to connect, it may consult a _directory server_ to request that server's list of _registered servers_.  This is the _server list_ displayed for connection.  Each list is separate.

**Comment by gilgongo** [comment]
I've not got any opinion either way since I'm not in the code, but are things like `<widget class="QLabel" name="lblCentralServerAddress">` and `SRS_CENTRAL_SVR_FULL` going to change as part of this ticket or are we just talking about the docs here?

**Comment by gene96817** [comment]
@pljones   Thank you for the definitions. I had trouble understanding a few details.

> One of the "built in" directory servers in the Jamulus client and server.

I think you mean the list of public directory servers and their locations are provided in the Jamulus client and server.

> Custom Directory server
A directory server added by the Jamulus client or server user.

I think  part of this is "information about custom directory servers must be added by the user to the Jamulus client or server"

> ++ note: "Private Directory server" would then be the proposed server-only list of built-in "private" directory servers.

I find this confusing. I was expecting that a custom directory server is a private directory server created for <example of private use.>.

> Private server
A server that is not intended for use by every Jamulus client user. These may be registered or not (but should not be registered to the Public Directory servers).

To my understanding, I suggest:
"A server that is not intended for use by the public (i.e. general Jamuilus community). A private server should not be registered to the Public Directory servers. they may be registered with a Private Directory server.

**Comment by pljones** [comment]
> I think you mean the list of public directory servers and their locations are provided in the Jamulus client and server.

"built in" - the ones in the source code - but only the Public ones.  We _may_ add Private ones to the server.  So not equally client and server.  So I was a little vague :).

> I think part of this is "information about custom directory servers must be added by the user to the Jamulus client or server"

Yes, I just phrased it as a definition, rather than an instruction.

> I find this confusing ...

As above - I've suggested having the server have a built in list of one or two "Private Directory servers" - not custom ones (and not exactly "private servers", either).  This is to make it easier for people using the server GUI to set up a "private" server when they need directory ping-back to make it work.  I think that's why there are so many empty "public" servers, so doing this should keep @gilgongo happy :).

> To my understanding, I suggest: ...

Sounds pretty much the same to me, yes.  I'd not use a phrase like "Jamulus community", however.  It sounds like something organised -- which isn't real.

**Comment by gene96817** [comment]
It is interesting that "community" to me is a collection of individuals with similar interests but not organized. If it is organized, then it would have an organization name. ...  It would be good to have an agreed way to refer to all the Jamulus users (ad hoc) and the mostly invisible users clustered around private servers.

**Comment by pljones** [comment]
"User base" would be a commonly used expression, I suppose.
