### ISSUE TITLE
Update and link user survey on onboarding page

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#331]
The user survey could do with updating and linking from the onboarding to make it a bit more visible.

**Comment by Akhilesh1204** [comment]
Can I work on this  issues. I ensure you  that i will do my best to solve this Issues

**Comment by gilgongo** [comment]
Hi @Akhilesh1204 thanks for offering. The main part of the work will be agreeing which questions we want to ask this time around (and which we want to keep), and how to word them. Do you have experience with questionnaire design?

**Comment by Akhilesh1204** [comment]
Not very much but I have little knowledge of Questionnaire design.

**Comment by Akhilesh1204** [comment]
Yes! I have quite  a good Knowledge of Questionnaire design.

**Comment by gilgongo** [comment]
OK good. Have a look at the current one and do a cut of a new one an we can maybe get a discussion going on the questions.

I was thinking this time (assuming we can branch the questionnaire in some way - I was thinking of using crowdsignal.com this time which does) that we'd try to structure it per "demographic", so maybe by skill level and/or the use cases: jamming, rehearsing (ie private), server operation maybe. This is so that we might get a better idea of the different types of issues that those use cases face. Right now it's just all at one level, as it were.

**Comment by Akhilesh1204** [comment]
Ok Fine will do.

**Comment by ann0see** [comment]
@Akhilesh1204 any updates here?

**Comment by ann0see** [comment]
@Akhilesh1204 any updates here?

**Comment by ann0see** [comment]
@gilgongo what can we do to move this forward?

**Comment by ann0see** [comment]
I'll close this and suggest to open a discussion if we want to set up a new survey.
