### ISSUE TITLE
Standardising Style and Tone

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#339]
Use/copy a guide that we like and refer to that in order to resolve questions when writing documentation. Add our own bits and pieces along the way (eg BE spelling/grammar, how to refer to "open source", and whatever)

**Comment by mulyaj** [comment]
Here's a [draft I've made](https://docs.google.com/document/d/12-QJXRskXhiJ9F5HCl216h53OtGkXhReMnm2wrbtQpk/edit?usp=sharing). Let me know your thoughts!

**Comment by gilgongo** [comment]
Thinking about where to put this on the site, if we create wiki/en/en-Style-Guide.md and link to it [from here](https://github.com/jamulussoftware/jamuluswebsite/blob/changes/README.md) that would work I think?

**Comment by hoffie** [comment]
Could we add an additional word of context? `wiki/en/en-Language-Style-Guide.md`? `wiki/en/en-Doc-Style-Guide.md`?
I'm asking because there is also the topic of Code Style Guide (although I'm not saying that there will be such a document for that shortly).

**Comment by mulyaj** [comment]
We could probably add a link to it from ``Contribution.md``.

**Comment by ann0see** [comment]
Just found the Google Doc again. https://docs.google.com/document/d/12-QJXRskXhiJ9F5HCl216h53OtGkXhReMnm2wrbtQpk/edit

Will link it on my PR.

**Comment by ann0see** [comment]
Closing since we now have a style guide on the website: https://jamulus.io/contribute/Style-and-Tone
