### ISSUE TITLE
Breadcrumb missing on installation on android page

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#344]
While going through the wiki page, I saw that the Installation for Android page doesn't have a breadcrumb. Not sure if we can add this during the translation process?

**Comment by gilgongo** [comment]
What's the preferred way of doing something like this? Can we add it to main now that translations have been done?

**Comment by ann0see** [comment]
Not sure. I'd add it to release after the new version is out (every translated page if possible)

**Comment by ann0see** [comment]
Ok. Anybody who wants can add them in the release branch for every language.
