### ISSUE TITLE
Remove reference to SourceForge on footer

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#345]
Currently the [footer](https://github.com/jamulussoftware/jamuluswebsite/blob/5271c43ee108818634e7071b48098d04180a633f/_includes/footer.html#L14) links to SourceForge. Shouldn't we link the GitHub discussions forum there?

**Comment by josecollado** [comment]
Which GitHub discussions?

**Comment by ann0see** [comment]
Hi @josecollado 

it‘s this link: https://github.com/jamulussoftware/jamulus/discussions

I‘d say that also another icon (maybe a speech bubble or question mark should  be displayed. An icon from FontAwesome would be great.

**Comment by ann0see** [comment]
Do you want to do it or should I? This will probably have to wait until the next release is out.

**Comment by josecollado** [comment]
Hi @ann0see You can assign it to me, i could send a PR by tomorrow if that works. 

Also, would one of these work? 
** only the first two i can choose without paying ** 
<img width="1059" alt="Screen Shot 2021-03-16 at 7 22 23 PM" src="https://user-images.githubusercontent.com/37092658/111392464-035efe80-868d-11eb-993f-24d4fe7b95e6.png">

**Comment by ann0see** [comment]
If you have to pay, I wouldn't choose any of them. Can you find some here: https://icongr.am/fontawesome ?

**Comment by josecollado** [comment]
Sent a PR for the changes

**Comment by ann0see** [comment]
Great! Thank you.
