### ISSUE TITLE
[Bug] Link to new homepage broken

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#35]
**URL**
http://llcon.sourceforge.net/index.html
wrongly redirects to

**Describe the bug**
If you click the link on the facebook group (https://www.facebook.com/groups/619274602254947/) you get an error and not redirected to jamulus.io. The easiest fix is to change it to https://jamulus.io Who is the admin of this group? I do not have a facebook account.

Nevertheless the issue is broader. Gilgongo already experienced the redirection issue after we uploaded the htaccess file. 

I'm unsure but we could also redirect permanent the index.html file. Would that fix the issue?

**Comment by gilgongo** [comment]
Just tried adding this to .htaccess:

`Redirect permanent /index.html https://jamulus.io/index.html`

But it still doesn't work.

**Comment by ann0see** [comment]
For me it works now.
