### ISSUE TITLE
Wrong link on the contributing page to website discussions

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#350]
**URL**
https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_7_0/wiki/en/en-Contribution.md#jamulus-website

We should link this to the main discussion forum.

**Comment by 96RadhikaJadhav** [comment]
@ann0see  Can I work on it?

**Comment by ann0see** [comment]
Yes sure, you can open a PR to the translate3_7_0 branch which fixes this for all pages in all languages! The files are in /wiki/[languagecode]/ as far as I know.

Thank you very much!

**Comment by ann0see** [comment]
German should already be ok.
