### ISSUE TITLE
Create dedicated "Team" page

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#355]
As per this discussion, viewing team members on GH may be problematic if you don't have a login, and doesn't give us freedom on how we format or describe ourselves. 

If we have a page on the website we can maintain names, bios etc, as we want.

_Originally posted by @trebmuh in https://github.com/jamulussoftware/jamulus/pull/1223#r592191314_

**Comment by ann0see** [comment]
Closing since we have our names set officialy in the jamulussoftware organisation.
