### ISSUE TITLE
Add Download links for 3.7.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#359]
`Download now for [Windows](https://github.com/jamulussoftware/jamulus/releases/download/r3_7_0/jamulus_3.7.0_win.exe), [Mac](https://github.com/jamulussoftware/jamulus/releases/download/r3_7_0/jamulus_3.7.0_mac.dmg), [Debian/Ubuntu](https://github.com/jamulussoftware/jamulus/releases/download/r3_7_0/jamulus_3.7.0_ubuntu_amd64.deb) or [other platforms](https://github.com/jamulussoftware/jamulus/releases/tag/r3_7_0)`

- [ ] Update front page `mHTMLDownloadNow` in `*index*.html`
- [x] Decide if/how we can do that without going to a translation process again (Keep "other platforms" untranslated? ~Use a dictionary?~) -> Use English
- [ ] Any other places to update?

(Just opening this for tracking, feel free to assign to you)

**Comment by gilgongo** [comment]
I assume we can do the change to the release branch, and maybe for each lang just paste in the English - don't want to delay the release for that really.
