### ISSUE TITLE
[Bug] Branches "release" and "changes" are out-of-sync

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#362]
I've just merged #333 to the `release` branch. Afterwards, I've received an email `[jamulussoftware/jamuluswebsite] Sync release to changes workflow run`, linking to https://github.com/jamulussoftware/jamuluswebsite/runs/2133076952?check_suite_focus=true

The main problem is the cherry-picking my commit (0a147d015b9872bc34c743a0a80f529aafb4def2) or merging `release` into `changes` leads to conflicts. I think this should not happen.

In fact, I'm pretty sure that things had been out of sync even before my PR as attempting to merge defeb1e0e8a800a5fc29f631636b42ae41d1c547 (the 3.7.0 translation merge) into `changes` also fails with conflicts.

As far as I understand:
- `changes` should only receive updates to the English documentation.
- `changes` usually does not receive updates in the final stage of a release (maybe minor ones)
- Updates to `release` should always be mirrored to `changes`. I guess this is what the Github action does?
- The diff between `release` and `changes` should be really minimal (or zero) at this stage (release almost done / translations merged), but it isn't.

What I think might have happened:
- `release` has been changed without changing `changes`
  - Could this happen if the Github action is broken? Was it?
  - Could this happen when directly committing to `release` instead of using a PR?
- In theory, this should not be a problem. A single merge should fix this and should apply without conflicts. However, it doesn't.
- Therefore, I assume that translated files have also been modified in `changes` without having been modified in `release`.

What I propose:
1. If we are really sure that `changes` does not contain any fixes after the translation process has been started, we can either force `changes` to be at the same commit as `release`. This would require a force push and may confuse people. We can also make the branches identical by merging `release` (to merge histories), ignore all conflicts, reset working copy to `release` and commit this merge. There is at least one commit (799cce3ffea79d97a92062b7cb089ba13617a739) on 2021-03-12, so this may not be true.
2. If `changes` may contain relevant updates (hopefully only to the English files!), we could merge `release`, ignore all conflicts, reset the working copy of all English files to `changes` and reset the working copy of all non-English files to `release` (as this is what the translators have verified).
3. We could still go with 1) and just cherry-pick any changes which might get lost otherwise.

I'm tending towards 2) but this needs confirmation by someone who knows the process/history better than I do (@ann0see? @gilgongo?).

In addition, we should think about how to avoid this issue in the future.

This is not a blocker for 3.7.0, but we should fix this as soon as possible afterwards to avoid any additional discrepancies which may be even harder to solve.

**Comment by gilgongo** [comment]
> Updates to release should always be mirrored to changes

Is that automated? If so I didn't realise any Github action was doing that.

Also, I was under the impression that I could commit to changes any time. But what you imply is that unless there was some automation to keep the branches in sync, we'd need to have a "changes freeze" once the translation branch was started, is that right? If so I'm fine with that if it's easier (we can even put locks on branches I think),

**Comment by hoffie** [comment]
> Is that automated? If so I didn't realise any Github action was doing that.

Based on the mail and action failure I got, I think so. Seems to be configured here:
https://github.com/jamulussoftware/jamuluswebsite/blob/changes/.github/workflows/sync.yml

Looks like it's supposed to do its work on each push and it looks like it has been failing since 20 days:
https://github.com/jamulussoftware/jamuluswebsite/actions/workflows/sync.yml

**Comment by hoffie** [comment]
> Also, I was under the impression that I could commit to changes any time. But what you imply is that unless there was some automation to keep the branches in sync, we'd need to have a "changes freeze" once the translation branch was started, is that right? If so I'm fine with that if it's easier (we can even put locks on branches I think),

I think it might be OK to continue working on changes in specific cases (e.g. English-only). When this is guaranteed, there should be no conflicts. We should merge from `release` to `changes` regularly to verify this and solve if necessary. This should happen via that action.

**Comment by ann0see** [comment]
Yes, your analysis is correct. Unfortunately the merge of the docs also broke the download links which obviously don't exist yet. But that's not a big issue since we're releasing today anyway.

I just merged release into changes and fixed the conflict. 

> changes usually does not receive updates in the final stage of a release (maybe minor ones)

If we want to avoid conflicts, yes. But I'd say that we can always deal with them? That's why I suggested we could always work on changes.

> Updates to release should always be mirrored to changes. I guess this is what the Github action does?

Yes. That's true.

As I said somewhere else:

1. release is the "live" branch. Everything we merge here will be available on jamulus.io
2. translate* is a prerelease branch which should only be active during the translation process
3. changes should be for english translations only and will be the base for the next release.

A release process works as follows:

1. Create a translate branch on the base of release
2. Open a PR from changes to translate
3. Wait on translations
4. Once we're releasing, merge the translate branch into release
5. GH actions should now automatically merge release to changes, but this didn't seem to happen. 

This way, we should have a clean diff for translators to get all the changes they need.

**Comment by hoffie** [comment]
> Unfortunately the merge of the docs also broke the download links which obviously don't exist yet.

Ah, didn't think of it when @gilgongo asked in the chat.

> If we want to avoid conflicts, yes. But I'd say that we can always deal with them? That's why I suggested we could always work on changes.

I agree, but what happened here was that there were conflicts in non-English files. I don't think this should happen if we adhere to the process. This will also be hard to solve for us without translators.

So I'm still wondering what went wrong in this case and what to avoid in the future?

**Comment by ann0see** [comment]
I just did another test. GH actions suggests it's because the changes branch is a protected branch and therefore it can't commit to it.

**Comment by hoffie** [comment]
> I just merged release into changes and fixed the conflict.

This looks very good, thanks! There is still a diff between `changes` and `release` which shouldn't be there, I think:
https://github.com/jamulussoftware/jamuluswebsite/compare/changes...release

It looks like `changes` is missing the ASIO4ALL 2.15 beta update and a spacing fix for Spanish.

Edit: In fact, it seems to be just e655312693a23e493aa34df02cc8dd89f8e7eb2b which is missing as it was just committed.

**Comment by ann0see** [comment]
Yes. That was to check the GH Action. I'll disable the protection for changes.

**Comment by hoffie** [comment]
Then I think everything is solved and the culprit was most likely the missing merges by the Github action due to the branch protection. Thanks!

**Comment by ann0see** [comment]
I hope so.
