### ISSUE TITLE
Presonus studio 24c 

### ISSUE THREAD

**Issue by pieterbos** [jamulussoftware/jamulussoftware.github.io#372]
To add to the list of known good devices:

- Focusrite scarlett tested to works very well on several different macs (so 'should' can be removed)
- An older focusrite FireWire clarett works well on Mac

Presonus studio 24c works:
- on Windows with the provided ASIO driver, provides the absolute best USB audio interface round trip latency we have seen, tested to have 4.1ms at 48khz, 64 samples
- works very well on mac, we have not measured rtl

I have some more audio interface RTL measurements, measured with oblique RTL utility or with Jack delay, all at 48khz 64 samples:
-Behringer umc202hd: 7ms windows, 10.5ms Linux and mac
- focusrite Scarlett: around 7ms windows and Mac OS. 
- hifiberry dac+ adc pro on raspberry pi 4: 4.9-5.1ms stable, 3.1-3.3ms possible with realtime kernel, but unstable during UI interaction.

But since there are no RTL measurements on that page, perhaps not so interesting.

**Comment by ann0see** [comment]
Sorry, just saw this... the focusrite should already be on the page as far as I know?

Not sure about the presonus devices. Can you edit this file: https://github.com/jamulussoftware/jamuluswebsite/blob/release/_posts/2021-01-05-Jamulus-Sound-Devices.md ?

**Comment by pieterbos** [comment]
Yes, but the Scarlett has a 'should work great', that can be 'works great', and the clarett firewire can be added next to the thunderbolt one. And the presonus is not on the list. I'll edit the file soon!

**Comment by ann0see** [comment]
Ok. Great!

**Comment by ann0see** [comment]
Not sure about the status of this issue? Did you already edit the page?

**Comment by pieterbos** [comment]
Sorry about the delay, I had been a bit busy. I opened a pull request for the changes.

**Comment by ann0see** [comment]
Thanks
