### ISSUE TITLE
[Bug] Jekyll build for Spanish was broken

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#373]
**URL**
https://jamulus.io/es/

**Describe the bug**
@ignotus666 noticed that https://jamulus.io/es/ and all sub-pages returned a 404, apparently after I had merged this PR #369 at 8:41 CET.
- I don't see anything strange in the PR.
- The [Github Jekyll action for `release`](https://github.com/jamulussoftware/jamuluswebsite/runs/2137624265?check_suite_focus=true) was listed as green (did not find anything non-green elsewhere either).

I re-triggered the [most-recent jekyll release action](https://github.com/jamulussoftware/jamuluswebsite/actions/runs/663785526) at about 10:53 CET and the site was working again at 10:54 CET.

I am also wondering why the second rebuild due to @gilgongo's merge of #370 at 8:50 CET did not fix it.

We should
- [ ] Find the root cause which caused the breakage
- [x] Maybe set up some basic monitoring? I could probably do that. I'm running Prometheus for my own infrastructure and its blackbox_exporter can check HTTP status codes or content.

**Comment by gilgongo** [comment]
Not sure how to reproduce this. I guess monitoring would be a first step?

**Comment by hoffie** [comment]
> Not sure how to reproduce this. I guess monitoring would be a first step?

Yes. I'm planning to set this up in my private monitoring infrastructure. If wanted, I can forward any alerts to team@.

BTW, I think there has been another breakage event recently which @ann0see fixed by forcing a rebuild.

**Comment by gilgongo** [comment]
Interesting. Maybe this means we have to check all changes locally? From time to time we (well, I) make changes via Github and just trust the build scripts.

**Comment by hoffie** [comment]
I rather suspect that this might be a temporary problem with the CI? So that would be hard to spot locally. All those cases I've spotted were fixed by starting a rebuild in some way (sometimes by pushing another change, sometimes by restarting the CI job).

**Comment by hoffie** [comment]
What I have done now is:
- Run a quick & dirty link checker (`wget`, see below) once per hour (because it causes some traffic)
- Check index pages for all languages for status 200 code once per minute 

Both alerts currently onyl reach me directly. Let me know if I should add specific people or team@.

I do not see any chance to find the root cause for the initial issue right now, so I'll close this issue as it is no longer actionable.

```
#!/bin/bash
set -eu
OUTPUT=/home/jamulus/jamulus_io_metrics.prom

echo -n 'jamulus_io_broken_links ' > "$OUTPUT.tmp"
(wget --spider -r --no-directories --no-verbose -l3 https://jamulus.io |& grep -qF 'Found no broken links.' && echo 0 || echo 1) >> "$OUTPUT.tmp"
mv "$OUTPUT.tmp" "$OUTPUT"
```
