### ISSUE TITLE
Link installation scripts 

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#374]
Related to https://github.com/jamulussoftware/installscripts/issues/1

The website should link a quick download to the installation scripts which are being removed from the main repo.

**Comment by gilgongo** [comment]
This should be part of (yet another) re-write of the install docs for Linux I think. Now that we have our .deb, everything to do with compilation (including [here](https://jamulus.io/wiki/Compiling)) should I think be moved off the site and into the compiling.md in the repo where such things usually live by convention. 

Normal people don't compile (I'm joking, but you know what I mean) :-) 

BTW stuff like Flatpak or non-deb methods can be mentioned on the website as links to compiling.md I think. The UX of Linux should ideally be the same as that of other platforms: download installer, read docs on how to set up.

I'll see if I can add this to my list of doc re-jigs and we can discuss on a PR?

See also https://github.com/jamulussoftware/jamuluswebsite/issues/382

**Comment by ann0see** [comment]
Yes. That sounds good.
