### ISSUE TITLE
[Bug] Rename alt text in footer: Remove Source Forge reference

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#375]
**URL**
https://jamulus.io/
https://github.com/jamulussoftware/jamuluswebsite/blob/97544de8ac776af71b525ff0e2e6e75275e871e5/_data/en/general.yml#L6

**Describe the bug**
The alt text linking to the GH Forum is wrong. Since it needs translation, I'm not sure what to do here.

**Comment by gilgongo** [comment]
@ann0see Can you explain what you mean? There doesn't appear to be a link to the GH Forum.

**Comment by ann0see** [comment]
Yes there is: if you click the question mark in the footer, you'll be redirected to the GitHub Discussions forum. 

What needs to be done:

1. change the variable name
2. change the variable content

Afterwards: 

* remove the reference to sourceforge on the privacy page (if that hasn't been done already)
* Have a look at the graphics of the question mark. The color doesn'tseem to be right
