### ISSUE TITLE
Audio devices known to work with Jamulus

### ISSUE THREAD

**Issue by Robert53844** [jamulussoftware/jamulussoftware.github.io#376]
Audio Device 1: 
**ZOOM LiveTrak L-8**
Using "L-8 Driver" (ASIO, 07/02/2020) from https://zoomcorp.com/
Latency: 19 ms (measured with local server with ping time of 0 ms)

Audio Device 2:
**ZOOM H2N**
Using "Stereo ASIO Driver" (06/02/2020) from https://zoomcorp.com/
Latency: 26 ms (measured with local server with ping time of 0 ms)

Both devices works great with **Jamulus 3.6.2** and **Jamulus 3.7.0** on **Windows 10, Version 20H2**.
Could not do any testing using macOS | Linux.

**Comment by ann0see** [comment]
Thank you for your report!

**Comment by ann0see** [comment]
I've just opened a pull request (#377) for you which adds these devices. Could you please verify if everything is ok and if possible add direct driver download links: https://github.com/jamulussoftware/jamuluswebsite/pull/377/files

**Comment by hoffie** [comment]
> I've just opened a pull request (#377) for you which adds these devices. Could you please verify if everything is ok and if possible add direct driver download links: https://github.com/jamulussoftware/jamuluswebsite/pull/377/files

Sorry, I only read your comment after I had merged that PR already. :(
If we find driver links we would probably have to open a new PR.

**Comment by Robert53844** [comment]
Driver for ZOOM LiveTrak L-8: https://zoomcorp.com/documents/186/L-8_Driver_Win_v1.0.0_E.zip
Driver for ZOOM H2N: https://zoomcorp.com/documents/10/H_and_F-Series_ASIO_v4.0.0_E_2_3_0.zip
Of course, both links may change for updated versions.

**Comment by ann0see** [comment]
Great! Thank you. Maybe it's better to link an overview page then (if they update the links). BTW: You can try to edit this file yourself: https://github.com/jamulussoftware/jamuluswebsite/blob/release/_posts/2021-01-05-Jamulus-Sound-Devices.md

and add your tested devices/links if you want.
