### ISSUE TITLE
Audio devices known to work with Jamulus

### ISSUE THREAD

**Issue by Robert53844** [jamulussoftware/jamulussoftware.github.io#378]
**ZOOM H2** (the "older one" - not the successor **H2N**, which works as well)
Description: https://zoomcorp.com/en/us/handheld-recorders/handheld-recorders/h2/
(Click "Support & Downloads" on this page for navigation to driver download page.)

The **Stereo ASIO Driver** (06/02/2020) for H2N and Windows 7/8/8.1/10 works as well for H2:
https://zoomcorp.com/documents/10/H_and_F-Series_ASIO_v4.0.0_E_2_3_0.zip
(Link depends on driver version, so it may change in the future)

Latency: 26 ms (measured with local server with ping time of 0 ms - same as for H2N)

Device works great with Jamulus 3.6.2 and Jamulus 3.7.0 on Windows 10, Version 20H2.
Could not do any testing using macOS | Linux.

**Comment by ann0see** [comment]
Thanks. Just a short question: can you edit the Sound devices page yourself: https://github.com/jamulussoftware/jamuluswebsite/edit/release/_posts/2021-01-05-Jamulus-Sound-Devices.md ?

**Comment by Robert53844** [comment]
I've tried to do it (see pull request #383). Hope everything is ok; it was my first time using Git.

**Comment by ann0see** [comment]
I think you did everything right ;-)
