### ISSUE TITLE
Windows powershell run instruction update [Bug]

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#380]
https://jamulus.io/wiki/Compiling

I have compiled the source on my windows machine and believe a minor change is needed in the compile instructions.

Under the "Compling and building installer" topic step 5 mentions to run the powershell command with the C:\Qt\QtVersion argument. I believe this is no longer required and does not seem to make a difference when you do provide this argument.

**Comment by gilgongo** [comment]
We need to re-vamp the Linux installation page now that we have the binary installer, and move the compilation instructions for all platforms to one place as part of that. I'll link this and other compilation issues to a master ticket on that. 

See also:
https://github.com/jamulussoftware/jamuluswebsite/issues/382

**Comment by gilgongo** [comment]
Just looking at this now but since I don't have a Windows build environment I can't verify that removing step 5 will be OK. Can anyone confirm?

**Comment by henkdegroot** [comment]
@gilgongo step 5 is still required, just the part to specify the qt folder is not.
