### ISSUE TITLE
Update Compilation Documentation

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#382]
Page url:
https://jamulus.io/wiki/Compiling#download-jamulus-source-code

The issue with spaces (issue 864) has been resolved now, so the text on this page (see below) can removed now. 

Make sure that there are no spaces in the directory you move the jamulus directory to since it might break the Jamulus installer

**Comment by gilgongo** [comment]
Let's turn this into a master ticket for re-jigging the Linux installation as well so that compilation for all platforms is in one place. The UX of installing for Linux is now with the binary.
