### ISSUE TITLE
USB-Hub causing some trouble with ASIO-driver only in jamulus

### ISSUE THREAD

**Issue by tackin** [jamulussoftware/jamulussoftware.github.io#384]
**URL**
https://jamulus.io/de/wiki/Client-Troubleshooting

**Describe the bug**
Not a bug but a highly recommended info should be added. I run in to an unspecified error telling me during the "connect to server" that I have "a problem with my soundcard".
I use a ZOOM H4pro connected via USB over a USB-Hub to my PC Win8 (Generic ASIO-driver) and it works great so far. But Jamulus refused work in clientmode. 
After hours of search on my computer I found out, the USB-Hub I used caused the problem for jamulus. 
Connecting my ZOOM H4 to an USB3-Port directly on my PC solved my problem.
So I would recommend to give the "Troubleshoot-advice" to connect any USB-Mic/Dvice directly to the computer and NOT use any USB-hub in between at first-aid try.

Feel free to delete or move this input/issue if needed.
And sorry, but I couldn't find a better place to get this info to you.

**Comment by ann0see** [comment]
Hmm. I always use my docking station and my Interfaxe works with it. Can you add content to the troubleshooting page: https://github.com/jamulussoftware/jamuluswebsite/edit/changes/wiki/en/en-Client-Troubleshooting.md

**Comment by tackin** [comment]
Of course. Done.

**Comment by ann0see** [comment]
Thanks (Danke).
