### ISSUE TITLE
Document contribution process

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#385]
I think @gilgongo already worked on restructuring the contribution pages?

We can discuss the documentation of the new process here

Possibly Related https://github.com/jamulussoftware/jamuluswebsite/issues/91

**Comment by gilgongo** [comment]
Yes. https://github.com/jamulussoftware/jamuluswebsite/issues/314

**Comment by ann0see** [comment]
Ok. Closing this then
