### ISSUE TITLE
MaxNumChannel is wrong

### ISSUE THREAD

**Issue by DominikSchaller** [jamulussoftware/jamulussoftware.github.io#388]
https://jamulus.io/wiki/Command-Line-Options

Is says MaxNumChannel is 50, but it really is 150

**Comment by ann0see** [comment]
Ok thank you. Can you update it on the [release branch (wiki folder)](https://github.com/jamulussoftware/jamuluswebsite/tree/release/wiki) for every language on the command-line-options page?
