### ISSUE TITLE
Privacy: Clarify that audio is sent without encryption

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#395]
Sonobus clearly states that it's sending audio without encryption. I think we should also clarify this on the privacy page for Jamulus since users deserve to know that. 

This should *not* turn into a discussion of implementing encryption. If we want to discuss this topic, please open an issue on the main repo.

**Comment by gilgongo** [comment]
This is just adding a line in the privacy statement, is that right?

**Comment by ann0see** [comment]
Yes. Probably

**Comment by gilgongo** [comment]
OK I put a line in "Please note that all audio and text data is sent and received between the Jamulus server and client without encryption."
