### ISSUE TITLE
[Translate] Screen shots languages !

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulussoftware.github.io#413]
# Language you want to translate to
Fr and all others
# Description
There is a 'jamuluswebsite/assets/img/en-screenshots/' directory.
Isn't it more interesting to create also fr-screenshots directory (and all other languages) in order to have all the images stored at the same place ?

**Comment by gilgongo** [comment]
Yes, the intention of the "en-screenshots" directory is so that there can be an "es-" "de-" and other directories if/when translators want to do that. Not sure what you mean by "interesting" though?

If you want to create "fr-screenshots" and use them on the French translations, feel free to do so. BTW we have a new CSS style to handle screenshots with captions. Not sure when that will be released though.

**Comment by jujudusud** [comment]
`Not sure what you mean by "interesting" though?`
I mean something like:

- identical to 'en- ' workflow and organisation of the website files,
- upgradable with new screenshots only by replacing images by the new file with the same name
(no need to change the txt file of a page),
- centralized because it is possible to update all screenshots in one action without having to search for them one by one in the pages (and missing some).
I will first create the directory in the changes' branch and copy/past all the french screenshots already presents on all the pages and disseminated in the "usergithub" side of the repository.
After that, I have some other ideas that I can do on l my own if anybody in the project is ok. :-)

`BTW we have a new CSS style to handle screenshots with captions.`
Could you please show me where I can read some information of this new CSS style (I'm not a webdesigner, don't know much about those things).

Thanks for your response.

**Comment by gilgongo** [comment]
Yes, that's the idea. I've also got a task to convert all the images that are currently using `user-images.githubusercontent.com` to being img tags hosted from the repo for this reason. We'll do that in the English version first on the changes branch.

The new style will allow you to use the `<figure>` and `<figcaption>` HTML tags. But not yet until that's live - so when you say _"I will first create the directory in the changes' branch and copy/past all the french screenshots already presents"_ - don't do that yet or you will have to it all again when the markup changes in the English.

If you want to create a set of French language screenshots based on the English ones though that's fine. You can link to them later.

**Comment by gilgongo** [comment]
Now that we've got the screenshot markup in the changes branch I'll close this because translators will be able to create their own directory in `assets/img/[lang]-screenshots/` now.
