### ISSUE TITLE
ASIO4ALL has been updated

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#439]
**URL**
https://jamulus.io/wiki/Installation-for-Windows#asio

**Describe the bug**
ASIO4ALL 2.15 Beta 2 has been released. We should update it on the website.

Todo:

- [x] Push the binaries to the assets repo
- [x] Update the links for every language

To discuss: Should we still link beta 1? Did anyone test beta 2?

**Comment by gilgongo** [comment]
I see that Beta 2 supports Windows 10 only.

**Comment by ann0see** [comment]
Yes. But the same is for the other Beta. Do you think we should update it now?

**Comment by hoffie** [comment]
It would be good to have at least one Jamulus dev or user provide feedback that it works, I think? Especially considering that we are linking to beta releases...?

**Comment by ann0see** [comment]
I used beta 2 and it works a lot better than the stable release.

**Comment by hoffie** [comment]
Cool! Then maybe replace the beta1 link with beta2?

**Comment by ann0see** [comment]
Yep

**Comment by ann0see** [comment]
Done
