### ISSUE TITLE
Update fr web translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#458]
Hi @jujudusud, @trebmuh,

We are getting ready for the 3.8.0 release and have created the [translate3_8_0](https://github.com/jamulussoftware/jamuluswebsite/tree/translate3_8_0) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..translate3_8_0)).

Because the English is still going through large changes, we are not expecting translations of anything other than the following pages:

- [Home page](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/1-index.html)
- [Setup](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Setup.md) (renamed from Getting-Started)
- Installation pages for each supported platform ([Windows](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Windows.md), [Mac](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Macintosh.md), [Linux](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Linux.md))

While you are of course welcome to translate more than this, please be aware that you may have to re-translate for the next release.

We would be happy if you updated the translations for **fr** until **2021-05-15**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `translate3_8_0` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **translate3_8_0** branch with the subject `Update fr web translation for 3.8.0`,
- Link your PR(s) to this issue by including `Fixes #458` in the PR content.

Note: The term "Central server" has been replaced with "Directory server"

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Suggested commit and PR message:
```
Update fr web translation for 3.8.0

Fixes #458
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/README.md#translating).

Thanks for contributing to Jamulus!

**Comment by jujudusud** [comment]
Translate FR done:
- [x] 1-fr-index.html
- [x] data/fr/general.yml 
- [x] data/fr/navigation.yml
- [x] wiki/fr/fr-Choosing-a-Server-Type.md
- [x] wiki/fr/fr-Client-Troubleshooting.md
- [x] wiki/fr/fr-Command-Line-Options.md
- [x] wiki/fr/fr-Compiling.md **-> suppress <-**
- [x] wiki/fr/fr-Contribution.md
- [x] wiki/fr/fr-Demos.md
- [x] wiki/fr/fr-Directory-Servers.md
- [x] wiki/fr/fr-Getting-Started.md **->suppress<-**
- [x] wiki/fr/fr-Hardware-Setup.md
- [x] wiki/fr/fr-Installation-for-Android.md
- [x] wiki/fr/fr-Installation-for-Linux.md
- [x] wiki/fr/fr-Installation-for-Macintosh.md
- [x] wiki/fr/fr-Installation-for-Windows.md
- [x] wiki/fr/fr-Network-Requirements.md
- [x] wiki/fr/fr-Onboarding.md
- [x] wiki/fr/fr-Privacy-Statement.md
- [x] wiki/fr/fr-Running-a-Private-Server.md
- [x] wiki/fr/fr-Running-a-Server.md
- [x] wiki/fr/fr-Server-Linux.md
- [x] wiki/fr/fr-Setup.md
- [x] wiki/fr/fr-Server-Troubleshooting.md
- [x] wiki/fr/fr-Server-Win-Mac.md
- [x] wiki/fr/fr-Software-Manual.md
- [x] wiki/fr/fr-Tips-Tricks-More.md
- [x] wiki/fr/fr.FAQ.md
- [x] wiki/fr/index.md

**Comment by gilgongo** [comment]
Wonder why this didn't close when we merged the linked PR? It says "a pull request that will close this issue".

**Comment by hoffie** [comment]
> Wonder why this didn't close when we merged the linked PR? It says "a pull request that will close this issue".

Seems like the explanation is in the [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):

> Note: The special keywords in a pull request description are interpreted when the pull request targets the repository's **default** branch. However, if the PR's base is any other branch, then these keywords are ignored, no links are created and merging the PR has no effect on the issues.

I wasn't aware of that though. :(

Maybe that's why the UI says "Successfully merging a pull request **may** close this issue."

**Comment by gilgongo** [comment]
OK so closing manually then.
