### ISSUE TITLE
Update it web translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#459]
Hi @dzpex,

We are getting ready for the 3.8.0 release and have created the [translate3_8_0](https://github.com/jamulussoftware/jamuluswebsite/tree/translate3_8_0) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..translate3_8_0)).

Because the English is still going through large changes, we are not expecting translations of anything other than the following pages:

- [Home page](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/1-index.html)
- [Setup](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Setup.md) (renamed from Getting-Started)
- Installation pages for each supported platform ([Windows](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Windows.md), [Mac](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Macintosh.md), [Linux](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Linux.md))

While you are of course welcome to translate more than this, please be aware that you may have to re-translate for the next release.

We would be happy if you updated the translations for **it** until **2021-05-15**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `translate3_8_0` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **translate3_8_0** branch with the subject `Update it web translation for 3.8.0`,
- Link your PR(s) to this issue by including `Fixes #459` in the PR content.

Note: The term "Central server" has been replaced with "Directory server"

Suggested commit and PR message:
```
Update it web translation for 3.8.0

Fixes #459
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/README.md#translating).

Thanks for contributing to Jamulus!

**Comment by dzpex** [comment]
thats ok! i will try to respect the data

**Comment by jujudusud** [comment]
Hi here, I have this image if you wanted to translate screenshots :
![italian-verification-mac](https://user-images.githubusercontent.com/12748768/117546290-fbd32a80-b029-11eb-9213-5f6190798223.png)
