### ISSUE TITLE
[Bug] Getting started or Setup?

### ISSUE THREAD

**Issue by ewarning** [jamulussoftware/jamulussoftware.github.io#468]
**URL**
https://github.com/jamulussoftware/jamuluswebsite/blob/translate3_8_0/wiki/en/en-Installation-for-Macintosh.md

**Describe the bug**
I’m doing the translation to german, and I was told „Getting started“ should be renamed to „Setup“. On the page above says Getting Started though.

Sorry if I’m missing something, I’m quite new both here in team and in GitHub as well.

**Comment by gilgongo** [comment]
Sorry for the confusion. The file "Getting-Started.md" will still exist but will redirect to "Setup.md". I should have just changed the content of "Getting Started" and not created a new page... :-( Too late now.

Links to "Getting Started" can stay as they are I think as the meaning is almost the same. The reason the English used "Setup" is that it's shorter - easier to use in navigation.

**Comment by gilgongo** [comment]
@ewarning Is that OK can now? Can we close this?

**Comment by jujudusud** [comment]
I have translated all the `Getting Started` By `Setup` in french.

**Comment by gilgongo** [comment]
Yes, in English they are very similar terms.
