### ISSUE TITLE
Update pt web translation for 3.8.0

### ISSUE THREAD

**Issue by ewarning** [jamulussoftware/jamulussoftware.github.io#469]
# Language you want to translate to
Portuguese

# Description
As I’m already doing the german translation, I could also in a fly do portuguese as well, if desired. Let me know.

**Comment by hoffie** [comment]
I guess it would be welcomed by those readers :)
@gilgongo @melcon @Snayler What do you think?

**Comment by ewarning** [comment]
Okay, I’ll work on that, already commited two pages. Is there away to link my PR to this issue and the german one at the same time?

**Comment by gilgongo** [comment]
Bear in mind that there will be (yet another) quite large set of changes in the next release as we come out with a User Manual and Server Admin Manual, and re-adjust some other stuff around that (also perhaps a new web site layout/navigation). So you will re-doing some of this ... :-(

**Comment by melcon** [comment]
Welcome aboard @ewarning.

I'll fix my fork first then will start looking at pt_BR web as well.

**Comment by Snayler** [comment]
I'm ok with that, I never got the time to do the website translation

**Comment by jujudusud** [comment]
Hi ewarning,
do you plan to create the necessary screenshots for the website based on the EN screenshots ?

**Comment by ann0see** [comment]
@ewarning once the site is released, could you please check if everything is ok for PT and German (especially that everything is in sync with en)?

**Comment by ewarning** [comment]
> do you plan to create the necessary screenshots for the website based on the EN screenshots ?

Sorry, I’ve been busy I’ll do the ss right now.

**Comment by ewarning** [comment]
I’m not sure I’m doing it right. I uploaded the pics to my rep on the branch translate_3_8_0 and created a PR as I did before. But all my changes and commit are showing up there, is it supposed to be like that?

**Comment by ann0see** [comment]
Since the new website is out, you‘ll need to have a look at the release branch. Let me first merge @ignotus666 pr
