### ISSUE TITLE
[Question] Installation for Linux - no more compilation instructions?

### ISSUE THREAD

**Issue by ewarning** [jamulussoftware/jamulussoftware.github.io#470]
Sorry if I’m annoying you guys with thousand questions.

I’m translating the Installation for Linux now, and I noticed (as a Linux user myself), that the instructions for compiling the source code are no longer there. Is it intended to be that way?

**Comment by jujudusud** [comment]
It is intenses.
Compiling informations are often at the same place as sources. Si, now it is here :
https://github.com/jamulussoftware/jamulus/blob/gilgongo-compiling/COMPILING.md

**Comment by hoffie** [comment]
@ewarning Does @jujudusud's reply answer that for you? If so, please close this issue. Thanks :)
