### ISSUE TITLE
DOC: onboarding information outdated

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulussoftware.github.io#480]
In the onboarding section of the documentation there is the following information:

`
The buffer delay setting is a fundamental setting of the Jamulus software. This setting has an influence on many connection properties. Three buffer sizes are supported:

64 samples: The preferred setting. Provides the lowest latency but does not work with all sound cards.
128 samples: Should work for most available sound cards.
256 samples: Should only be used on very slow computers, or with a slow internet connection.
`

128 samples is preferred according to the UI. The screenshot is outdated and shows 128, 256 and 512 samples.

**Comment by ann0see** [comment]
Hi @reneknuvers I've just transferred this issue to the documentation repository.

Do you mean the Software Manual page: https://jamulus.io/wiki/Software-Manual#buffer-delay there are multiple outdated screenshots and I think either @gilgongo or @jujudusud are working on them for the next release. If you want, you can help them, but I think the new release of the website will fix some of these issues. Have a look at https://github.com/jamulussoftware/jamuluswebsite/tree/translate3_8_0 and https://github.com/jamulussoftware/jamuluswebsite/tree/changes which should both contain the new files from which the new site will be built. Feel free to contribute and update the images.

**Comment by jujudusud** [comment]
Will be updated with the 3.8.0 release of the app.
