### ISSUE TITLE
Formatting in Tips-Tricks-More.md

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#484]
I know you're busy at the moment with the release - this isn't a pressing issue, but it'd be great if someone with some knowledge of formatting in markdown files could help me out here because nothing I do seems to work.

When converting .md files to .po, all the formatting has to be transferred too, and it works fine for every single file except the one in the title. It contains a few scripts wrapped in triple tildes to highlight them, and for some reason the first one comes out fine (left raw text and right the resulting .md view):
![right](https://user-images.githubusercontent.com/4263412/119472924-f45e9180-bd4a-11eb-8cc1-9d4da1c8d065.png)

But the next few come out in continuous lines (in both the original and target segments after processing), with no line breaks and the tildes seeming not to fulfil their function:
![wrong](https://user-images.githubusercontent.com/4263412/119473259-49020c80-bd4b-11eb-84f9-37b48b4741af.png)

To clarify: what you see on the left is the segment after processing by po4a. All the scripts look fine in the original EN .md file. What's bizarre is that the first one is processed correctly while the rest are not.

I've tried inserting all kinds of line breaks, spaces, backslashes... but nothing works to replicate the hidden "magic" in the first script. Copying and pasting from the original EN to the processed/translated .md file works, but that's not practical and kind of defeats the purpose of using po4a, even though it's just one file. There must be some kind of line breaks, but they either won't show up in any editors, or are shown to be the same as a normal break by pressing enter - when they obviously are not.

It's probably something trivial, but I've wasted an awful lot of time and maybe someone knows what's going on.

Edit: some more info.

This is what the first script looks like in Lokalize:
![right_2](https://user-images.githubusercontent.com/4263412/119477121-faef0800-bd4e-11eb-91a6-02c0b2daf813.png)

And this is what the second script looks like:
![wrong_2](https://user-images.githubusercontent.com/4263412/119477357-2d006a00-bd4f-11eb-8d53-a768e4fe32c0.png)

I tried inserting those \n line breaks but it doesn't work. I suspect whatever line breaks it has are interpreted as such by po4a/Lokalize, but they're something else as they're not visible in the original file.

**Comment by ann0see** [comment]
Hmm. I think there’s also another way to format code: use three \` instead of \~. Maybe this solves the problem?

**Comment by ignotus666** [comment]
Tried that - it didn't work. It doesn't cause a problem for the first script so it must be something else. I think it's some kind of line break that I can't identify.

It's the \n¶ at the end of each line, but with some version of \n that does the same and is hidden. That's my uninformed hypothesis anyway...

**Comment by ann0see** [comment]
You could have a look at it with an ASCII editor? Linux & Mac vs Windows line breaks maybe?

**Comment by ignotus666** [comment]
Fixed it. I found someone having a similar problem with Kicad/po4a. It was a matter of inserting a space before the start of each line. I don't know if it's a bug or po4a is following some kind of formatting rule too strictly, but it's a minor issue - this is the only doc it happened with.
