### ISSUE TITLE
[Knowledge Base] Alternative Linux install methods

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#489]
Although it's not an official way to obtain Jamulus, tormodvolden seems to host Jamulus for Ubuntu: https://launchpad.net/~tormodvolden/+archive/ubuntu/jam/+packages 

There are also various other methods out there (and see also https://github.com/jamulussoftware/jamulus/discussions/2133)

We might link it somewhere on the linux installation page?

**Comment by gilgongo** [comment]
OK, but for every external thing we link to like this it's more content for us to maintain over time. Also, I would think explaining how to set up a PPA is more complicated than the installation instructions we have now (unless we literally just link to it I guess).

**Comment by ann0see** [comment]
A ppa is much more convenient and more "the Ubuntu way". It allows automatic upgrades and a standard way of maintaining software installs/updates/removal. So it’s a one time setup. 

We might need to explain the user that there are multiple ways to obtain Jamulus:

1. Get Jamulus from the official distribution repo
2. Get the official .deb
3. Use an unofficial PPA for automatic upgrades
4. Use Flatpak
5. Compile it from source


and we can‘t always give a recommendation. 

1 and 3 are convenient but maybe provide old software, 2 is official, 4 is a bit less convenient since you need pipewire, 5 is sometimes needed if all other methods don’t work.

**Comment by gilgongo** [comment]
Yes, but point about the repo is that we don't maintain it, so without regular checks we don't know if it's up to date. 

As to the rest of the options, my general view is that more content = more work = more potential for problems. Most other multi-platform software out there (eg VLC, Gimp, others) have a single supported way of installing their Linux stuff for that reason I think. And ours is (currently) to install our .deb.

If people want alternative install methods, we could put links to 3rd party stuff on the knowledge base perhaps?

BTW Not sure I understand what you mean by "Get Jamulus from the official distribution repo" vs "Get the official .deb"? We're not in the (current) Debian repos are we? Or do you mean some other distro?

**Comment by ann0see** [comment]
> If people want alternative install methods, we could put links to 3rd party stuff on the knowledge base perhaps?

Yes probably. I think we could move the Flatpak there. But this would need some one who knows Pipewire... I tested  pw on Debian 11 with the normal build of Jamulus and it performed worse than native JACK. Maybe some people get it run probably...

> BTW Not sure I understand what you mean by "Get Jamulus from the official distribution repo" vs "Get the official .deb"? We're not in the (current) Debian repos are we? Or do you mean some other distro?

official distribution repo = repository of the linux distribution you are using. We are in [Debian Buster backports now ](https://packages.debian.org/de/buster-backports/jamulus) and of course still in multiple other repos.

**Comment by gilgongo** [comment]
When this was all discussed, I understood that the .deb file download and install was the official method for now because we're not fully in control of what releases go into other repos. But perhaps others can clarify that.

**Comment by hoffie** [comment]
> When this was all discussed, I understood that the .deb file download and install was the official method for now

I'd say it is, yes.

> because we're not fully in control of what releases go into other repos.

And we may never be and that would be totally acceptable, IMO.

Not all Linux distros ship Jamulus and most may not ship the latest version, especially those distributions which backport bugfixes only for a given release (*EL, Debian, ...).

The PPA is somewhere in-between -- it's neither officially by us nor officially by the distro. It's obviously a benefit for users (download .deb files and installing them manually is not and should not be common on Linux), but having yet another place is a bit strange. It would probably be best to have an official repo, but that'd mean maintenance again...

**Comment by gilgongo** [comment]
My assumption is that just like the other platforms, if we support Linux (5% of the users base), then we have a duty to ensure that "download the latest, supported, correct version" does just that. If people want to maintain lists of alternative methods controlled by others, I'd say that's one for the KB really.

**Comment by ann0see** [comment]
Ok. So we should then create a KB page ;-)!

**Comment by ann0see** [comment]
ToDo: Document
Flatpak,
Debian Repo,
Repology,
Docker by grundic


Also a bit related:

Document more related projects like jamcaster by @dtinth

**Comment by ann0see** [comment]
Ok. Created https://github.com/jamulussoftware/jamuluswebsite/commit/af4a0d6ba418909e814255eea25f46635afd307d

**Comment by ann0see** [comment]
Since the KB page is now up, I'll close this. We can always update the KB page.
