### ISSUE TITLE
Link legacy macOS build on website

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#501]
We now provide two builds for macOS: legacy and the normal one. We should link both on the macOS page.

**Comment by gilgongo** [comment]
What's the reason? I've not been following the macOS stuff.

**Comment by ann0see** [comment]
The new build with Qt 5.15.2 supports macOS Big Sur without UI glitches and multiple small bugs but breaks compatibility to old versions of macOS. See: https://github.com/jamulussoftware/jamulus/pull/1687 and especially https://github.com/jamulussoftware/jamulus/pull/1768

**Comment by gilgongo** [comment]
Oh OK, so it's just a straight OS version split on the download page. I assume we therefore maintain two versions of 3.8.0+ from now on? 

Just trying to work out what impact this has on what we say on the website.

**Comment by ann0see** [comment]
> I assume we therefore maintain two versions of 3.8.0+ from now on?

Yes. I think we could just link the legacy build from the macOS page the same as for the SourceForge mirror

**Comment by gilgongo** [comment]
How does that work with the links exactly then? Do we have two `{{ site.download_file_names.mac }}` variables and change the SF link to point to the versions directory instead or something?

**Comment by ann0see** [comment]
I think something like this would be enough: 

![macOS](https://user-images.githubusercontent.com/20726856/120376426-2d36d180-c31c-11eb-9e8a-abdcdcba63b4.png)

**Comment by gilgongo** [comment]
So will we need to update these links for each release (until we abandon support for anything lower than macOS 11)?

**Comment by ann0see** [comment]
Unfortunately yes.

But it's all in _config.yml

**Comment by ann0see** [comment]
Ok. Just pushed this change to translate

**Comment by ann0see** [comment]
@ignotus666 @jujudusud I also added the legacy link to your translations. You can translate them later on

**Comment by jujudusud** [comment]
Done for FR, to be merged.
