### ISSUE TITLE
Anchor link at Server-Linux page not correct

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#508]
**URL**
https://jamulus.io/wiki/Server-Linux

https://jamulus.io/wiki/Tips-Tricks-More

**Describe the bug**
In the Recording section at the bottom the following text is written:

See [this information](https://jamulus.io/wiki/Tips-Tricks-More#controlling-recording-on-linux-headless-servers) on controlling recordings on headless servers.

The url used for "this information" is: https://jamulus.io/wiki/Tips-Tricks-More#controlling-recording-on-linux-headless-servers

The _#controlling-recording-on-linux-headless-servers_ does not exist on that page, so when you click the link you get to see the top of page.

The correct link needs to include an S, recording => recordings.
Working link is: https://jamulus.io/wiki/Tips-Tricks-More#controlling-recordings-on-linux-headless-servers

**Comment by ignotus666** [comment]
This has been fixed in PR #510.
Same anchor was missing in FR.

**Comment by jujudusud** [comment]
> Same anchor was missing in FR.

Is it ok now ?

**Comment by ignotus666** [comment]
Yes, they should be all fixed in #510

**Comment by jujudusud** [comment]
@henkdegroot if you are ok, we can close this issue since de PR is now merged. ;-)

**Comment by henkdegroot** [comment]
Working fine now.
