### ISSUE TITLE
[Knowledge Base] Connecting to JACK

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#511]
Just documenting this for anybody who wants to take it up:

> If we have a general "Connecting Jamulus to JACK" page on the wiki, it might be worth linking that from each message, too.

_Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/pull/1732#r637373198_

**Comment by pljones** [comment]
I take it we'd want to cover all platforms, not just Linux, with this.

**Comment by gilgongo** [comment]
Connecting to JACK is a requirement to run Jamulus under Linux so it's on the website itself ([I assume](https://jamulus.io/wiki/Installation-for-Linux#configure-jack-with-qjackctl)). For other platforms, it's an option so would qualify for either the KB or T&T I think. 

Just so I'm clear, what's the primary advantage of using JACK on other platforms? If it's not just a minority interest (routing?) and leads to better performance or something, we might want to talk about it more formally perhaps?

**Comment by pljones** [comment]
Allegedly better overall latency than ASIO4ALL - but I can't corroborate.  Plus routing and multi-client, etc, that you'd need some other set up (e.g. ReaRoute/Reaper on Windows) to achieve.

The reason I think it would be good if it were clearly documented in one place is that it's pretty much the same set up process for Jamulus, regardless of platform, with JACK.  (Setting up JACK is a per-platform thing, then, of course...)

**Comment by ann0see** [comment]
It’s not only related to Linux of course. Once https://github.com/jamulussoftware/jamulus/pull/1829 is merged, it could be equally applied to Windows. Also https://jamulus.io/kb/2021/04/18/Jamulus-Video.html could benefit from a link?

**Comment by gilgongo** [comment]
Possibly naive quesition since I've never used JACK outside of Linux, but seeing as so many Windows users have issues with ASIO, if JACK helps  that situation would we consider preferring JACK to ASIO in the docs?

**Comment by ann0see** [comment]
No. Better give a hint at it but nothing specific. You‘d still need ASIO. JACK adds too much complexity - especially for ASIO4ALL users.

**Comment by pljones** [comment]
Yep, on Linux, you've three or four different audio stacks but generally the user is well-protected from them because they co-operate fairly nicely.  On Windows there are... well, lots of audio stacks and none of them co-operate with the others particularly well.  JACK isn't, itself, an audio stack, it's just an audio router - it still needs an audio stack to connect to.  (It uses PortAudio on Windows to help protect the code from insanity...  PortAudio just being an abstraction layer over the actual audio stacks, whether it's PortAudio on Windows or Linux or whatever.)

**Comment by gilgongo** [comment]
Oh OK. So it makes sense to have it in the KB only then.

**Comment by jujudusud** [comment]
Since "Jack on windows" is available from the official Windows installer, it is a good idea to document more precisely a sort of "how to" use it.

**Comment by gilgongo** [comment]
> Since "Jack on windows" is available from the official Windows installer, it is a good idea to document more precisely a sort of "how to" use it.

Yes, but from what I understand, the use cases for Windows JACK version seem to be pretty specialised (mainly around doing what you might do with Voicemeeter, only without the latency issue?).

**Comment by pljones** [comment]
People use Voicemeeter for a couple of main reasons:
* connecting multiple physical interfaces to audio applications without ASIO contention (i.e. "You can only open one ASIO device driver")
* connecting many kinds of audio applications to each other (WinMME, WDM, DirectSound, WASAPI push, WASAPI event, ASIO -- although probably not all of them...).

The first point has an alternative in ASIO4ALL, as that allows you to open multiple input and output devices and make them look like a single ASIO device to an ASIO application.  ASIO4ALL only offers WDM but has a fancy "Allow Pull Mode" checkbox ("WaveRT") for hardware buffering (saving a rebuffer, but not always functional and sometimes broken - although probably most modern non-ASIO hardware would work as well as it's going to like this).

The second point is harder to address, generally.  Fortunately, it's a more specialised need, which I guess leads to few easy solutions being available.

JACK can help by using PortAudio to open your hardware.  (Given I can't get it working, I don't know how flexible it is - Audacity, which works for me, only offers WinMME and DirectSound and WASAPI (event?).)  It can then be used to route audio between applications -- either "native JACK-aware" or, via JackRouter, ASIO-based.  (JackRouter _may_ be adding one buffer's worth of latency in and out... I can't remember... so there's a little bit of benefit going JACK-native when possible.)

There's an alternative to JACK in Reaper with ReaRoute - but it's proprietary and ASIO-only. 

Voicemeeter "just works" but then everyone complains it adds latency...  (I think it probably has to buffer at the buffer size of the device with the largest buffer, with two buffers in and out... so could be easily adding 2048 samples of latency in/out even if you asked for 64...  I could very easily be wrong.)

**Comment by ann0see** [comment]
Not 100% related, but I just published https://jamulus.io/kb/2022/01/26/Routing-JACK-Windows.html

It's certainly not a full guide, but probably a good starting point for semi-experienced Windows users.

**Comment by ann0see** [comment]
I assume we should close this since at least it's partly done with my and @henkdegroot 's KB-Entry (and I think it's at least giving a good hint)
