### ISSUE TITLE
Server registration - illegal characters

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#514]
The server registration requirements are not clearly documented - semicolon and newline should not be allowed.

See https://github.com/jamulussoftware/jamulus/pull/1803 and https://github.com/jamulussoftware/jamulus/pull/1804

This should form part of the server administrator's guide.

**Comment by ann0see** [comment]
Since you're now using Base64 encoding, I'll close this one.
