### ISSUE TITLE
Viewing the logs doesn't work as specified (wiki/en/Server-Linux.md)

### ISSUE THREAD

**Issue by tenorix** [jamulussoftware/jamulussoftware.github.io#516]
https://jamulus.io/wiki/Server-Linux
wiki/en/Server-Linux.md

Error in Section "Viewing the Logs".

Currently, the shown commands for viewing the logs refer to systemd unit `jamulus` (e.g. `journalctl -u jamulus`).
It should be `jamulus-headless` - otherwise it won't work.

-- 
Note: This is my first issue on github :)

**Comment by ann0see** [comment]
Hi @tenorix! Thanks for raising this issue. Probably that's outdated information ;-). I'm not exactly sure if we can change this in the live version (asking @ignotus666 here) but I'm quite sure that we can fix this for the next release. I've tagged it to the 3.8.1 Milestone.

**Comment by ignotus666** [comment]
I think we could. Correct it in EN, run po4a-update-templates.sh, validate that segment in ES and FR (.po files) and run po4a_create-all-targets.sh - it shouldn't need translator input as it would be inserted as a fuzzy match.

**Comment by ignotus666** [comment]
I can do it if you want.

**Comment by ignotus666** [comment]
Added to PR #517. I edited the .po .pot and .md files directly to avoid the deluge of modified files and it works.

**Comment by ann0see** [comment]
Ok. Thanks for working on this @ignotus666 and thanks @tenorix for mentioning it! It should be fixed soon.
