### ISSUE TITLE
[Bug] Command-Line-Options lacks options such as --server, --multithreading

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulussoftware.github.io#520]
Describe the bug
There appear to be valid command line options missing from the list at https://jamulus.io/wiki/Command-Line-Options

To Reproduce
I'm doing a clean install of 3.8.0, building it myself without a *.deb file. I'm creating the *.service file manually. For 3.7.0, my ExecStart was:

ExecStart=/usr/local/bin/Jamulus 
--server 
--nogui 
--serverinfo "School of Rock WS;Seattle, WA;225" 
--welcomemessage "message here" 
--numchannels 20 
--multithreading
--fastupdate 
--centralserver anygenre2.jamulus.io:22224

Expected behavior
Of the command line options I'm using, the Wiki is missing:

--server
--serverinfo
--welcomemessage
--numchannels
--multithreading

--centralserver has been replaced by --directoryserver, so I'm not surprised that it's missing from the Wiki. But the others are not mentioned in the Change Log so are likely still available, but missing from the Wiki.

Operating system
Linux Debian x64

Version of Jamulus
N/A

Additional context
N/A

**Comment by jujudusud** [comment]
Waiting for the other members of the website team.
My point of view is that the website have to list all the available options in command line.

**Comment by ann0see** [comment]
True. I assume this page is being reordered by @gilgongo? 

>  My point of view is that the website have to list all the available options in command line.

Yes. But we'll move over to the server manual soon and I think this site will then be less important (and should then document all features [including --analyzerconsole -L etc.])

**Comment by gilgongo** [comment]
That's a bit strange those are missing! I seem to remember there was a merge conflict at one point. Maybe they got lost in that? I was trying to reconcile some differences between the output of `-h` and what we had on the website.  

Thanks for spotting though.

**Comment by gilgongo** [comment]
Fixed with https://github.com/jamulussoftware/jamuluswebsite/pull/527
