### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by reinhardwh** [jamulussoftware/jamulussoftware.github.io#530]
**URL**
Please provide the url of the page in question.
https://jamulus.io/wiki/Command-Line-Options

**Describe the bug**
Language problem, typo, confusion, misleading thing, device formatting, accessiblity issue ... let us know.

Hello
Important parameter like

-T Multi Threading
-s Servermode (mandatory for service file)

are not mentioned

If you agree those should be added

Thanks!

**Comment by ann0see** [comment]
I think that’s already a known issue and will be fixed in the next cycle. 

See https://github.com/jamulussoftware/jamuluswebsite/pull/527
