### ISSUE TITLE
Use colours for proposed sound devices

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#541]
The KB page https://jamulus.io/de/kb/2021/01/05/Jamulus-Sound-Devices.html shows devices which do not work that well on e.g. Windows since they need ASIO4ALL. I‘d suggest to color the OS name in green/red/yellow depending on OS support. 

We should use a css class to add the missing colours.

**Comment by gilgongo** [comment]
Symbols or some non-colour device would also need to be added for accessiblity.

**Comment by ann0see** [comment]
What about ❌ and ✅

**Comment by gilgongo** [comment]
That would be good! :-)
