### ISSUE TITLE
According to the website [software manual](https://jamulus.io/wiki/Software-Manual), 64 samples is the preferred setting to use for the Buffer.

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulussoftware.github.io#545]
According to the website [software manual](https://jamulus.io/wiki/Software-Manual), 64 samples is the preferred setting to use for the Buffer.
However the text in the GUI dialog indicates 128 samples is the preferred option.

Which is the correct one?

One of them should change....

_Originally posted by @henkdegroot in https://github.com/jamulussoftware/jamulus/discussions/1895_

**Comment by jujudusud** [comment]
According to Jamulus application, 128 samples is the preferred is option.
I will open a PR as soon as possible to change that in the online website.

**Comment by gilgongo** [comment]
I've updated this in next-release so feel free to translate it.

**Comment by jujudusud** [comment]
I will translate in next-release instead.
