### ISSUE TITLE
Run po4a scripts via gh actions

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#553]
As commented elsewhere, it would be good to automate running the po4a scripts via a gh action. I did some initial tests and created a couple of .yml files that can be found [here](https://github.com/ignotus666/jamuluswebsite/tree/GH_actions_test/.github/workflows) (targets.yml and templates.yml). What they do:

- po4a-update-templates.sh only gets triggered when edits are pushed to files in wiki/en/
- po4a-create-all-targets.sh only gets triggered when edits are pushed to files in translator-files/po/**

I did it that way because I think it's pointless to trigger the po4a scripts if anything else is edited.

po4a and its dependencies are cached to speed things up (vs installing every time). This cache gets purged if not used for 7 days or more, so if it can't be found, a new one is automatically created. The catch is that a po4a .deb package not available from any repos is required. I put one I created in the root folder but I assume it's not the best practice.

Hopefully some or all of the scripts can be used (a few things would need to be renamed in any event). As set up on that branch, they work. However, due to my very poor grasp of this gh action business, there are probably more sensible ways to go about it. This issue is to get the ball rolling and discuss the best approach.

**Comment by ignotus666** [comment]
I managed to combine both .yml scripts into one. Depending on what files have been edited (en/*.md or po/**.po), the corresponding po4a script is run. See the script [here](https://github.com/ignotus666/jamuluswebsite/blob/GH_actions_test2/.github/workflows/po4a.yml). It's made possible using the [Paths Changes Filter](https://github.com/marketplace/actions/paths-changes-filter).

**Comment by ann0see** [comment]
Added to my todo list; once I find time, I‘lll look at code and give some thoughts on this.

**Comment by ann0see** [comment]
Ok. So your scripts basically install all dependencies, run the scripts and then push everything? 

The best thing which could happen would be to only create the .md files in the wiki folder right before Jekyll runs via CI. We’d 
 not even add them to the live repo. This removes the possibility to edit .md files on the live site accidentally entirely.

**Comment by ignotus666** [comment]
> Ok. So your scripts basically install all dependencies, run the scripts and then push everything?

Yeah.

> The best thing which could happen would be to only create the .md files in the wiki folder right before Jekyll runs via CI. We’d
> not even add them to the live repo. This removes the possibility to edit .md files on the live site accidentally entirely.

So you mean run the create targets script as a step in the creation of the Jekyll site?

**Comment by ann0see** [comment]
Yes. Basically we could implement a similar workflow to the main repo CI process.

**Comment by ignotus666** [comment]
Giving this further thought, I'm not sure it's a good idea to only create the .md files just before they get deployed. Even if someone managed to mistakenly edit a doc in the wiki folder, it's solvable simply by running the 'create targets' script again - it will delete all the files and re-create them based on the "correct" .po versions. There will inevitably be mistakes made when translating (formatting, spelling...) and translators should be able to view the .md version of their translations before signing them off. Not necessarily the website view, but at least on github.

I'm not sure how that could be done.

When someone translates .po files and pushes them to their branch (in their fork), could their branch run the po4a script via GH actions so they can check their translation in .md format? Is it possible to enable by default certain workflows for forks/branches? Otherwise they'd have to wait until their changes were pushed to the main repo - which is a bit late - or run the scripts manually themselves, which defeats the whole purpose of automating them. It would also give them an early warning if the scripts failed for whatever reason (unwittingly edited metadata, etc). But: the po4a.yml script currently pushes the changes it makes, so if branches run it before submitting their PR, there's little point in it being run again when this PR is pushed to the main repo.

Maybe it's simpler than I'm making it out to be - or more complex...

**Comment by ann0see** [comment]
>  Is it possible to enable by default certain workflows for forks/branches? 

I think, in theory it should be possible. At least once you enable GitHub actions in your repo. See https://github.com/jamulussoftware/jamuluswebsite/pull/515 which could even generate .html files.

**Comment by ignotus666** [comment]
> I think, in theory it should be possible. At least once you enable GitHub actions in your repo

Yes, if you actively enable them, they can all be run (if they are not limited to a specific branch). I just was wondering if they could be enabled by default without the "forker" explicitly having to.

> See #515 which could even generate .html files.

I had a look at that and ran it on my branch, but I wasn't sure how to actually view the zipped website. I downloaded the .zip file, unzipped it, _unzipped the extracted .zip file_, then CD'd into the _site folder and ran 'jekyll serve'. I could then view it, but I though it was a bit of a pain... Is there an easier way?

**Comment by ann0see** [comment]
You don’t need to run Jekyll serve. Just double-klick the index.html file

**Comment by ignotus666** [comment]
> You don’t need to run Jekyll serve. Just double-klick the index.html file

I'd tried that and did so again - it won't work for me. I get the index page in the browser but none of the links work. Jekyll serve however does work nicely.

**Comment by ann0see** [comment]
Hmm. Probably the document root is wrong then.

**Comment by ignotus666** [comment]
Yes, I think it's a paths issue. The browser wants an absolute path but the links in index.html only provide relative paths. That's what I think is happening anyway. Also - no images or anything, just text.

**Comment by ignotus666** [comment]
I didn't really understand whether I couldn't view the zipped website because of my own incompetence or not, but assuming it's easily done, I've been doing some tests with all the translated .md files removed from /wiki as @ann0see suggested. I created a workflow that does the following:

- If changes to docs in wiki/en are pushed, this triggers the po4a-update-templates script. The results of running the script (updated .po files) are automatically pushed as well. A zipped version of the website is created. I assume it functions as a check to see if the site builds properly anyway so I let it run too.

- If a .po file is edited (translated) and pushed, this triggers the po4a-create-all-targets script. The results of the script are not pushed to the branch (to avoid creating the folders in /wiki) but are picked up by the action that builds and zips the website. Translators would be able to download the zipped site and view their translations before submitting them.

- If anything else is edited and pushed, all the po4a-related steps are skipped and the site is built and zipped.

The above would be a workflow run on branches. Editing main.yml to include the step to create the translated .md docs for gh-pages shouldn't be too hard, but I'll leave it there for now as I'm not entirely sure I'm going in the right direction. But if it works out the way I think it does, it means we can get rid of all the translated folders in /wiki and translators can check their translations if they want.

The script can be found [here](https://github.com/ignotus666/jamuluswebsite/blob/GH_actions_test4/.github/workflows/po4a.yml).

**Comment by ignotus666** [comment]
This is a comparison between what (I think) current GH actions do and what the ones I propose would do:

| Trigger | Current | Proposed |
|------------|------------|------------|
| PR to 'next-release' **Case 1** | jekyll.yml runs, test building the site. | The same, but if the PR contains edits to EN .md files, the update-templates po4a script runs to include the changes in the build (but doesn't push them). Since translated .md files are no longer in the repo, the create-all-targets script always runs to create the translated files for the CI build or deployment to the website, but never pushes them to the repo. The site build is zipped and uploaded. Only triggered by PR (not "on: push") |
| Merge (push) to 'next-release' **Case 2**  | Same again.  | Same again, but after the commits in the PR are merged (pushed), the results of the update-templates script are also pushed IF the changes were to EN .md files (to update the .po files). This requires a separate, slightly modified version of the script for the PR scenario above: this one is only "on: push" and also pushes the output of the po4a script to the repo. **EDIT**: It's possible for a single script to push changes or not depending on whether it was triggered by a PR or push. |
| PR to 'release' **Case 3** | Same as PR to 'next-release' | Same as PR to 'next-release' |
| Merge (push) to 'release' **Case 4** | jekyll.yml; main.yml and sync.yml are run, test-building, building and deploying the website, and syncing 'release' with 'next-release' | Basically the same changes as in **Case 2**, but also applying them to the 'main.yml' script: the po4a scripts are run (if there are any changes to EN .md or .po files) and passed on to the step that deploys the website. |

I can see the logic of running jekyll.yml in cases 1, 2 and 3, to have a "preview" version of the site, but wouldn't it be redundant in case 4, as the site is going to be deployed anyway? Besides, it would also mean potentially running the po4a scripts twice, which is unnecessary. I've prepared and tested scripts for cases 2 and 4 and they do what I describe above. I haven't tested 1 and 3 because they are just slightly simpler versions of 2 and 4 but I will when I get time.

These scenarios assume that actions are **not** run on branches, meaning translators would not be able to see an .md version of their translations until they submit a PR. On the one hand it would be nice if they could, but on the other it'd mean that users would have to manually enable actions and I'm not sure if adding more requirements and things to remember is the best move. By only running the scripts on the main website repo, however, it also means we won't get PRs with massive amounts of timestamp changes (though line changes and different text wrapping would still occur).

A lot to take in I know :-) I'm basically thinking out loud and trying to document my thoughts before they get lost. It's a damn sight trickier than I'd imagined...

**Comment by ann0see** [comment]
Hmm. To me - from a first glance - it looks ok like that.

> I can see the logic of running jekyll.yml in cases 1, 2 and 3, to have a "preview" version of the site, but wouldn't it be redundant in case 4, as the site is going to be deployed anyway?

As far as I know, that's already kind of the case on the main code repo: Autobuild builds twice (once for PR, once for merge). 
If the po4a scripts get run twice we must ensure that this doesn't clutter the commit history. We might want to check if anything changed (check md5 hash of each .po file?).

**Comment by ignotus666** [comment]
>  Autobuild builds twice (once for PR, once for merge)

Yes, that's how it'll work here too, but what I mean is that, on merge (not a PR) to release, I don't see the point of running both jekyll.yml and main.yml. Shouldn't main.yml be enough?

**Comment by ann0see** [comment]
Yes, running main.yml would be enough.

**Comment by ignotus666** [comment]
Ok, so I've got a working version of the scripts in #568, which behave as in the table above:
- jekyll.yml runs on PR and push to 'next-release', and on PR to 'release'.
- main.yml runs on push to release.
