### ISSUE TITLE
Show up to date translation status in repo

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#557]
The idea was to offer an up-to-date overview of the status without having to load the files anywhere or run a script. If it can be shown elsewhere (and in a more visually appealing way) I'm all for it.

_Originally posted by @ignotus666 in https://github.com/jamulussoftware/jamuluswebsite/pull/550#discussion_r661704253_

**Comment by ann0see** [comment]
Unsubscribed from this issue; if you need me just ping me.

**Comment by ignotus666** [comment]
I updated the statistics script so it creates a markdown file that's not as unpleasant to read (it used to create a plain text file). See [here](https://github.com/ignotus666/jamuluswebsite/blob/GH_actions_test3/_translator-files/statistics.md). I don't know if the use of LFS will change anything, but hopefully this can be included in some shape or form so translators can easily see what the status of their language is.
