### ISSUE TITLE
Duplicate text/incorrect placement of image?

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#561]
**URL**
https://jamulus.io/wiki/Server-Win-Mac

**Describe the bug**
The Server Installation page seem to contain duplicate text. See image:
![server-webpage](https://user-images.githubusercontent.com/13550012/124978399-01e98580-e032-11eb-95aa-e6fd724c085e.png)

Also not sure why the text is place in brackets. 
Perhaps the image should be place below the first text line? But then still it is almost duplicating the text and also referencing the "central server" instead "directory server".

Just reporting this issue here, in case it has not been noticed/picked up yet.

**Comment by gilgongo** [comment]
Yes, this was corrected as part of https://github.com/jamulussoftware/jamuluswebsite/pull/527

**Comment by henkdegroot** [comment]
It would be nice if #527 would be merged so that the "public" can see the improvements.....:)

**Comment by ann0see** [comment]
That would mean a new release and translation process. Are we there yet? Closing this issue since it’s fixed on next-release probably
