### ISSUE TITLE
DRY-RUN: Test release process for r3.8.0 po4a and smaller changes #579

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#580]
As proposed by @ignotus666 we're doing a test translation round for the po4a workflow. This issue should focus on all the discussion around the process.

**Comment by ann0see** [comment]
@ignotus666 commenting here

Translations get merged into next-release; next-release is frozen until this one is merged. But I think we still need an OK by @gilgongo to ensure nothing unfinished/for r3.8.1 gets released

**Comment by ignotus666** [comment]
Ok, I get it.

**Comment by gilgongo** [comment]
Not sure how I would determine that though. The docs I did for the next release I don't think had anything that would relate to [anything here](https://github.com/orgs/jamulussoftware/projects/2?card_filter_query=milestone%3A%22release+3.8.1%22 ) is that what you mean?

**Comment by ann0see** [comment]
Yes. If we added content for 3.8.1 this should be removed. If not, we can start the process. See https://github.com/jamulussoftware/jamulus/milestone/4

**Comment by gilgongo** [comment]
What about these? https://github.com/jamulussoftware/jamuluswebsite/milestone/3

**Comment by ann0see** [comment]
I think the current status of them is ok too.

**Comment by ignotus666** [comment]
If possible, I'd go through the different processes to see if they work (create a checklist?) and to get familiar with them.

Preferably in this order to avoid disrupting any potential translation process:

- Edit/add EN content in wiki/en/ (next-release). Check that it shows up in the .po files.
- Make a correction to an EN doc in release and validate the corresponding segment in (translated; no need if they're not) .po files. Verify that the sync with next-release works without conflicts.
- Optional: add a language (Chinese? maybe the person who did the app translation can be approached - a single test file would be enough).
- Translation of .po files. I have translation memories that may come in handy, particularly for FR as it has the most translated content.

**Comment by ann0see** [comment]
Yes. You should document the process somewhere ;-). I‘ve already opened #579 which will show  all the differences between next-release and release. Later on this will need to be merged to put all stuff live.

Concerning the new language, maybe try to go through the process yourself and later remove the language.

**Comment by ann0see** [comment]
CC: @jamulussoftware/translators 

You might want to monitor this issue since it‘s related to translation. There’s no need to start the translation process now, however I think it’s good if you’re aware that we try to test the new po4a translation workflow.

**Comment by ignotus666** [comment]
> You should document the process somewhere ;-)

Well, from the point of view of editing EN content, not much has changed. However, it is documented in /wiki/README. The translation process is documented in _translator-files/README.

> I‘ve already opened #579 which will show all the differences between next-release and release

Is there a particular reason why we need to see the differences? It's not needed by translators in any event.

**Comment by ignotus666** [comment]
> It's not needed by translators in any event.

At least not anything in /wiki/en/. Changes to other documents not covered by po4a that need translation, e.g. in _data, 1-index.html etc. will need to be documented somewhere so translators are aware they need to update their translations. A future enhancement might be to somehow process these files with po4a too.

**Comment by ann0see** [comment]
Yes. By documentation I mean the process we‘re doing to release the repo should be part of a checklist:
- [ ] Open a pull request from release to next-release and set it to draft
- [ ] Mention all translators and point them to changes not part of the .po files
- [ ] Wait until translations arrive
- [ ] Review each translation PR
etc. Similar to the release checklist by hoffie: https://github.com/jamulussoftware/jamulus/blob/644f1c7653bcec09ee6854f0826b5ea14870cf8d/.github/ISSUE_TEMPLATE/release_new_version.md

**Comment by ann0see** [comment]
> Is there a particular reason why we need to see the differences? It's not needed by translators in any event.

No, but at one point we need to merge next-release into release. If a draft PR is already open, reviewing is easier. At one point once we click on merge, the site goes online.

**Comment by ignotus666** [comment]
I think I've figured out how to also process with po4a the files in _data and _includes, and also the index.html files, using symlinks. It would mean the status for all translatable docs could be in the "Statistics" file for consultation, removing the need to document changes to these files.

**Comment by ignotus666** [comment]
I've decided against it. Po4a does a sloppy job of segmenting these files (1 or 2 giant segments in most cases), and any change in their EN counterparts causing the templates to update would wipe out practically the entire translation -> not good.

**Comment by ignotus666** [comment]
What I will be doing is getting rid of the wrapping in the .po files - it causes an utter mess in PRs every time someone opens them in a different editor and it doesn't offer any benefits other than just looking tidier when reading the raw .po file. It's also been mentioned as a cause of git conflicts, so it's going (with the `--wrap-po no` option). This means translations shouldn't start yet as it will take some work to do the switch (make sure all translations are stored in TMs, re-create .po files without wrapping and re-populate them with translations).
