### ISSUE TITLE
Add Basque language [eu]

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#581]
Adding the "new language" label should trigger the creation of a new language folder  (`_translator-files/po/eu`) containing the corresponding .po files.

**Comment by ignotus666** [comment]
Success! Will remove the test files now.

**Comment by ann0see** [comment]
Great! 

Actually, I think the GH actions commit message should say AUTO: add new language (eu)

and if possible link #581. But that’s just a minor enhancement

**Comment by ignotus666** [comment]
Done. See #582
