### ISSUE TITLE
Document location of configuration files of Jamulus

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#588]
I will probably not work on this, but I think it needs to be done (and is not that difficult). Therefore I assume, It could be a good first issue (for people with at least some background knowledge of Jamulus).

Related to: https://github.com/jamulussoftware/jamulus/discussions/1939

Todo:
- [x] Find the file locations of the Jamulus configuration files (Jamulus.ini and JamulusServer.ini)  and document them on this issue (Windows [%AppData%/Jamulus] or similar, macOS [???], Linux [.config/Jamulus])
- [x] Decide where to document the paths to the files (Tip: https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/wiki/en/Tips-Tricks-More.md or in the knowledge base)
- [x] Open a Pull Request

**Comment by henkdegroot** [comment]
macOS:
I located the Jamulus.ini at the following path:

/Users/user/.config/Jamulus

This contains both the Jamulus.ini and Jamulusserver.ini. Note the "user" in the above is the name of the user. Guessing the /Users/user part is some environment variable.

**Comment by gilgongo** [comment]
If we're going to document this, we need to be clear why :-) The following points probably need to be considered:

1. Upgrades of ini files are never backwards compatible.  So if you want to roll back to an older version of Jamulus, you also need to restore the ini file(s) for that version (so knowing the location of the ini file might be useful).

1. Manually editing ini files is not normally necessary and certainly not recommended (they're not designed for that).

1. There are some inconsistencies in the way clients and servers work with ini files which may produce unexpected effects between what's given in the ini file, the UI and any command-line options. And headless servers don't use them.

1. Ini files can be saved and loaded via the UI and stored anywhere (so you don't need to know where the defaults are).


So what would be the reason to document the paths exactly?

**Comment by softins** [comment]
* For Windows, the ini files are stored within `%APPDATA%\Jamulus`, which is usually `C:\Users\username\AppData\Roaming\Jamulus` (or maybe on `D:` instead)
* For macOS, as Henk mentioned, they are stored within `$HOME/.config/Jamulus`, which is usually `/Users/username/.config/Jamulus`
* For Linux, such as Ubuntu and RPi, they are also stored within `$HOME/.config/Jamulus`, but in this case that is usually `/home/username/.config/Jamulus`

In the above directories, the client stores the file `Jamulus.ini` and the server stores the file `Jamulusserver.ini` (unless the name is overridden with `-i`).

**Comment by softins** [comment]
Note also that if specifying a simple filename or relative path with `-i`, such as `-i jamtest.ini`, the file will be created in the current directory, not the default directory above. So it is necessary to give the complete path, such as by saying `-i $HOME/.config/Jamulus/jamtest.ini`

**Comment by gilgongo** [comment]
Done.
