### ISSUE TITLE
Contribution.md/CONTRIBUTING.md

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#598]
I was looking at where to link the translation stats file and noticed this: the `wiki/en/contribution.md` file on the 'next-release' branch links to a 'CONTRIBUTING.md' file on 'release'. Fine. But 'next-release' doesn't contain this file. When 'next-release' is merged into 'release', wouldn't that mean CONTRIBUTING.md disappears?

**Comment by ignotus666** [comment]
There's stuff I'd like to modify in both of these files: add link to stats and edit references to translation/adding languages. Both files basically repeat the same information about translating.

So should I make a PR against 'next-release' and toss 'CONTRIBUTING.md' back in again?

Edit: Maybe removing CONTRIBUTING.md was a deliberate decision? I see that the current README.md in the root directory contains most of what was in CONTRIBUTING.md. Maybe @gilgongo can clarify? If this is the case some links will need editing in `wiki/en/contribution.md` then.

**Comment by gilgongo** [comment]
Yes @ann0see moved all the contrib stuff to the website so I think it'll now all be in `wiki/en/contribution.md`?

**Comment by ignotus666** [comment]
Ok, then it makes sense that CONTRIBUTING.md won't exist any more. Opened #599 so `wiki/en/contribution.md` points to the right places.
