### ISSUE TITLE
Add Mackie Mixer to list of audio interfaces that work with Jamulus

### ISSUE THREAD

**Issue by Burnhaven** [jamulussoftware/jamulussoftware.github.io#607]
My Mackie ProFx6 v3 works fine with it's ASIO driver.

**Comment by ann0see** [comment]
Thank you! Can you add it to https://jamulus.io/kb/2021/01/05/Jamulus-Sound-Devices.html yourself to receive the credit?

**Comment by gilgongo** [comment]
Added
