### ISSUE TITLE
/contribute/Statistics: Broken "get involved" link in footer

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#628]
https://jamulus.io/contribute/Statistics contains a relative link to "Contribution" (in the "get involved" text in the footer). For regular pages, this is correctly resolved to /wiki/Contribution. For the Statistics page, it is not as it lives within a different directory.

Should probably be linked to `/wiki/Contribution` explicitly, but haven't confirmed that it doesn't break anything else.
Seems to affect translations as well.

The relevant file should be: `_includes/wiki/en/footertext.md` (+ translations)

Can't promise to send a PR atm. Will comment here if I can.

**Comment by ignotus666** [comment]
Thanks for pointing this out!
> Should probably be linked to /wiki/Contribution explicitly

This won't work - the link then resolves to `/wiki/wiki/Contribution` (just tried it). Maybe a solution could be to just move `Statistics.md` to `/wiki/en/`. It's a file that only gets created when the site is deployed via a GH action (and therefore doesn't 'live' on the repo), so I don't think it should matter much where it gets created. I'll have time tonight to look at it properly.

**Comment by ignotus666** [comment]
Ok, so if we tell the po4a-stats script to create `Statistics.md` in `/wiki/`, changing the permalink in its header accordingly (and the link in `Contribution.md`), the link works as it should. Since it's a "non-repo resident" file like the target translation files, I don't see any harm in letting it be created there.
