### ISSUE TITLE
[Bug] Can't link to macOS signed binary

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#632]
The way we do the variables for downloads doesn't let us have a link outside our repo. As of 3.8.1 the macOS signed binary is on [emlynmac's fork](https://github.com/emlynmac/jamulus/releases/download/r3_8_1/jamulus_3.8.1_mac.dmg).

**Note**: Once this issue is fixed, we can remove the section about unverified developer here: https://jamulus.io/wiki/Installation-for-Macintosh#jamulus-cant-be-opened-because-the-developer-cannot-be-verified

**Comment by ann0see** [comment]
@emlynmac @gilgongo it's not that difficult to edit the release ;-): https://github.com/jamulussoftware/jamulus/releases/edit/r3_8_1 I just uploaded the signed binary (although ofc we should verify it first).

**Comment by gilgongo** [comment]
Ok so similar to how we upload the released binaries to SF, we can do that for the macOS signed binary to GH. That'll work for the moment I guess.

Also need to add this step to the release process.

**Comment by gilgongo** [comment]
OK I've verified that the signed version works OK. I've updated the release to-do list. Have update the link on the download page (and in the announcement on GH, but FB doesn't let me edit it).

Will edit the statement about unsigned warning on the website, but realise we can't remove it as it will come up with legacy build.
