### ISSUE TITLE
QoS not linked to anywhere

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#642]
'QOS-Windows.md' was originally created as an include for use in multiple places, but currently it's only mentioned in 'Running-a-Server.md', albeit without a link to it ("To enable it, see section below"... but there's nothing below). If it's only going to be mentioned in one place it doesn't make sense for it to be an include. Not sure if there were any plans for QoS though - move it elsewhere and link to it or...

**Comment by pljones** [comment]
It should be mentioned from both client and server manuals, as it applies to both.

**Comment by ignotus666** [comment]
Actually, it's mentioned in 'Shared-Commands.md' (I was looking at the website and didn't realise), but the point still stands that QoS is not actually linked to.

**Comment by gilgongo** [comment]
I think it's because it applies to both client and server, and doesn't need to be a stand-alone page. I guess we should re-name it according to the new format - I forgot about it when we did that.

**Comment by ignotus666** [comment]
> I think it's because it applies to both client and server, and doesn't need to be a stand-alone page. I guess we should re-name it according to the new format - I forgot about it when we did that.

Yes, but the thing is that it's not actually linked to in Shared-Commands.md (or Include-Shared-Commands.md as it is named on next-release). There's currently no way to access the QoS information on the website.

**Comment by gilgongo** [comment]
Ah ok. It used to be included as a section after the CLI options. Must have removed it by mistake.

**Comment by ignotus666** [comment]
So here's the thing: AFAICT, QoS is only mentioned in Shared-Commands.md, so instead of being a separate include file -unless the intention is to link to it in other parts of the documentation- it would make sense to just do away with the QoS doc and paste its content into Shared-Commands.md. OTOH, I think that Shared-Commands.md will have to be modified separately on release and next-release as the file names are different (it has the 'Include-' prefix in next-release) - the auto-sync from release won't work.

**Comment by gilgongo** [comment]
Yes we could do that I suppose, but it was originally a separate file so that we could include it as a separate section.  I'm not sure it fits into shared-commands.md very well does it, content wise I mean.


By the way the use of the command line that affects QoS is in the docs.

**Comment by ignotus666** [comment]
> I'm not sure it fits into shared-commands.md very well does it, content wise I mean.

True, it's kind of out of place to have a concise list of command line options and then that whole slab of text on QoS whenever Shared-Commands.md is included. The other option would be to make it a stand-alone doc and link to it when required.

**Comment by gilgongo** [comment]
Can't we do what we originally did and include it as a separate section after the CLI (and before the Troubleshooting in the Server Manual's case)? I'd prefer to keep things in one ToC-enabled and browser-searchable page, unless they're long and of minority interest.

**Comment by ignotus666** [comment]
Yeah; I'm just getting a bit muddled... so it'd be removed from Shared-Commands.md as an include then?

**Comment by gilgongo** [comment]
Yes. The Shared Commands content and the QoS content are two separate pieces of content, and special in the sense that they need to be displayed in two places, hence the includes for them. 

I think it's just a matter of adding the QoS section back in as an include. I can re-name QOS-Windows.md to Include-QOS-Windows.md and do that for the Client and Server manuals (in next-release) if you like. Not sure why it got missed last time (but not a huge deal as it's Windows only and it seems QoS might not be respected by some ISPs anyway).

**Comment by gilgongo** [comment]
OK I've done that. With it re-named to Include-QOS-Windows.md, will the po4a script handle it OK?

**Comment by ignotus666** [comment]
Yeah, no problem.

**Comment by ignotus666** [comment]
Wait - so what happens with '(Include-)Shared-Commands.md'? Regarding QoS, it still says "To enable it, see section below", and there's nothing below. Do we get rid of this sentence?

It should also be fixed on 'release'.

**Comment by gilgongo** [comment]
Oh sorry, the "see section below" refers to the H2 (or is it H3) that is provided by that section below the CLUI options section.

Happy to fix it on release if Include-QOS-Windows.md has been translated - for some reason I assumed it hadn't.

**Comment by ignotus666** [comment]
It's translated into Spanish and French. I'll update those on 'next-release' because with the change of file name the translation isn't carried over.

**Comment by gilgongo** [comment]
I think we're OK to close now as per https://github.com/jamulussoftware/jamuluswebsite/commit/322dfb9049a9abce6af8ab4beb1c02482b77fcc9
