### ISSUE TITLE
Server Troubleshooting page links improvement to refer to paragraphs

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#651]
**URL**
https://jamulus.io/wiki/Server-Troubleshooting 

**Describe the bug**
_Improvement 1:_
At the first question, _Why doesn’t my server show up in the list? Why isn’t it registering?_, the following line is included. (The **text in bold** refers to another page).

If you are seeing a message that says the server is full, please **see this note** on Directory Servers.

The bold text links to the page (Directory-Servers), which then changes to the Running-a-Server page.
It would be good to enhance the link to include the "Directory-Servers" paragraph, so you are taken straight to the relevant text. I.e. change to (Running-a-Server#3-directory)

_Improvement 2:_
A similar thing happens with another referral at the same page, the question: _What address do I give to people so that they can connect to my server?_ contains the following line:

Note that your public IP address can change - see the note on “dynamic DNS” **in this guide**.

The bold text links to the page (Running-a-Private-Server), which then changes to the Running-a-Server page.
It would be good to enhance the link to include the "Dynamic DNS" paragraph, so you are taken straight to the relevant text. I.e. change to (Running-a-Server#dynamic-dns-and-why-you-will-probably-need-it)

**Comment by gilgongo** [comment]
Thanks for spotting! Fixed in release.
