### ISSUE TITLE
Incorrect text in 

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#652]
**URL**
https://jamulus.io/wiki/Running-a-Server

**Describe the bug**
The following text, in one of the bullets before the Server Types section, contains twice the same server type.

Running a **Private Server** at home will require you to port forward on your router. When running a **Private Server**, port forwarding should not be necessary in most cases, but it’s advisable to do so because some networks may not work properly with Jamulus in its default mode.

I believe the second text should be changed into **Public Server**

**Comment by gilgongo** [comment]
Fixed in next-release
