### ISSUE TITLE
Improvement reference link to Running a Server page

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#654]
**URL**
https://jamulus.io/wiki/Server-Troubleshooting

**Describe the bug**
The last paragraph contains a referring link to **port forwarding**. However when you click the link, you get the main page which contains details, instead jumping direct the section on port forwarding.

(Running-a-Private-Server#port-forwarding) should be changed into (Running-a-Server#port-forwarding) to resolve this.

**Comment by gilgongo** [comment]
Thanks - fixed on release.
