### ISSUE TITLE
Bugfix update (website) for 3.8.1

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#661]
Since a number of documentation issues applicable to 3.8.1 have been fixed and a complete Dutch translation has been added, we thought it would be nice to update the live website to include these changes, as the next application release probably won't be out for a long time still. The NL and ES translations have been updated to reflect the edits to the English documentation and it would be great if at least FR could also be updated, as it's very near complete - so pinging @jujudusud to see what he reckons.

Other language updates/new languages are of course welcome too!

**Comment by ann0see** [comment]
@jamulussoftware/translators as Ignotus mentioned in this issue, we are planning a bug fix translation round for the website. Please note that this is *not* a new release but follows basically the same procedure as for a new release. Please update your languages until 30.12.2021.

**Comment by jujudusud** [comment]
I will do the update as soon as possible for the FR langage.

**Comment by ann0see** [comment]
I know I'm late, but ASIO4ALL got updated: https://www.asio4all.org/ we should also upload the new version to the assets repo

**Comment by ignotus666** [comment]
If you update 'Installation-for-Windows.md' on next-release I can take care of updating the .po files for all languages. Not sure if @jujudusud is finally going to update FR.

**Comment by jujudusud** [comment]
It's already done. FR is up to date.
Commited directly in the main repository and the next release branch. @ignotus666

**Comment by ignotus666** [comment]
@jujudusud if you run `po4a-create-all-targets.sh` in ./po4a-tools, a Statistics.md file is created in ./wiki. There you can see what is missing. You can also see it in Poedit (instructions in the readme in ./_translator-files).
