### ISSUE TITLE
Operationsystem in Main page seems outdated

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#674]
**URL**
https://jamulus.io/

**Describe the bug**
OperatingSystem element seems outdated:

      "name": "Jamulus",
      "applicationCategory": "{{ page.ldjAppCategory }}",
      "operatingSystem": "Windows 10, macOS 10.11, Linux",
      "discussionUrl": "https://github.com/jamulussoftware/jamulus/discussions/",
      "license": "GPLv2",

Not sure if updating this makes any difference, but it would be nice to have it matching the software.

**Comment by ann0see** [comment]
In theory yes. Android and iOS are experimental

**Comment by henkdegroot** [comment]
And what about windows 11 or a later macOS?
Or is the intention of this element minimum supported version?

I did not even consider Android and iOS, since both are not available through the website.

**Comment by ann0see** [comment]
I think that’s the minimum version? Not sure what the official interpretation of the structured data is

**Comment by henkdegroot** [comment]
[https://schema.org/SoftwareApplication](https://schema.org/SoftwareApplication)

In the description for **operatingSystem**: Operating systems supported (Windows 7, OSX 10.6, Android 1.6).

**Comment by ann0see** [comment]
In my opinion that’s not really an useful example. Would you interpret we should add other OS?

**Comment by henkdegroot** [comment]
Initially I read it as the OS the application is working on. But can't really find other use cases/scenario's for this.
I also cannot find a reference to where/who this is used. I know it is used for rankings, but don't know if adding more will improve or make things worse. Personally I would say if the application is not specific "limited" to an OS version, then the OS should not include the "version" in the text. But that might be effecting rankings as well.

**Comment by ann0see** [comment]
Hmm. Maybe @gilgongo knows more? I initially added it in hope of Google showing it as search result for questions like "Which OS does Jamulus supprt". Google seems to get all the data from Wikipedia though. I'm not sure if we need to update it.

**Comment by gilgongo** [comment]
I think Google's use of schema markup is mainly so that they can do things like format rich snippets on search listings, and of course to help people find the site. Doesn't do any harm to check what we have (Google have a tool I'll see if I can find it), but I don't think we need to go into much detail on the operating system versions. I would think just "Windows, macOS, Linux" would be enough?  

EDIT:

Yes, what we have looks OK as far as I can tell - although I'm not sure what `"offers"` would do (and is `alternateName` what we want?). Might remove that perhaps.

**Comment by ann0see** [comment]
I think we could leave it like that. Therefore closing. If this needs more discussion, please re-open
