### ISSUE TITLE
Documentation updates for 3.8.2

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#682]
The following updates need documenting:

- [x] Reorder of serverdlg bits https://github.com/jamulussoftware/jamulus/pull/2177
- [x] Server tray icon update https://github.com/jamulussoftware/jamulus/pull/2231 (exists as part of [server UI PR](https://github.com/jamulussoftware/jamuluswebsite/pull/677), but bring forward)
- [x] Add Meter Style Selection Option https://github.com/jamulussoftware/jamulus/pull/1688

**Comment by pljones** [comment]
Apologies for editing your message to correct the links.

**Comment by gilgongo** [comment]
OK PR's there for review.
