### ISSUE TITLE
Update it web translation for 3.8.2

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#691]
Hi @dzpex,

We are getting ready for the 3.8.2 release and have created the [next-release](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..next-release)).

We would be happy if you updated the translations for **it** by **2022-02-13**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `next-release` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- New/changed images are listed at the end of this issue. [Generate new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your image `.inc` files.
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **next-release** branch with the subject `Update it web translation for 3.8.2`,
- Link your PR(s) to this issue by including `Fixes #691` in the PR content.

Suggested commit and PR message:
```
Update it web translation for 3.8.2

Fixes #691
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/README.md#translating).

Thanks for contributing to Jamulus!

---

**New/Changed screenshots**:

Please [replace with new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your screenshots here, and use those URLs in
your `.inc` files.

![settings-profile](https://user-images.githubusercontent.com/4561747/150635632-df083c6e-94d2-4ab8-a81c-18c7cc0c158d.png)

**Comment by ann0see** [comment]
@dzpex could you please give us a short update if someone works on this translation? Since the translation is quite outdated, does it make sense to remove it?
