### ISSUE TITLE
Suggest ASIO4ALL 2.15 (final)

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#706]
https://www.asio4all.org/ now lists 2.15 final

- [ ] Check that it is working
- [x] Upload asset
- [ ] Update recommendations on the website

The changelog says (among other things):
> Avoid using “Stereo Mix” input in default configuration.

This would be a huge improvement for new users.

(I'm not planning to work on this for now)

cc @ann0see @ignotus666

**Comment by ann0see** [comment]
> Avoid using “Stereo Mix” input in default configuration.

Finally!!!

**Comment by ann0see** [comment]
Tested on Windows, but at least for me the microphone didn't work (no input). But that might also be due to some strange configuration on my end.

@gilgongo could you test the new ASIO4ALL version please?

**Comment by ann0see** [comment]
Ok. Could get it to work so so. But I think that's the case with Jamulus + ASIO4ALL always (the Realtek Drivers are probably not good). I'd put it instead of the beta but still link older versions (and maybe KoordASIO).

**Comment by ann0see** [comment]
Ok. Updated it on the website.
