### ISSUE TITLE
Update headless installation guide

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#707]
**URL**

https://jamulus.io/wiki/Server-Linux

Needs a good review – we’re suggesting to modify the systemd files directly – that’s unneeded
The page is hidden behind a wall of text in the server admin guide (cc: @pljones who mentioned it in the chat.)

I think this file needs to be reviewed. 

Please post all related issues to the Linux headless server installation here (as Checklist)

**Comment by jujudusud** [comment]
Also keep in mind that some things are already written in [COMPILING.md](https://github.com/jamulussoftware/jamulus/blob/master/COMPILING.md)

**Comment by ann0see** [comment]
Thanks for the pointer. Probably it needs restructuring

**Comment by pljones** [comment]
Google searches that should find jamulus.io ahead of anything else, with the preview clearly showing a good - non-frightening - match:

> How do I install Jamulus in the cloud

We're third down the list, after a YouTube video and the famous Facebook idiots' Guide.

> How do I install Jamulus on Ubuntu

Yay!  We're first - although it's not the headless install, of course -- but that _is_ second, so not bad.

> How do I configure Jamulus server

Several YouTube videos.  Desktop usage on our site.  More videos.  Hey!  A Sound On Sound mention from 2020 which barely mentions the server.  (Esh, the UI's improved.)

> How do I run a Jamulus server for my band

Pretty much the same results as above.  The response from jamulus.io looks pretty technical so might put people off (port forwarding and stuff).


There's probably others but I can't think of them now -- if you do, add a comment.

**Comment by ann0see** [comment]
I think at the moment the site is structured to push off people running servers… that might be why our SEO isn’t that good.

**Comment by pljones** [comment]
> I think at the moment the site is structured to push off people running servers… that might be why our SEO isn’t that good.

The idea is to get anyone searching onto jamulus.io, where we can get them to think
- should I run a server _at all_?  (i.e. am I asking the right question)
- will one of the public servers do for what I want? (advantages / disadvantages)
- will a hosted solution provide what I need? (advantages / disadvantages)

Only after that would we describe the options available and how to achieve them.  Currently we've little pulling people in, so they're going off and following potentially unhelpful guidance.

**Comment by gilgongo** [comment]
Please review https://github.com/jamulussoftware/jamuluswebsite/pull/715  if you want to make any more changes that myself and @pljones have not already made.

**Comment by ann0see** [comment]
Done.

**Comment by gilgongo** [comment]
> I think at the moment the site is structured to push off people running servers… that might be why our SEO isn’t that good.

I'm not an SEO expert by any means, but I think the prevailing wisdom is that Google will probably push YouTube videos above text results because... they own YouTube (we could change that by running ads of course). But also YouTube videos are good for us if they link to us, so having them first isn't too bad and if (as Google would tell it) people prefer watching videos to reading text.

I'm pretty sure though that **by far** the biggest reason why we don't get as much traffic as we think we want from Google is that we don't get enough link benefit from other sites. If I see a mention of us on the web and they don't link to us, then I try and contact the author to ask.

**Comment by gilgongo** [comment]
Now that we have https://github.com/jamulussoftware/jamuluswebsite/pull/715 and https://github.com/jamulussoftware/jamuluswebsite/pull/715 can we close this or is it now about [COMPILING.md](https://github.com/jamulussoftware/jamulus/blob/master/COMPILING.md)?

**Comment by ann0see** [comment]
I don’t think it’s fixed now since the file is still a bit too big in my opinion

**Comment by gilgongo** [comment]
OK sure. Feel free to do PR as I think myself and @pljones think it's OK. That's not to say it can't be improved of course.

**Comment by ann0see** [comment]
Going to close this as my PR got merged. Other issues have been opened by pljones.
