### ISSUE TITLE
[Bug] All binary download links are broken since release of 3.8.2

### ISSUE THREAD

**Issue by pianojoe** [jamulussoftware/jamulussoftware.github.io#709]
**URL**
[Please provide the url of the page in question.](https://jamulus.io/wiki/Installation-for-Macintosh)

**Describe the bug**
On this page, the download button links to https://github.com/jamulussoftware/jamulus/releases/download/r3_8_1/jamulus_3.8.2_mac.dmg which does not exist. Please update the link to refer to the correct URL https://github.com/jamulussoftware/jamulus/releases/download/r3_8_2/jamulus_3.8.2_mac.dmg

Thank you.

**Comment by hoffie** [comment]
Thanks for the report! This also affects the other platforms as the root URL is wrong. Fixing in a second.
