### ISSUE TITLE
Reduce likelihood for broken release downloads

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#711]
Follow-up to #709.

- [x] Should the checklist be modified to point out that the root URL has to be updated as well?
- [ ] Can a CI check catch this?
- [x] Why did my link checker not catch this (I might ignore non jamulus.io URLs... or it might run not frequently enough)?

**Comment by ann0see** [comment]
>  Should the checklist be modified to point out that the root URL has to be updated as well?

Yes, sure ;-)

> Can a CI check catch this?

If we got a working link-checker in the CI, sure (did some work here: https://github.com/jamulussoftware/jamuluswebsite/pull/698 but I thought it's not worth it). There were a few smaller problems (gilgongo updated the links by committing to release instead of next-release) which might have stopped us checking.

**Comment by hoffie** [comment]
> Why did my link checker not catch this (I might ignore non jamulus.io URLs... or it might run not frequently enough)?

My `wget` call was missing `--span-hosts`, so it'd ignore Github URLs. It now does a single-depth check so it should catch broken downloads now.

**Comment by pljones** [comment]
Any status update, @hoffie?  This is in backlog - is it likely to be ready for 3.9.0?

**Comment by hoffie** [comment]
Well, the live URL checker I'm running has been updated. The checklist update should be a small change. If/when and by whom the other part (CI) is done, is questionable.
As this is mainly a process task, it doesn't have to be tied to the release, IMO.

**Comment by pljones** [comment]
How's progress?

**Comment by pljones** [comment]
I'll drop from the tracker as we don't need to track it.

**Comment by ann0see** [comment]
Closing as
> Well, the live URL checker I'm running has been updated.

And the Checklist was updated.
