### ISSUE TITLE
[Bug] Release announcement template: Emojis don't work with all platforms

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#712]
**URL**
https://jamulus.io/contribute/Release-Process#release-announcement doesn't render for me on Firefox/Linux (neither do the actual announcements on Github or the .md file in vim). Might be a platform-/font-related issue.

**Comment by ann0see** [comment]
Firefox-esr does show them for me; iOS not. I‘d say we should change the character then.

**Comment by ann0see** [comment]
Does ↓ render for you?

Alternatives: ↡ ⇟ ↓ ⇟ (maybe some are similar)

See https://www.compart.com/de/unicode/block/U+2B00 for arrows

**Comment by hoffie** [comment]
Yes, all 5 which you posted do render for me.
The following also render for me and might fit?

[⬇ U+2B07](https://emojipedia.org/emoji/%E2%AC%87/)
[📥 U+1F4E5](https://emojipedia.org/emoji/%F0%9F%93%A5/)

Edit: Note though that Github seems to employ logic to replace my two examples with actual images...? Not a blocker at all for us, maybe even an advantage for compatibility.

**Comment by ann0see** [comment]
Yes, both also render for me. However they look like emojis so I'm not sure if they fit the style.

**Comment by ann0see** [comment]
Would ↓ be ok for you in the announcement?
