### ISSUE TITLE
Document JSON-RPC api

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#717]
As soon as https://github.com/jamulussoftware/jamulus/pull/1975 is merged, we need to link the JSON-RPC.md file somewhere from the website. 

Where should the link be? Server admin? User manual? Tips and Tricks?

**Comment by pljones** [comment]
I'd say we need
* what it is, how to use it, which links to
* what the protocol looks like

as separate pages - as the protocol could change whilst "what it is and how to use it" should be more or less static.

Then the "what it is and how to use it" would be linked from the client and server pages where it should get a simple mention.

**Comment by ann0see** [comment]
The link to the actual documentation should be JSON-RPC.md in the main repo under the docs/ folder

**Comment by gilgongo** [comment]
> * what it is, how to use it, which links to
> * what the protocol looks like

Do we have texts for these already in https://github.com/jamulussoftware/jamulus/pull/1975? I seem to recall we did, but where/are there two PRs?

**Comment by gilgongo** [comment]
BTW I'm not qualified to write anything on this so I won't do it. But structure-wise, I agree we should just plonk in a brief "what it is, how to use it" into Software-Manual and Running-a-Server (I'd add a section after Command Line Options) and then put the hard docs into the repo .md.

**Comment by ann0see** [comment]
Just added a link on the cli page. Client and server admin manual should also have it mentioned.

**Comment by pljones** [comment]
Moving to 3.9.1 -- the API isn't finalised as of 3.9.0 so documentation isn't pressing.

**Comment by ann0see** [comment]
Also there are things which need to be updated in the app: https://github.com/jamulussoftware/jamulus/pull/2704#discussion_r916870904

**Comment by pljones** [comment]
Bumping to 3.10.0.  There are a few more bits that need doing for JSON-RPC.
