### ISSUE TITLE
Document Raspberry .debs

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#728]
With https://github.com/jamulussoftware/jamulus/pull/2526 merged, we now provide armhf (32bit) .deb packages which are Raspberry-compatible. We should probably still announce them as experimental and ask for feedback.
They've been tested on Raspberry 3 and 4 so far. We should also ask if there's demand for 64bit builds.

- [x] Docs
- [x] Release announcement platform list
- [x] Website download links ("Raspberry-compatible (32bit)"?)

**Comment by ann0see** [comment]
Docs means:
- removing all ARM related compilation instructions
- adding links (https://github.com/jamulussoftware/jamuluswebsite/blob/37fb3f136e921bd615cddd439a5081cc5fefdf74/_config.yml#L16)

**Comment by ann0see** [comment]
Just marked the "docs" as finished

**Comment by ann0see** [comment]
>  Website download links ("Raspberry-compatible (32bit)"?)

Is this also done?

**Comment by ann0see** [comment]
Closed since I've now also updated the release announcement
