### ISSUE TITLE
"Running a Server" sections on "Running" and "Configuration" need rewriting

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#729]
Currently the page has pieces of information that are useful when configuring a server for the first time scatter across several sections.  These need reworking so that information is more easily found.

The introductory section makes a vague reference to server performance but there was more information available somewhere (one of the multi-threading issues, if I remember correctly) that could be included here to help people understand how to size their server (e.g. cloud hosted VM or bare metal server).

There are also several examples given of how to run the server but these aren't explained clearly.  To be helpful, more explanation of the examples should be given.

Sections on network configuration (i.e. router set up, firewall set up, dynamic DNS) that are not about Jamulus configuration should be in their own section and referenced.  (Currently they're under "Unregistered Server".)

**Comment by gilgongo** [comment]
I agree, and add that if we feel the doc should be expanded (eg with more explanation of the examples) then we should not be afraid of length.  The attempt to shorten the guide in https://github.com/jamulussoftware/jamuluswebsite/pull/725 was fine as a bit of gardening though.

Aside from the things you mention here, you mentioned elsewhere that there is also the issue (now that we assume GUI servers are a minority sport) of combining the CLUI and GUI modes which are connected by common info like port forwarding, recording, delay panning, etc. So (and I can't **BELIEVE** I'm saying this!) yet another total re-write. 

Perhaps along the lines of:

- intro
- installation
- configuration/maintenance
- list of all functions/options

Some challenges with the above though, but we'll see...

**Comment by pljones** [comment]
I'm tagging this for 3.10.0 as I feel it's not going to get pushed at all unless it's got a release assigned.  At least this way we keep assessing it each cycle.

**Comment by gilgongo** [comment]
I've not forgotten about this BTW. I just need to build up the courage to actually do it :-)

**Comment by gilgongo** [comment]
> Some challenges with the above though, but we'll see...

OK thinking about the structure of this again, I might try the following layout (these are not actual heading names - decide those later):

- Intro and Concepts (eg requirements, Registered/Unregistered etc.)
- Installation instructions
- Configuration options
- Maintenance/Misc (eg backup, logs, upgrades and links to troubleshooting, points to note about the GUI?)

The Configuration options would be the core of it all, essentially the [Command Line Options](https://jamulus.io/wiki/Running-a-Server#command-line-options) section as today, but expanded more like we have it in the [User Manual](http://127.0.0.1:4000/wiki/Software-Manual) (essentially a list of each function explained). 

An important thing to note is that _I would not reference the GUI_ (so no screenshots needed, ~~no separate [Servers on the desktop](https://jamulus.io/wiki/Running-a-Server#servers-on-the-desktop) section, perhaps~~). This is mainly to avoid duplication (the cardinal sin of collaborative docs) as I think anyone reading the CLUI explanation of a given command could (in principle - might be some exceptions eg server status icon) find that in the GUI without much trouble. 

So overall, I'm hoping it would be easier to find stuff (eg everything related to recording) and that each feature/function might have it's own URL. This (and again to fight duplication) might also even replace the current help text in the GUI with links to the relevant section on the website? Not sure if we can do that though.

BTW, this interesting [image map approach for Audacity](https://manual.audacityteam.org/man/searching_the_manual.html#imagemap) - might be worth a try (and for the client?). But that would be for later. 

Thoughts welcome. Meanwhile, I'll rough it out in a Google doc to see what issues arise.

EDIT: I'm also not going to be concerned with length. So with the exception of nuking the GUI stuff, I intend to keep the text mostly as it is. But we'll see.

EDIT 2: After an initial pass, I think this may mean we need to combine what options do with how to use them, which in turn means we'll probably need to group them together (eg a "Recording" section which includes  `--recording` and `--norecord`. a "Registered Servers" section which includes `--directoryserver`, `--serverinfo` etc.). This may break the "single URL for each option" idea, but that's a nice to have.

**Comment by gilgongo** [comment]
Done now. 

Some conversation about whether we should add a "quick start", but I don't know how that can work if you don't  know the difference between server types, port forwarding and whatnot first. Maybe somebody can do that later though.
