### ISSUE TITLE
Link JACK build on Windows page

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#739]
I think we should link the JACK download on the windows page too (but less prominent without a button) on the Windows install page. 
Any disadvantages?

**Comment by pljones** [comment]
In that case, should we link Jack for Windows, too, as it's a dependency?  (We can't do similar for the ASIO version, as it's hardware-dependent - although we probably do point to ASIO4ALL somewhere.)

**Comment by ann0see** [comment]
Agree.

**Comment by jujudusud** [comment]
I can't see any disadvantages. It is always nice to Say "Hey, there is another possibilité here!".
