### ISSUE TITLE
Rephrase --recording on CLI Page

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#756]
@gilgongo this needs to be rephrased. I think it's not well written. What it does is basically making recording available but it needs to be enabled via JSONRPC or SIGUSR

_Originally posted by @ann0see in https://github.com/jamulussoftware/jamuluswebsite/pull/747#discussion_r883978105_

**Comment by pljones** [comment]
Above is incorrect.

_By default_, recording will start whenever there's something to record, if a recording directory is given.

To prevent that behaviour, `--norecord` must be supplied on the command line.

**Comment by ann0see** [comment]
As I said, it needs to be re-phrased. At least it's a bit confusing. If -R and --norecord is set, the server can record, but doesn't. If -R is set, the server records by default, I think?

**Comment by pljones** [comment]
`sets directory to contain recorded jams` is insufficient.  It's never _just_ done that.  It's always also turned on the "record when a session is active" state.  The text that's there now isn't what I proposed.

`disables recording (when enabled by default by -R)` is also misleading as it doesn't _prevent_ recording (the "disabled" wording may also be in the GUI with this wrong meaning).  What it does is set the default state to not record when a session is active.

The GUI allows that state to be toggled.  It also also allows triggering a new recording.  Both those actions are also available through SIGUSR1/2 (on *nix) and JSON-RPC.

So let's see...
```
-R, --recording       set server recording directory (server will record when a session is active by default)
    --norecord        set server not to record by default when recording is configured
```
How's that?

**Comment by ann0see** [comment]
Yes. I'd stress the fact that by default recording is enabled a bit more (not in parentheses)

Maybe -R could in future take two parameters: -R (recording directory, default recording state[on,off]). Probably requires the CLI parsing to be adapted

**Comment by pljones** [comment]
> Probably requires the CLI parsing to be adapted

We could have an optional alternative syntax of `-R [0|1];[path]`, so if it starts `0;` or `1;` it's the flag for off/on by default, otherwise it's the existing on by default behaviour.  That's backwards compatible and removes the _need_ for `--norecord` (which would still be supported as we love being backward compatible).

**Comment by ann0see** [comment]
Yes. Sounds good.

**Comment by ann0see** [comment]
@pljones since the translation hasn't started yet for the website, would you mind changing this and open a PR on the website with your proposal: https://github.com/jamulussoftware/jamuluswebsite/issues/756#issuecomment-1164861183 ?

**Comment by ann0see** [comment]
Actually this is probably the text which I thought was already changed in the app.

**Comment by pljones** [comment]
Mm, I don't think this has had an issue in the jamulussoftware/jamulus project raised to fix the app yet, no.

**Comment by ann0see** [comment]
I've now opened two PRs on this. Once they're merged this issue can be closed
