### ISSUE TITLE
Update de web translation for 3.9.0

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#774]
Hi @Helondeth, @ewarning,

We are getting ready for the 3.9.0 release and have created the [next-release](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..next-release)).

We would be happy if you updated the translations for **de** by **2022-07-22**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `next-release` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- New/changed images are listed at the end of this issue. [Generate new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your image `.inc` files.
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **next-release** branch with the subject `Update de web translation for 3.9.0`,
- Link your PR(s) to this issue by including `Fixes #774` in the PR content.

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Suggested commit and PR message:
```
Update de web translation for 3.9.0

Fixes #774
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/README.md#translating).

Thanks for contributing to Jamulus!

---

**New/Changed screenshots**:

Please [replace with new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your screenshots here, and use those URLs in your `.inc` files.

![settings-profile](https://user-images.githubusercontent.com/4561747/178144679-bef8518c-f095-4848-86bf-7639cb508505.png)

![server-window-setup](https://user-images.githubusercontent.com/4561747/178142684-1b85e654-78be-4909-a76c-945d7a0f7ccc.png)

![server-window-options](https://user-images.githubusercontent.com/4561747/178142687-da256fa5-d7b8-47ab-9265-63c3c9760841.png)

**Comment by ignotus666** [comment]
Please note that the documents "Include-QOS-Windows.po" and "Server-Linux.po" do not need translating as they have been removed from the documentation (though did not get removed from the PO folders). However, some of their content has been moved to other documents so it would be good if you update your translation memory to take advantage of any strings that had already been translated.

**Comment by ignotus666** [comment]
Just realised @reinhardwh hasn't been added to the message here - he's the main contributor of the DE translation.

**Comment by pljones** [comment]
Aha, thanks @ignotus666!  We'll need to get the script updated.

**Comment by reinhardwh** [comment]
Hello @ann0see,
I am away from keyboard for next 2 weeks and cannot work on DE translations right now.
Could somebody else take updating the URLs?

**Comment by ann0see** [comment]
No problem. Translations can also be added post release on the website.
The links will be automatically updated by us, so nobody would get the old version of the app anyway

**Comment by pljones** [comment]
Removing from Release 3.9.0 - this can be completed after the release.

**Comment by ann0see** [comment]
@ewarning @reinhardwh any updates here?

**Comment by reinhardwh** [comment]
Hello,
I am currently on Business Trip in SFO
I will look into this next week
2022-08-22
Hope thats ok.

**Comment by ann0see** [comment]
Yeah. No problem.

**Comment by ann0see** [comment]
I'll close this now as probably it's worth working on 3.9.1 from now on. The translation files on weblate are synced with the next-release branch.
