### ISSUE TITLE
Update fr web translation for 3.9.0

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#776]
Hi @jujudusud, @trebmuh,

We are getting ready for the 3.9.0 release and have created the [next-release](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..next-release)).

We would be happy if you updated the translations for **fr** by **2022-07-22**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `next-release` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- New/changed images are listed at the end of this issue. [Generate new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your image `.inc` files.
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **next-release** branch with the subject `Update fr web translation for 3.9.0`,
- Link your PR(s) to this issue by including `Fixes #776` in the PR content.

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Suggested commit and PR message:
```
Update fr web translation for 3.9.0

Fixes #776
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/README.md#translating).

Thanks for contributing to Jamulus!

---

**New/Changed screenshots**:

Please [replace with new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your screenshots here, and use those URLs in your `.inc` files.

![paramètres-monprofil](https://user-images.githubusercontent.com/12748768/179051420-159a2024-f672-4e24-a492-b4bd86278d68.png)

![parametres-serveur](https://user-images.githubusercontent.com/12748768/179054052-da19298e-f3d5-440d-a560-4e502ada1544.png)

![options-serveur](https://user-images.githubusercontent.com/12748768/179054398-8e659c23-3516-4489-8319-c3cf1ea68053.png)

**Comment by ignotus666** [comment]
Please note that the documents "Include-QOS-Windows.po" and "Server-Linux.po" do not need translating as they have been removed from the documentation (though did not get removed from the PO folders). However, some of their content has been moved to other documents so it would be good if you update your translation memory to take advantage of any strings that had already been translated.

**Comment by jujudusud** [comment]
> Please note that the documents "Include-QOS-Windows.po" and "Server-Linux.po" do not need translating

Good to know. Thanks.

**Comment by jujudusud** [comment]
Screenshots are now ok for the next release 3.9.0.

**Comment by jujudusud** [comment]
Second one:
Server setup.
![parametres-serveur](https://user-images.githubusercontent.com/12748768/179054052-da19298e-f3d5-440d-a560-4e502ada1544.png)
