### ISSUE TITLE
Update nl web translation for 3.9.0

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#778]
Hi @henkdegroot,

We are getting ready for the 3.9.0 release and have created the [next-release](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release) branch ([full diff](https://github.com/jamulussoftware/jamuluswebsite/compare/release..next-release)).

We would be happy if you updated the translations for **nl** by **2022-07-22**.

Please

- Start your work in your fork on a branch based on jamuluswebsite's `next-release` branch.
- Update the language-specific files using your favorite editor (or directly on Github),
- New/changed images are listed at the end of this issue. [Generate new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your image `.inc` files.
- Commit and push your changes to your fork,
- Open a Pull Request with your translations to the **next-release** branch with the subject `Update nl web translation for 3.9.0`,
- Link your PR(s) to this issue by including `Fixes #778` in the PR content.

Suggested commit and PR message:
```
Update nl web translation for 3.9.0

Fixes #778
```

Feel free to use this Issue to discuss anything you need prior to making any PR (and in your native language if needed).

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/README.md#translating).

Thanks for contributing to Jamulus!

---

**New/Changed screenshots**:

Please [replace with new URLs](https://github.com/jamulussoftware/jamuluswebsite/tree/release#adding-screenshots) for your screenshots here, and use those URLs in your `.inc` files.

![settings-profile](https://user-images.githubusercontent.com/4561747/178144679-bef8518c-f095-4848-86bf-7639cb508505.png)

![server-window-setup](https://user-images.githubusercontent.com/4561747/178142684-1b85e654-78be-4909-a76c-945d7a0f7ccc.png)

![server-window-options](https://user-images.githubusercontent.com/4561747/178142687-da256fa5-d7b8-47ab-9265-63c3c9760841.png)

**Comment by henkdegroot** [comment]
Adding Dutch screenshots to this issue, so I can link them in the website update:

![settings-profile](https://user-images.githubusercontent.com/13550012/179161661-d8ef5df9-c199-43b5-8902-1c28f46c185a.png)

![Server_Settings_nl](https://user-images.githubusercontent.com/13550012/178717359-6d949933-2d7c-4089-b487-bc1ff28ed54b.png)

![Server_Options_nl](https://user-images.githubusercontent.com/13550012/178717403-9ad11b79-c09b-4176-84a1-d2def00121a5.png)

**Comment by ignotus666** [comment]
Please note that the documents "Include-QOS-Windows.po" and "Server-Linux.po" do not need translating as they have been removed from the documentation (though did not get removed from the PO folders). However, some of their content has been moved to other documents so it would be good if you update your translation memory to take advantage of any strings that had already been translated.
