### ISSUE TITLE
[Translate] The footer is untranslatable anymore.

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulussoftware.github.io#798]
# Language you want to translate to
All
# Description
The footer is not translated anymore. Is it normal or a problem?
![bas-de-page](https://user-images.githubusercontent.com/12748768/182929622-36b1c870-7f32-4127-bbef-14ccf56d3058.png)
As "software by Volker Fischer and contributors - Want to get involved? " is not ASIO compliance part, it should be translated as before.

**Comment by pljones** [comment]
Yep, that needs splitting.  It wasn't done for 3.9.0 to avoid complicating things too much but we should do it for 3.9.1, I reckon.

**Comment by ann0see** [comment]
@jujudusud should be fixed now.

**Comment by jujudusud** [comment]
Really nice. Thanks again!
