### ISSUE TITLE
Checkbox controls should be "self-labelling"

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulussoftware.github.io#816]
Following up on https://github.com/jamulussoftware/jamulus/issues/2723#issuecomment-1239293096 so it doesn't get lost.

That issue has initial screenshots.  Once they're agreed, I'll post the final ones here along with any further changes needed in the "Software Manual" and "Running a Server" pages.

**Comment by pljones** [comment]
From https://github.com/jamulussoftware/jamulus/pull/2847 builds:

**Linux client screen shots** (`src/clientsettingsdlgbase.ui`)
![image](https://user-images.githubusercontent.com/1549463/189522766-34844d83-64b2-4f05-b5eb-4939b3b081a9.png)
![image](https://user-images.githubusercontent.com/1549463/189522782-db81b289-3490-4e45-b7bc-c22e2b5bcbf2.png)
![image](https://user-images.githubusercontent.com/1549463/188870901-71ed689c-cb79-4316-af27-729abdb1936d.png)

**Linux server screen shots** (`src/serverdlgbase.ui`)
![image](https://user-images.githubusercontent.com/1549463/189522900-f0772d08-ca2e-42e4-a576-40b5d95952d0.png)
![image](https://user-images.githubusercontent.com/1549463/189522910-8eb410d8-6764-404e-969d-157a6e9f588e.png)

----

(Once the github artifacts are built:)
**Windows client screen shots**
![image](https://user-images.githubusercontent.com/1549463/189525609-67a4212c-37cd-4306-ae09-862179375c53.png)
![image](https://user-images.githubusercontent.com/1549463/189525616-13a63899-5d36-4162-b789-8a2ba6485db1.png)
![image](https://user-images.githubusercontent.com/1549463/189525622-d80c0410-5ee4-45d0-84f7-4240c81ec8ac.png)

**Windows server screen shots**
![image](https://user-images.githubusercontent.com/1549463/189525661-affcf406-8ef8-4f9a-9f3c-c1da346fe886.png)
![image](https://user-images.githubusercontent.com/1549463/189525728-2576d525-f0bc-4377-8cd0-6ad304410095.png)

**Comment by ann0see** [comment]
@pljones I'd prefer to not have the Jamulus Private directory address in a screenshot.

**Comment by pljones** [comment]
Bumping as this will _very shortly_ have the merge done for https://github.com/jamulussoftware/jamulus/pull/2996.

**Comment by pljones** [comment]
I'll get new screenshots off the build from main.

**Comment by pljones** [comment]
# Screenshots from current jamulussoftware/jamulus:main build

## Linux
| My Profile | Audio/Network Settings | Advanced |
| --- | --- | --- |
| ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/b73fa678-6863-487d-ab4d-17038fad1d6e) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/3ab5ae8a-452f-44f2-97f8-88f0d7cceb88) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/a5624e71-baf5-4e99-aac2-f1a6ac045d99) |

| Server Setup | Options |
| --- | --- |
| ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/8fa5334c-4252-44ba-97f2-0f15158130a5) |![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/98e6c997-9770-42f8-9669-aa9cc436adf0) |

## Windows
| My Profile | Audio/Network Settings | Advanced |
| --- | --- | --- |
| ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/219642dd-82bd-4c4e-9065-f97c449a1b3d) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/6ce27b14-97e8-4ad0-a641-af42e4adebbc) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/7c3cf548-9898-4458-b09c-a8eea9afe9ef) |


With resizing...
| My Profile | Audio/Network Settings | Advanced |
| --- | --- | --- |
| ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/226f5822-ffa9-48bf-b5bc-8660e55c12c8) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/47f9f7d7-4672-4e23-980e-9299661a6f00) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/94c626af-4f0c-4ee2-968f-816afae1291a) |


| Server Setup | Options |
| --- | --- |
| ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/67437df6-0b51-41e4-88f2-6552d4d81037) | ![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/06685335-2ad4-4f09-a9f3-2c76c34cc5a1) |

**Comment by pljones** [comment]
Looks like the server ones aren't in 3.10.0 docs.

**Comment by ann0see** [comment]
Yeah, the website isn't up to  date yet on the next-release branch

**Comment by pljones** [comment]
Updated website referenced from #931.

**Comment by ann0see** [comment]
@pljones as your PR is now in, please close.
