### ISSUE TITLE
Update po4a for better markdown support

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#817]
Upstream po4a has received several updates recently that improve markdown support. Our scripts currently process .md files as asciidoc and work well enough, but this can be improved. I've been doing some tests on my repo and would like to implement these improvements in our scripts (and update the po4a .deb package in the assets repo). 

These improvements are mainly about stripping out markdown formatting like # (translators don't have to worry about how many there are), ``` (identifying code blocks and treating them as such) and '-' symbols from .po files and some other things. After a .po file update there will be a lot of translated strings that will be marked as fuzzies though, but I can fix those myself.

So to do this update I would like to ask that after merging the translation updates currently on Weblate, we lock it temporarily to avoid conflicts while it gets done. I hope to have time next Monday 12 September during the morning - it should only take a couple of hours. This update should in future reduce the chances of errors made with markdown formatting and save translators from having to worry about it.

**Comment by pljones** [comment]
Can this wait until 3.10.0?

**Comment by ignotus666** [comment]
I don't see why not. The thing is, with weblate translations are coming in constantly, not like before when there were defined pre-release periods. Is there any specific reason you'd prefer to wait?

**Comment by pljones** [comment]
Stability during the release cycle, is really the only thing.  3.9.1 is intended to be out "ASAP" as we don't want anything risking that, like suddenly finding the tools don't work.  If it's something that can be done, tested and proved working without impacting what we have now, then I guess that should be fine.

**Comment by ignotus666** [comment]
Fair enough, it's not urgent so no problem to wait until after 3.9.1. I've been doing testing on my repo but there's always the chance I missed something.

**Comment by ann0see** [comment]
@ignotus666 Any updates here?

**Comment by ignotus666** [comment]
Looking into it again. As it involves changes to po4a scripts, workflows, an updated version of po4a and .po files, it has to be done in a series of PRs and in a certain order.

**Comment by ann0see** [comment]
Closed as the respective PR was merged.
