### ISSUE TITLE
Rename links to Getting Started page to Setup page 

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#821]
I wonder why the English isn't consistent here.  In several places, the page is called "Getting Started".  The file is "Getting Started".  Yet the text here is "Jamulus setup page".  @gilgongo any ideas?

_Originally posted by @pljones in https://github.com/jamulussoftware/jamuluswebsite/pull/811#discussion_r962366493_

**Comment by ann0see** [comment]
https://github.com/jamulussoftware/jamuluswebsite/pull/811#discussion_r962366645

**Comment by gilgongo** [comment]
Was this a legacy from the Great Rebase Problem a few months ago? Seem to recall we had some naming issue we were fixing at the time that related to Getting Started. I suppose we settled for "Getting Started" instead of Setup though?

**Comment by ann0see** [comment]
I don't know honestly. But I think the issue should still be open as I thought there are still inconsistencies.

**Comment by ann0see** [comment]
Closing as not planned as I don't see the issues anymore on next release (at least on my machine)
