### ISSUE TITLE
Document --serverinfo two-letter ISO country code support

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulussoftware.github.io#822]
https://github.com/jamulussoftware/jamulus/pull/2841 should be documented on the website.
We should make the ISO-code-based variant the preferred one and only keep the documentation for "Jamulus 3.9.0 or earlier".

Note: This is nice-to-have for 3.9.1, but in no way mandatory as it doesn't break existing documentation in any way.

**Comment by pljones** [comment]
> Successfully merging a pull request may close this issue.

... or it may not.  It should have, so I'll do it manually.
