### ISSUE TITLE
[Bug] <details> uses invalid css. Should be font-weight: bold

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#839]
https://jamulus.io/wiki/Running-a-Server

**Describe the bug**
fw.css should contain font-weight: bold for details. Currently we use invalid css and thus the TOC doesn't show up in bold.
@gilgongo should we change it? It's an easy fix.

**Comment by gilgongo** [comment]
Feels like it, yes.
