### ISSUE TITLE
[Translate] Add Korean [ko_KR]

### ISSUE THREAD

**Issue by ignotus666** [jamulussoftware/jamulussoftware.github.io#845]
@MarongHappy could you confirm that you would like us to add the files to translate the website into Korean?

**Comment by ann0see** [comment]
As soon as we have a translator, the create translation issues script needs to be updated.

**Comment by ann0see** [comment]
Related to: https://github.com/jamulussoftware/jamuluswebsite/issues/854

**Comment by ignotus666** [comment]
Wow, I failed to adhere to the instructions I created myself... (adding the language code in square brackets). Thanks @ann0see : )

**Comment by ignotus666** [comment]
This person hasn't surfaced here, but they've already started ploughing through the Korean translations on Weblate, so I think it's safe to add them to the translator's list.

**Comment by ann0see** [comment]
As Korean will go live soon, closing
