### ISSUE TITLE
[Bug] found and fixed a typo

### ISSUE THREAD

**Issue by trebmuh** [jamulussoftware/jamulussoftware.github.io#857]
I committed to next-release: https://github.com/jamulussoftware/jamuluswebsite/commit/19f4cd5411efea92fe1ba08a6c03936f106864c3
Hope I did the right way (but I'm not sure hence, I'm opening this issue).

**Comment by ann0see** [comment]
Yes. Strictly speaking that was my initial thought of how the (wiki) part is handled: 
next-release is "unsupervised" and translators are allowed to work on it directly (for smaller things even without PR), while the PR to release must be verified by wikiadmins. 

I think we changed to a dev workflow similar to the website with more "control" meaning PRs are preferred.

**Comment by trebmuh** [comment]
@ann0see OK. I'll try to remember next time to submit a PR instead of straight-committing against next-release.
Thanks for answering me.
