### ISSUE TITLE
[Next-release] User & Server Manual contains a section which is not translated.

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#912]
**URL**
Testing this locally using the next-release branch.
User Manual: http://127.0.0.1:4000/nl/wiki/Software-Manual
Server Manual: http://127.0.0.1:4000/nl/wiki/Running-a-Server

**Describe the bug**
The User Manual contains a section which is not translatable.

![image](https://user-images.githubusercontent.com/13550012/228143816-ed519722-9725-4f53-9574-084862b0cffa.png)

Similar section found in the Server Manual:

![image](https://user-images.githubusercontent.com/13550012/228144989-a6c770e8-9b5b-4c01-89e5-22209ba764ce.png)

**Comment by ignotus666** [comment]
Weird. The GH action for #909 ran correctly but the .po files didn't get updated with this change.

**Comment by ignotus666** [comment]
I re-ran the job, it updated the .po files properly, but now it borked Weblate... AARRGHH. We really must merge Weblate PRs before committing ANY changes to EN files.

**Comment by ignotus666** [comment]
@ann0see I reverted the .po file update that messes up Weblate. I think the way to proceed would be to merge the Weblate PR as it is, re-run the job for #909, and then Weblate would be ready with the update from there.

**Comment by ann0see** [comment]
? I reverted the po file thing yesterday?

**Comment by ann0see** [comment]
Ah. I understand now. I reverted the automated commit to re enable Weblate translations. This disabled the translation of this section. Today you recreated the po files and we got conflicts again. So I'd suggest to wait translating this section. First ensure the Weblate stuff is correct and can be merged.

**Comment by ignotus666** [comment]
Fixed by #921.
