### ISSUE TITLE
[Next-release] List not showing correct in translated webpages

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#913]
**URL**
http://127.0.0.1:4000/nl/wiki/Installation-for-Windows
http://127.0.0.1:4000/nl/wiki/Installation-for-Macintosh
http://127.0.0.1:4000/nl/wiki/Installation-for-Linux

**Describe the bug**
Lists are not showing correct in translated pages.

_Installation for Windows:_
English:
![image](https://user-images.githubusercontent.com/13550012/228335658-b8eccbb2-3aad-4a8a-8e4f-4e35c6d6b6ce.png)

Dutch:
![image](https://user-images.githubusercontent.com/13550012/228335059-f2f11262-0480-459d-bdcc-c4a9108ff110.png)

_Installation for macOS:_
English:
![image](https://user-images.githubusercontent.com/13550012/228335437-e5ac7b9e-500a-4c1c-a7bf-828699136a78.png)

Dutch:
![image](https://user-images.githubusercontent.com/13550012/228335274-4dfb2045-42be-4cbc-bd61-b0ec307b09c4.png)

_Installation for Linux:_
English:
![image](https://user-images.githubusercontent.com/13550012/228336092-20b6d0fb-e4ce-4e7a-819a-e85390ba465e.png)

Dutch:
![image](https://user-images.githubusercontent.com/13550012/228335948-5f5248ed-b070-45cb-b246-94e6bc929382.png)

**Comment by henkdegroot** [comment]
See https://github.com/jamulussoftware/jamuluswebsite/pull/908#issuecomment-1487986764

**Comment by ignotus666** [comment]
Fixed. Translations need updating though.
