### ISSUE TITLE
[Next-release] Translated copyright text not showing

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#914]
**URL**
http://127.0.0.1:4000/nl/

**Describe the bug**
With NL selected as the site language, the text in the navigation and footer section are not showing in Dutch but always show in English.

Navigation section:
![image](https://user-images.githubusercontent.com/13550012/228337962-02202350-41b7-4733-94f1-405471852b37.png)

Footer section:
![image](https://user-images.githubusercontent.com/13550012/228338070-7dea23c3-f97b-4b0f-8c86-a1c07549c2f7.png)

**Comment by henkdegroot** [comment]
I found the cause of this issue and this can be fixed by updating the **_po4a-tools/po4a-create-all-targets.sh** script.

![image](https://user-images.githubusercontent.com/13550012/228350275-01b18bc8-e901-40bc-b9fe-34e675ec662f.png)

The highlighted section needs to be extended to include the reference to the **copyright** file.

![image](https://user-images.githubusercontent.com/13550012/228350559-9fcc42d7-455d-4aa5-89e8-0a3bb9778c88.png)

Not sure if the copyright file also needs be excluded from the threshold calculation.

**Comment by ignotus666** [comment]
@henkdegroot feel free to make a PR with the fix (here and elsewhere) - this week I'm going to be very pressed for time...

I'm not sure about excluding it from the threshold -I'm inclined to think it doesn't need to be- but maybe a quick test to confirm it would be best.

**Comment by henkdegroot** [comment]
Can this issue be linked to #917 ?

**Comment by ignotus666** [comment]
Yes, this can be closed now.
