### ISSUE TITLE
[Next-release] Incorrect link in Running a Server page

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#915]
**URL**
http://127.0.0.1:4000/wiki/Running-a-Server

**Describe the bug**
The red squares show the link and the text which has the link configured.
The correct link is: 127.0.0.1:4000/wiki/Running-a-Server#registered-mode

![image](https://user-images.githubusercontent.com/13550012/228341039-43bcabf7-210a-4d3d-b8c2-c2e88b63bf7f.png)

**Comment by ignotus666** [comment]
Fixed.
