### ISSUE TITLE
[Next-release] Incorrect text in Running a Directory page

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#916]
**URL**
http://127.0.0.1:4000/wiki/Directories

**Describe the bug**
Text in the Directories page refers to Server Types. 

![image](https://user-images.githubusercontent.com/13550012/228342097-abd16eda-5af5-414c-9ec4-9be50e6ae67c.png)

 When you click the link, the target is Server Modes.
![image](https://user-images.githubusercontent.com/13550012/228342356-553f5df0-ad37-45cf-b6e0-b651e1a22724.png)

I would say the Server Types text in the Directories needs to be replace by Server Modes.

**Comment by ignotus666** [comment]
Fixed.
