### ISSUE TITLE
Add documentation for Debian repository

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#937]
Related to: https://github.com/jamulussoftware/jamulus/pull/3013

Once the GPG key is set up on the main repository, the CI should automatically generate a debian repo on releases. This should be documented on the Linux installation page. Probably even as default installation method.
After we've pushed a nightly, I think we can start writing a paragraph.

**Comment by pljones** [comment]
Can this now move back to "In Progress"?

**Comment by ann0see** [comment]
Yes. I'm working on getting the repo stuff fixed. It seems to fail on importing the key even though it seems to do something.
