### ISSUE TITLE
[Bug] Quick Download text contains non-translateable text in next-release branch

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#950]
**URL**
Page header Main Page

**Describe the bug**
Webpage contains text which cannot be translated.

Current webpage (release branch):
![image](https://github.com/jamulussoftware/jamuluswebsite/assets/13550012/0340eda9-2c84-4716-af82-37d4cb631756)

Screenshot webpage (next-release branch):
![image](https://github.com/jamulussoftware/jamuluswebsite/assets/13550012/d4c2971e-b42f-4914-862d-86d87d7c3d64)

**Comment by pljones** [comment]
See comments here for history:https://github.com/jamulussoftware/jamuluswebsite/commit/4407678ddc0902eec64bf3f28c43c6a19eeaf26c

**Comment by henkdegroot** [comment]
Thank you for the quick action.
