### ISSUE TITLE
[Translate] Adding NL images for 310 to repo

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#956]
This issue is to generate user content image for the 3.10 website.

My Profile settings:
![settings-profile-310-nl](https://github.com/jamulussoftware/jamuluswebsite/assets/13550012/499541ee-96ec-4526-bea4-3788a93b64e9)

Audio/Network settings:
![settings-network-310-nl](https://github.com/jamulussoftware/jamuluswebsite/assets/13550012/96b3f2bd-34fd-48e6-b75a-434a2f056d0d)

Advanced settings:
![settings-advanced-310-nl](https://github.com/jamulussoftware/jamuluswebsite/assets/13550012/93f9ddad-dd09-43e3-9b28-8faba15bca11)

**Comment by pljones** [comment]
@henkdegroot if nothing else needs doing, please close.  (I've added it to the 3.10.0 release and marked it Done already.)

**Comment by henkdegroot** [comment]
Just need to update the matching INC files with the appropriate url. Will be submitting a PR for that, which can then close this issue.

**Comment by henkdegroot** [comment]
Can someone confirm the Server Setup and Options image are no longer used and therefore I should remove them?

EDIT: After checking I found they have indeed been removed. So will remove here and in the PR as well.
