### ISSUE TITLE
Text for Device/Audio Device in settings tab does not match with the application

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulussoftware.github.io#959]
The following text does not match the application:

`### Device`

In the application the text is: Audio Device

Link to code:
https://github.com/jamulussoftware/jamuluswebsite/blob/3020a2d48b853c0f5e315c81921fa247078a5f38/wiki/en/Software-Manual.md?plain=1#L155

**Comment by henkdegroot** [comment]
Minor issue, I would change this in a future release. Just created an issue so it won't be missed.

**Comment by pljones** [comment]
Just to be clear...

The English app Client Audio/Network Setup tab looks like this:
![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/d5fee029-3cdc-402a-8ad5-d71afbc5fe1d)

The manual is referring to "Audio Device" - so both the screenshot and text need updating.  (The screenshot will have been updated for 3.10.0 as part of the check box change.)
![image](https://github.com/jamulussoftware/jamuluswebsite/assets/1549463/7245a24c-b7ac-4977-bbd0-9cb94e600a30)

**Comment by henkdegroot** [comment]
> The manual is referring to "Audio Device"

@pljones, I think you mean: The manual is referring to "Device".

**Comment by pljones** [comment]
I mean the manual is refering to "Audio Device".  The text is wrong.  It reads "Device".

**Comment by henkdegroot** [comment]
My bad...not native English....was reading it differently.

**Comment by pljones** [comment]
@henkdegroot do you want to pick this up for 3.11.0?  I'm happy to do it myself if not (for the English).  If so, please feel free to assign yourself.

**Comment by ann0see** [comment]
If all translators agree, we can get this fixed in this release too.

**Comment by pljones** [comment]
Will the change break links?

**Comment by henkdegroot** [comment]
It seems there is no link to this header in any page.

**Comment by jujudusud** [comment]
Ok for me. We have to change the milestone to 3.10 also.

**Comment by ann0see** [comment]
Ok. Weblate is locked now
