### ISSUE TITLE
Ideal link for headless server operator

### ISSUE THREAD

**Issue by mcfnord** [jamulussoftware/jamulussoftware.github.io#971]
For Debian Linux, we distribute this configuration file:

https://github.com/jamulussoftware/jamulus/blob/main/linux/debian/jamulus-headless.service

It has this link in it:

https://jamulus.io/wiki/Command-Line-Options

That page does cover command line options, but starts with client-only options.

Instead, perhaps we should include this link:

https://jamulus.io/wiki/Running-a-Server#server-mode-related-options

While anchored to a specific section, that page does jump right into (headless?) server CLI options.

**Comment by ann0see** [comment]
Should be an easy fix. Tagged as good first issue, so anyone feel free to pick this up.
