### ISSUE TITLE
[Typo] Bad command line in french wiki Running-a-Server

### ISSUE THREAD

**Issue by bugith** [jamulussoftware/jamulussoftware.github.io#974]
https://jamulus.io/fr/wiki/Running-a-Server
Installation Step 1 is badly formated : 

Télécharger le script d’installation : `curl https://raw.githubusercontent.com/jamulussoftware/jamulus/main/linux/setup_repo.sh

 setup_repo.sh`

Should be (one liner):

Télécharger le script d’installation : `curl https://raw.githubusercontent.com/jamulussoftware/jamulus/main/linux/setup_repo.sh > setup_repo.sh`

**Comment by pljones** [comment]
We've a separate patch for the English for this.  The translations will be picked up from that: #968

**Comment by trebmuh** [comment]
Hi @bugith and thanks for pointing out this error.
I'll fix it as soon as it'll be available for translation (it's on a "hold state" for now).

**Comment by bugith** [comment]
> We've a separate patch for the English for this. The translations will be picked up from that: #968

Hi @pljones 
I tried to use weblate for this but the Modules and Languages tabs for Jamulus-website are empty, and I get a white page when I want to "watch"/monitor the project. Maybe I miss something, but I already use it for other projects then I'm not that newb with weblate. Please what's wrong ?

**Comment by bugith** [comment]
> Hi @bugith and thanks for pointing out this error. I'll fix it as soon as it'll be available for translation (it's on a "hold state" for now).

@trebmuh . Are you the one at linuxmao.org? Pleased to meet you here. Here AF from linuxmao.org. Could we quickly PM speak about weblate, because I can't find a nice feature the was on Transifex, that is a community of translators involved in language@project to not pollute the public software forums?
Have a good day

**Comment by trebmuh** [comment]
@pljones : it looks the weblate "running a server" item is still not open for translation after 5 days. Is that on purpose or can you please release it then I can fix the issue? Thanks.

@bugith : salut, oui, c'est moi "olinuxx". Tu peux me PM sur linuxmao.org si tu veux, ou parler dans le forum (c'est encore mieux).

**Comment by ignotus666** [comment]
@trebmuh 

I just realised that a recent merge messed up Weblate (I forgot to merge Weblate's changes first...), which is why it locked up. I'll see if I can fix it.

**Comment by ignotus666** [comment]
Fixed. Please note that "1-Index.md" ("Startpage" on Weblate) has been changed to make it easier to translate (lots of the sentences were broken up at weird places). However, this change means that a large part must be re-translated - though most will be in the translation memory and should be easy enough to do.

**Comment by trebmuh** [comment]
Thanks @ignotus666 . I've been able to push the French translation back to 100% now.
@bugith : the wrong command line should be fixed as well (I've checked it), so I'm closing here now. Thanks for the report.
