### ISSUE TITLE
[Bug] hreflang codes contain unrecognised undersores

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulussoftware.github.io#977]
The Google SEO report for jamulus.io says there is a problem with "unknown language codes" in some links using the "hreflang" property.  This is used in the language switcher,  specifically zh_CN, nb_NO, ko_KR, pt_BR, pt_PT.

It seems that if we can change the UI to show for example "zh-CN" and not "zh_CN", that would fix it.

I don't know how much of a problem this is for displaying content in the relevant Google geographic regions though, but it may be worth fixing.

_PS: Google is probably picking it up from [sitemap.xml](https://github.com/jamulussoftware/jamuluswebsite/blob/release/sitemap.xml) in fact. See my comment below._

**Comment by ignotus666** [comment]
I'll look into it when I get some time. Shouldn't be too hard, just a bit tedious.

**Comment by gilgongo** [comment]
BTW I see these codes also turn up in [our sitemap.xml](https://github.com/jamulussoftware/jamuluswebsite/blob/release/sitemap.xml) (which is I suppose where Google is mainly seeing them). If the root cause turns out to be too difficult, <del>could we hack it there [with a substitution](https://stackoverflow.com/questions/25802204/jekyll-filter-for-regex-substitution-in-content)?</del>   EDIT: Nope. GitHub Pages don't allow user plugins.

**Comment by gilgongo** [comment]
See also [this related issue](https://github.com/jamulussoftware/jamuluswebsite/issues/986).

**Comment by gilgongo** [comment]
I think this problem seems to come from something that `po4a-create-all-targets.sh` is doing with `$lang`.  At least, I can fix it manually my re-naming stuff, but running the script sets it back again (and breaks it).

**Comment by ignotus666** [comment]
@gilgongo are you also re-naming the folders in `_translator-files/po/`? That's where `$lang` gets the language codes from.

**Comment by gilgongo** [comment]
> @gilgongo are you also re-naming the folders in `_translator-files/po/`? That's where `$lang` gets the language codes from.

Ah yes, but I confused myself with the symlinks in the next-release branch.  I think I've sorted it now but need to check.

**Comment by ignotus666** [comment]
Yeah, there's the "1-xx-index.md" files, the folders in `/assets/img/` and `_translator-files/po/`, a regex that needs to be changed in `/.github/workflows/add-lang.yml `(line 21, change the underscore to a -), and then the language code in all the po files for the languages where it's changed. Oh, and the relevant line in `_config.yml`. I think that's it but there may be more. I'm not sure how Weblate will react too, but we'll get to that.

**Comment by gilgongo** [comment]
@ignotus666 OK so now that all seems to be working on my local machine (and I did a link check just in case), does this need to go to release or next-release? I've got a branch on my fork made from next-release (which seems to have some commits relating to the symlinks I'm changing?)

**Comment by ignotus666** [comment]
I'd say it should go to next-release.

**Comment by gilgongo** [comment]
Closing as now incorporated in https://github.com/jamulussoftware/jamuluswebsite/pull/993
