### ISSUE TITLE
Update iOS page as soon as sideloading on iOS/EU is available

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#981]
By EU law apple will soon need to allow sideloading. This may make installing the iOS version easier and should be updated - currently we know nothing about it and how it works unfortunately. But in latest march we should know. 

Also mentioning the lightning to usb camera adapter probably should now also be updated to say something about USB C (newer apple devices have that) also iPads seem to be USB C now.

**Comment by pljones** [comment]
Are there two separate changes here?  Would it be better to treat them separately?  Also, where do the changes refer to?

**Comment by ann0see** [comment]
Yes. They're separate. I just opened the issue to track some changes.

**Comment by ann0see** [comment]
Changes of USB C -> iOS documentation on the iOS install page. But also sideloading is on the same page. Unfortunately we don't know how it looks like yet.

**Comment by ann0see** [comment]
News for iOS sideloading is out. Seems to target mostly larger corporations: https://developer.apple.com/de/support/alternative-app-marketplace-in-the-eu/

Maybe we get into some sort of Fdroid for iOS in future.

**Comment by ann0see** [comment]
Maybe Altstore. But it doesn't seem to be a reasonable way for us on purpose.

**Comment by ann0see** [comment]
Closing, as I don't see that the sideloading is any better with the new terms.
