### ISSUE TITLE
Upgrade ASIO4ALL to v2.16

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulussoftware.github.io#995]
**URL**

https://asio4all.org/version-2-16-released/

A new version of ASIO4ALL has been released. We should update the website. Reading the comments it seems that anti virus software flags it, so we may want to check if it's really safe before setting the link.

**Comment by melcon** [comment]
> Reading the comments it seems that anti virus software flags it, so we may want to check if it's really safe before setting the link

VirusTotal Scan shows only 2 secuyrity vendors flagging it
https://www.virustotal.com/gui/file/c6b2f621a53584c581a9f5ce288d6d88562a062e2859de787c5e5d9453b75c50

**Comment by ann0see** [comment]
Ok. Tested the ASIO4All 2.16 version with my internal sound card and I get sound (internal microphone doesn't work though - but that's expected). External headphones work as *bad* as expected.

**Comment by pljones** [comment]
The only problem we've seen is the site's spamware ads...

**Comment by ann0see** [comment]
Yes... I usually use an ad blocker, so I don't see it.

**Comment by pljones** [comment]
Me too - but it's something we need to be aware of when advising people to visit the site.  Not everyone does, especially the less technically minded setting up for the first time.

**Comment by ann0see** [comment]
Direct download link: https://asio4all.org/downloads/ASIO4ALL_2_16.exe

Since we have this, I don't think we need to put it onto the assets repo?
I mean we can upload it there too - as backup.

**Comment by ann0see** [comment]
Uploaded here: https://github.com/jamulussoftware/assets/raw/refs/heads/main/ASIO4ALL/v2.16/ASIO4ALL_2_16.exe

**Comment by pljones** [comment]
Unless there's an explicit licence to allow redistribution, I'd get rid of that very public redistribution link.

I'm okay with directly referencing the download! 👍🏻

**Comment by ann0see** [comment]
I know that other pages do host ASIO4ALL itself, but I think I'll just change the link...
